### ISSUE TITLE
Error: Error: Failed to access "/Users/------/Library/Application Support/com.bridge.dev/bridge/projects/----------/.bridge/extensions": Directory does not exist: path not allowed on the configured scope: /Users/---------/Library/Application Support/com.bridge.dev/bridge/projects/-----------/.bridge/extensions@tauri://localhost/assets/main-4ce1a948.js:28:2515

### ISSUE THREAD

**Issue by hyjack57785** [bridge-core/editor#1005]
**Summary**

**To Reproduce**

4. Observe result

**Observed behavior**
A clear and concise description of what happened
**Expected behavior**

**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

**Platform (please complete the following information):**

-   OS: [e.g. Windows 10]
-   App Version: [e.g. 0.13.3]

**Additional context**

**Comment by outercloudstudio** [comment]
Please fill out the requested information.
