### ISSUE TITLE
Error: DataCloneError: Failed to execute 'put' on 'IDBObjectStore': (r,s)=>e.then(i=>s(i.transaction(t,r).objectStore(t))) could not be cloned.Error: DataCloneError: Failed to execute 'put' on 'IDBObjectStore': (r,s)=>e.then(i=>s(i.transaction(t,r).objectStore(t))) could not be cloned.    at window.onunhandledrejection (https://tauri.localhost/assets/main-05fed99d.js:28:2506)

### ISSUE THREAD

**Issue by MonkeyD-Cat** [bridge-core/editor#1008]
**Summary**
Vanilla pack linking error

**To Reproduce**

1. Download Vanilla Pack Extension
<img width="548" alt="Screenshot 2023-11-10 140112" src="https://github.com/bridge-core/editor/assets/141637307/0cbb26a1-36b7-44cc-995b-e87456b737a6">

3. Drag vanilla packs onto bridge
4. Click on "Vanilla Pack" to link the vanilla pack
<img width="482" alt="Screenshot 2023-11-10 135947" src="https://github.com/bridge-core/editor/assets/141637307/3d662124-ea30-4fe1-ba73-e4c527317338">

**Observed behavior**
Vanilla packs failed to link
**Expected behavior**
Vanilla packs linking successfuly

**Screenshots / File Attachments**

![image](https://github.com/bridge-core/editor/assets/141637307/965628ed-76df-4e24-a9b3-632ebfb7698c)

![image](https://github.com/bridge-core/editor/assets/141637307/dd663243-a53c-428b-ab1e-2bfac7f3b3ad)

**Platform (please complete the following information):**

-   OS: Windows 10
-   App Version: 2.7.1

**Comment by outercloudstudio** [comment]
Thank you for reporting!
