### ISSUE TITLE
Error: Error: Accessing service without service being definedError: Error: Accessing service without service being defined    at window.onunhandledrejection (https://tauri.localhost/assets/main-05fed99d.js:28:2506)

### ISSUE THREAD

**Issue by ardhi16** [bridge-core/editor#1010]
**Screenshots / File Attachments**
![Screenshot 2023-11-10 232530](https://github.com/bridge-core/editor/assets/36992129/9f545186-17d7-42b8-b99a-25b566cbe969)

**Platform (please complete the following information):**

-   OS: win10
-   App Version: 2.7.1

**Additional context**
Error: Error: Accessing service without service being defined
Error: Error: Accessing service without service being defined
    at window.onunhandledrejection (https://tauri.localhost/assets/main-05fed99d.js:28:2506)

cannot save file

**Comment by outercloudstudio** [comment]
Thank you for reporting this! For now just save files one at a time, that seems to work.

**Comment by outercloudstudio** [comment]
Fixed in 77d7e71e0b812a858e89451cc9aa958bb5ab4f41
