### ISSUE TITLE
when I export and the I import into minecraft, it got minecraft crash

### ISSUE THREAD

**Issue by ardhi16** [bridge-core/editor#1013]
**Summary**

**Observed behavior**
A clear and concise description of what happened
**Expected behavior**

**Screenshots / File Attachments**
![Screenshot 2023-11-11 132432](https://github.com/bridge-core/editor/assets/36992129/f74c7755-0cff-4176-8a91-e5e1a4ee64d0)

**Platform (please complete the following information):**

-   OS: Windows 10
-   App Version: 2.7.2

**Additional context**
I save the file, when I export and the I import into minecraft, it got minecraft crash. I restart the bridge again and still same. I don't know why, I think there's no failed code or something error.

**Comment by outercloudstudio** [comment]
This is fixed in b6a16c4dde3afa8964d0a3ae1a8ee62154646596
