### ISSUE TITLE
why this's yellow line??? 

### ISSUE THREAD

**Issue by ardhi16** [bridge-core/editor#1014]
I can't import into minecraft, failed import and then minecraft crash.

-   OS: Windows 10
-   App Version: 2.7.2

![Screenshot 2023-11-11 150301](https://github.com/bridge-core/editor/assets/36992129/1574266a-040d-4db2-968d-065d11aef109)

**Comment by outercloudstudio** [comment]
The crash has been fixed in b6a16c4dde3afa8964d0a3ae1a8ee62154646596. Not sure what is causing the warning, will look into it though.
