### ISSUE TITLE
Right clicking on the file manager creates an unwanted menu.

### ISSUE THREAD

**Issue by BayExecute** [bridge-core/editor#1023]
**Summary**
When you right-click on the file manager on the application, a second and unwanted menu appears, which I assume it is the Windows'.

**Observed Behavior**
Regardless of whether it is a file or free space, when you right-click on the file manager it generates another menu.

**Expected Behavior**
Second tab should not appear.

[Here is a footage of the issue](https://cdn.discordapp.com/attachments/785135286710829157/1173754245820985344/bridge_bug_report.mp4?ex=65651ad3&is=6552a5d3&hm=c72fd57408234cf7ec8398bee5138c7f75acb6ff6b09c4987d57def54752aea2&
)

I use Windows 10 and Bridge. 2
My application is on the latest version up-to date

**Comment by outercloudstudio** [comment]
Thank you for reporting. The problem here is I can't seem to reproduce this but multiple other users have experienced this.

**Comment by outercloudstudio** [comment]
This is fixed in 782611d4d04c9dced1e8e51ce27b907d669486f8
