### ISSUE TITLE
Error: NotReadableError: The requested file could not be read, typically due to permission problems that have occurred after a reference to a file was acquired.Error: NotReadableError: The requested file could not be read, typically due to permission problems that have occurred after a reference to a file was acquired.    at window.onunhandledrejection (https://tauri.localhost/assets/main-85572592.js:28:2506)

### ISSUE THREAD

**Issue by luigijack999** [bridge-core/editor#1027]
**Observed behavior**
A clear and concise description of what happened
**Expected behavior**

**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

**Platform (please complete the following information):**

-   OS: [e.g. Windows 10]
-   App Version: [e.g. 0.13.3]

**Additional context**

**Comment by outercloudstudio** [comment]
Please fill out the requested information.
