### ISSUE TITLE
Error: Cannot read properties of null (reading 'Sortable1701385637297')TypeError: Cannot read properties of null (reading 'Sortable1701385637297')    at HTMLDocument.p$ (https://tauri.localhost/assets/vendor-1153fe1d.js:53:60506)

### ISSUE THREAD

**Issue by SynnohStrike** [bridge-core/editor#1032]
**Summary**

**To Reproduce**

4. Observe result

**Observed behavior**
A clear and concise description of what happened
**Expected behavior**

**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

**Platform (please complete the following information):**

-   OS: [e.g. Windows 10]
-   App Version: [e.g. 0.13.3]

**Additional context**

**Comment by outercloudstudio** [comment]
Please fill out the requested information.
