### ISSUE TITLE
coding issue

### ISSUE THREAD

**Issue by LUNAxTOKITO** [bridge-core/editor#1037]
so basically when i go to put a command into a function it works but if i change one letter and then put it back or fix something/add something it will say something about a variable not working

this is the line
particle minecrfat:basic_flame_particle ^ ^1 ^2

and if i accidentaly put a letter down and remove it, it says this
![image](https://github.com/bridge-core/editor/assets/113733229/e5106e75-9389-4472-b4cd-47e0b55a21b2)

**Comment by outercloudstudio** [comment]
This is an addon issue. Please make a post in the discord instead.
