### ISSUE TITLE
Error: DataCloneError: Failed to execute 'put' on 'IDBObjectStore': (r,s)=>e.then(i=>s(i.transaction(t,r).objectStore(t))) could not be cloned.Error: DataCloneError: Failed to execute 'put' on 'IDBObjectStore': (r,s)=>e.then(i=>s(i.transaction(t,r).objectStore(t))) could not be cloned.    at window.onunhandledrejection (https://tauri.localhost/assets/main-60dc9ec5.js:28:2506)

### ISSUE THREAD

**Issue by Hugouououo** [bridge-core/editor#1062]
**Summary**
Bridge. error when i drag the folders into Vanilla packs

**To Reproduce**

1. Go to 'Vanilla Packs' extension
2. Drag the bp and rp folders onto bridge
3. Nothing happens
4. Error notification

**Screenshots / File Attachments**
![image](https://github.com/bridge-core/editor/assets/91914712/3ff85de2-9a5d-47a0-b957-3c22100798f8)

**Platform (please complete the following information):**

-   OS: [Windows 11]
-   Bridge. Version: [v2.7.10]

**Comment by outercloudstudio** [comment]
Thank you for reporting 👍
