### ISSUE TITLE
biome is broken

### ISSUE THREAD

**Issue by sean81** [bridge-core/editor#1072]
**Summary**
Biome Creation is broken I try to make a world and i get an error saying biome registry

**Observed behavior**
when I was working on a custom biome i get a error from the biome registry when creating the world
**Expected behavior**
when creating a world, no biome registry error should pop up and the custom biome should generate

**Screenshots / File Attachments**

https://github.com/bridge-core/editor/assets/53882945/95cc290b-9fa4-4eb1-9655-e78ee0223ad8
![Screenshot 2024-02-15 220325](https://github.com/bridge-core/editor/assets/53882945/abada42c-c911-495c-b7b0-81e67e5df22d)

**Platform (please complete the following information):**

-   OS: windows 11
-   App Version: 2.7.11

**Additional context**

**Comment by outercloudstudio** [comment]
This is not the place for this question. You may join the discord and ask in an addon help channel instead.
