### ISSUE TITLE
Fails to import vanilla packs from 1.20.70.25: Error: DataCloneError: Failed to execute 'put' on 'IDBObjectStore': (r,s)=>e.then(i=>s(i.transaction(t,r).objectStore(t))) could not be cloned.Error: DataCloneError: Failed to execute 'put' on 'IDBObjectStore': (r,s)=>e.then(i=>s(i.transaction(t,r).objectStore(t))) could not be cloned.    at window.onunhandledrejection (https://tauri.localhost/assets/main-fb217f93.js:28:2506)

### ISSUE THREAD

**Issue by AshtonScripts** [bridge-core/editor#1097]
**Summary**
Gives an error when dragging vanilla bp and rp folders together into bridge and clicking on vanilla pack option

**To Reproduce**
dragging vanilla 1.20.70.25 bp and rp folders together into bridge and clicking on vanilla pack option

**Observed behavior**
The vanilla pack tab continued to act as if i had never imported anything and an error appeared saying
"Error: DataCloneError: Failed to execute 'put' on 'IDBObjectStore': (r,s)=>e.then(i=>s(i.transaction(t,r).objectStore(t))) could not be cloned.Error: DataCloneError: Failed to execute 'put' on 'IDBObjectStore': (r,s)=>e.then(i=>s(i.transaction(t,r).objectStore(t))) could not be cloned.    at window.onunhandledrejection (https://tauri.localhost/assets/main-fb217f93.js:28:2506)"
**Expected behavior**
The vanilla pack tab should contain the vanilla packs that i just imported

**Screenshots / File Attachments**
![image](https://github.com/bridge-core/editor/assets/95329493/aa371792-e701-4eba-8fa7-6eb38080f73e)

**Platform (please complete the following information):**

-   OS: Windows 11
-   App Version: v2.7.15

**Comment by BenjaminJameson** [comment]
Same issue for me but OS is MacOS
