### ISSUE TITLE
AVG finding virus in v2.7.15 and v2.7.16

### ISSUE THREAD

**Issue by SpunkieMunkie** [bridge-core/editor#1105]
**Summary**
When I try to update...AVG finds malware-gen [trj] and puts it into quarantine.

**To Reproduce**

1. Have AVG installed
2. Update Bridge
3. AVG puts file into quarantine
4. Is this a false positive and safe to install?

**Observed behavior**
AVG finds a trojan virus and puts it in quarantine.
**Expected behavior**
Install new version as normal

**Screenshots / File Attachments**
![2024-04-08 (1)](https://github.com/bridge-core/editor/assets/51289567/4adb8e6f-722c-4591-ba87-6809e7dc0846)

**Platform (please complete the following information):**

-   OS: [Windows 10]
-   App Version: [2.7.15 & 2.7.16]

**Additional context**
Did you add a new file since 2.7.14 that would appear as a virus?
![2024-04-08 (1)](https://github.com/bridge-core/editor/assets/51289567/2a579d6b-4085-4941-842a-44335961e170)

**Comment by outercloudstudio** [comment]
I'm reporting this to AVG now.

**Comment by SpunkieMunkie** [comment]
I can also mark as false with them. It's good to install then, correct?

Thank you
SpunkieMunkie

**Comment by outercloudstudio** [comment]
Yes, It should be good to install after you make it as a false positive.
