### ISSUE TITLE
Error: TypeError: Failed to fetch dynamically imported module: https://editor.bridge-core.app/assets/editor.main-7e22fbc1.jsError: TypeError: Failed to fetch dynamically imported module: https://editor.bridge-core.app/assets/editor.main-7e22fbc1.js    at window.onunhandledrejection (https://editor.bridge-core.app/assets/main-a445007f.js:28:2506)

### ISSUE THREAD

**Issue by treblox** [bridge-core/editor#1106]
**Summary**

**To Reproduce**

4. Observe result

**Observed behavior**
A clear and concise description of what happened
**Expected behavior**

**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

**Platform (please complete the following information):**

-   OS: [e.g. Windows 10]
-   App Version: [e.g. 0.13.3]

**Additional context**

**Comment by outercloudstudio** [comment]
Please fill out the requested information.
