### ISSUE TITLE
Error: Error: Trying to access projectPath before tab finished loadingError: Error: Trying to access projectPath before tab finished loading    at window.onunhandledrejection (https://editor.bridge-core.app/assets/main-22363962.js:28:2506)

### ISSUE THREAD

**Issue by Navjill** [bridge-core/editor#1109]
**Summary**

**To Reproduce**

4. Observe result

**Observed behavior**
A clear and concise description of what happened
**Expected behavior**

**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

**Platform (please complete the following information):**

-   OS: [e.g. Windows 10]
-   App Version: [e.g. 0.13.3]

**Additional context**

**Comment by outercloudstudio** [comment]
Please fill out the requested information.
