### ISSUE TITLE
Error: RangeError: Maximum call stack size exceededError: RangeError: Maximum call stack size exceeded    at window.onunhandledrejection (https://editor.bridge-core.app/assets/main-51d7d002.js:28:2506)

### ISSUE THREAD

**Issue by DeadLite25** [bridge-core/editor#1124]
i can't import my project because of the Maximum call stack size exceeded error

1. Go to 'Project'
2. Click on 'Import Project'
3. Select project file
4. Should have imported my project

When i import my project file its show error Maximum stack size exceeded and does not import my project.

Should have imported my project

-   OS: Android/Chrome Website
-   App Version: 2.7.20

I was trying to import my addonpack which has more then 10k files, but its gives me error whenever i try to improve my addonpack
```[tasklist]
### Tasks
```

**Comment by outercloudstudio** [comment]
How large is you project?

**Comment by DeadLite25** [comment]
.brproject file size is 33.5mb

**Comment by DeadLite25** [comment]
no reply since last two weeks

**Comment by outercloudstudio** [comment]
I have reproduced this issue and am working on a solution.

**Comment by DeadLite25** [comment]
i found another bug thats if i try to import more then 10 files its just cancle out importing files but if i try to import 10 or less then 10 files its import files properly
