### ISSUE TITLE
Unable to link Vanilla Packs using Vanilla Packs plugin

### ISSUE THREAD

**Issue by SirenGlitch** [bridge-core/editor#1127]
**Summary**
Error (see below) occurs everytime I try to drag and drop extracted Vanilla Packs

**To Reproduce**

1. Download any Vanilla Pack from https://bedrock.dev/packs
2. Make sure "Vanilla Pack Viewer" extension is installed
3. Extract downloaded pack and drag "behavior_pack" or "resource_pack" onto Vanilla Packs tab of bridge.
4. Select Vanilla Pack
5. Observe result

**Observed behavior**
`Error: DataCloneError: Failed to execute 'put' on 'IDBObjectStore': (r,s)=>e.then(i=>s(i.transaction(t,r).objectStore(t))) could not be cloned.
Error: DataCloneError: Failed to execute 'put' on 'IDBObjectStore': (r,s)=>e.then(i=>s(i.transaction(t,r).objectStore(t))) could not be cloned.
    at window.onunhandledrejection (https://tauri.localhost/assets/main-a9d18057.js:28:2506)` 

**Expected behavior**
The pack would link/import successfully

**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

![image](https://github.com/bridge-core/editor/assets/110285018/16fd7f4e-c271-4e18-af2d-0c927e4e0911)

**Platform (please complete the following information):**

-   OS: Windows 10 22H2
-   App Version: 2.7.21

**Additional context**
Happens on multiple different Vanilla Packs, not just latest Stable

**Comment by SirenGlitch** [comment]
Same sort of thing as in #1097

**Comment by outercloudstudio** [comment]
This is one of the main things I want to fix for the next update.

**Comment by outercloudstudio** [comment]
This could be a bug with IDB Keyval. Have not been able to reproduce.
