### ISSUE TITLE
Error: RangeError: Maximum call stack size exceededError: RangeError: Maximum call stack size exceeded    at window.onunhandledrejection (https://editor.bridge-core.app/assets/main-f750b599.js:28:2506)

### ISSUE THREAD

**Issue by Ahmet532** [bridge-core/editor#1133]
**Summary**

**To Reproduce**

4. Observe result

**Observed behavior**
A clear and concise description of what happened
**Expected behavior**

**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

**Platform (please complete the following information):**

-   OS: [e.g. Windows 10]
-   App Version: [e.g. 0.13.3]

**Additional context**

**Comment by outercloudstudio** [comment]
Please fill out the requested information.
