### ISSUE TITLE
Error: Error: Failed to access "C:\Users\shiny\AppData\Local\com.bridge.dev\bridge\projects\The Infected.. \BP": Directory does not exist: path: C:\Users\shiny\AppData\Local\com.bridge.dev\bridge\projects\The Infected.. \BP: The system cannot find the path specified. (os error 3)Error: Error: Failed to access "C:\Users\shiny\AppData\Local\com.bridge.dev\bridge\projects\The Infected.. \BP": Directory does not exist: path: C:\Users\shiny\AppData\Local\com.bridge.dev\bridge\projects\The Infected.. \BP: The system cannot find the path specified. (os error 3)    at window.onunhandledrejection (https://tauri.localhost/assets/main-80e91abd.js:28:2506)

### ISSUE THREAD

**Issue by Dragonjr123** [bridge-core/editor#1140]
**Summary**

**To Reproduce**

4. Observe result

**Observed behavior**
A clear and concise description of what happened
**Expected behavior**

**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

**Platform (please complete the following information):**

-   OS: [e.g. Windows 10]
-   App Version: [e.g. 0.13.3]

**Additional context**

**Comment by outercloudstudio** [comment]
Please fill out the requested information.
