### ISSUE TITLE
Target Version Outdated

### ISSUE THREAD

**Issue by Litbolt123** [bridge-core/editor#1143]
**Summary**
The newest available target version is outdated and needs to be updated.
**To Reproduce**
Try and change target version to anything higher than 1.20.80

**Observed behavior**
You can't go higher than 1.20.80 when creating anything.
**Expected behavior**
Being able to change to a newer version to create with like 1.21.1 

**Screenshots / File Attachments**
None

**Platform (please complete the following information):**

-   OS: Windows 11
-   App Version: v2.7.23

**Comment by outercloudstudio** [comment]
Could you provide a screenshot?

**Comment by Litbolt123** [comment]
<img width="636" alt="Bridge Bug No 1" src="https://github.com/bridge-core/editor/assets/95593747/77324558-20fa-4fe2-8aba-92559825a5dd">

**Comment by Litbolt123** [comment]
That's what it says if I try to format anything higher than 1.20.80

**Comment by outercloudstudio** [comment]
Increase your target version in your project config.

**Comment by Litbolt123** [comment]
How do I change that in the config.json file?

**Comment by Litbolt123** [comment]
nvm, I think i changed it in notepad. Let me check though.

**Comment by Litbolt123** [comment]
Alright. I have changed it in the config.json file in my project. The problem has gotten better but still persists. I can change the version to 1.21.0 now but not any higher. Is that supposed to be like that?

**Comment by outercloudstudio** [comment]
You can change it to a higher version, bridge is just letting you know that there is nothing different than with the higher autocompletion. It's a bit confusing I know and it's something I want to change, but it's not a priority right now.

**Comment by Litbolt123** [comment]
Ok, here are two more screenshots too, thanks for your help :)

**Comment by Litbolt123** [comment]
<img width="561" alt="Bridge Bug No 2" src="https://github.com/bridge-core/editor/assets/95593747/bd16ab92-bba2-442e-a2a4-8332dc83b905">
<img width="632" alt="Bridge Bug No 3" src="https://github.com/bridge-core/editor/assets/95593747/20169982-3ee3-4d22-bfb1-e5911497b8ff">

**Comment by Litbolt123** [comment]
Yah, you can close this bug report. You can change the target version in the Create Project menu. Really sorry about that, I was confused, my bad.

**Comment by Litbolt123** [comment]
<img width="893" alt="Bridge Bug (fixed) No 4" src="https://github.com/bridge-core/editor/assets/95593747/c5d6877d-c4c7-43f9-9275-b4c7dd699a46">
