### ISSUE TITLE
Block not existing.

### ISSUE THREAD

**Issue by dogbytes00** [bridge-core/editor#1164]
**Summary**
Whenever I attempt to make a custom geometry block it just doesn't exist in game.

**To Reproduce**

1. Go to More (three dots)
2. Click on New File
3. Scroll down to Custom Geometry Block
4. Fill out everything with the correct files
5. Go in game
6. Not there

**Observed behavior**
Just a invisible block with a default selection box
**Expected behavior**
I expected a block to be there.

**Screenshots / File Attachments**
![bug_report1](https://github.com/user-attachments/assets/189cf83f-4597-43bd-b977-77b143dbdb2a)
Sorry could only give that one there's others but I couldn't figure out how to take pictures of them or upload.

**Platform (please complete the following information):**

-   OS: Windows 10
-   App Version: 2.7.29

**Additional context**
I have attempted to troubleshoot everything and nothing has fixed this problem.

**Comment by outercloudstudio** [comment]
If you have an issue with addons specifically, you should join our discord server and ask in the addon help section.
