### ISSUE TITLE
How  change /header/min_engine_version in mcpack?

### ISSUE THREAD

**Issue by Vasonch** [bridge-core/editor#1171]
How can this be changed? I have a file but I do not know how to edit it
![photo_5287685219547212049_y](https://github.com/user-attachments/assets/7536fa96-4ad2-4a7e-8f71-a77f9f015839)

[Vasonch's Pack [MConverter.eu].zip](https://github.com/user-attachments/files/16459603/Vasonch.s.Pack.MConverter.eu.zip)
(converted mcpack to zip)

**Comment by SpaceDummy** [comment]
It's in the manifest.json
