### ISSUE TITLE
/log command which automatically gets removed on production builds

### ISSUE THREAD

**Issue by solvedDev** [bridge-core/editor#146]

**Comment by rebrainertv** [comment]
I can add this to my custom commands extension if you want. With the new `compilerMode` feature, this is quite easy as a custom command.

**Comment by solvedDev** [comment]
Would be nice; feel free to close the issue once you're done :)

**Comment by rebrainertv** [comment]
Added to https://github.com/bridge-core/plugins/tree/master/plugins/CustomCommandToolbox
