### ISSUE TITLE
Find In Folder

### ISSUE THREAD

**Issue by solvedDev** [bridge-core/editor#152]
- [x] Support include/exclude in findAndReplace tab
- [x] Removed unused import https://github.com/bridge-core/editor/blob/dev/src/components/FindAndReplace/Tab.ts#L13
- [x] Search in folder in folder right click context menu https://discord.com/channels/602097536404160523/639751619352854530/904459440139403305

**Comment by Joelant05** [comment]
https://github.com/bridge-core/editor/commit/f91e90ec5591e7468a3fb7351642b5ae77cfe4bf
