### ISSUE TITLE
Nightly build: bridge. fails to compile

### ISSUE THREAD

**Issue by solvedDev** [bridge-core/editor#173]
```
TypeError: Failed to execute 'write' on 'FileSystemWritableFileStream':
failed to read the 'type' property from 'WriteParams':
Required member is undefined.
(at window.onunhandledrejection(https://nightly.bridge-core.app/assets/main.74680756.js:1:29240))
```

https://discord.com/channels/602097536404160523/813403646376411146/896733688610574346

**Comment by solvedDev** [comment]
This could have to do with virtual files and therefore something we fixed with our new compiler.

**Comment by Tschipp** [comment]
Is the new compiler already out for testing?

**Comment by Joelant05** [comment]
It is currently available on the nightly build

**Comment by solvedDev** [comment]
Closing because I didn't experience the issue anymore
