### ISSUE TITLE
Option to open existing addon already in com.Mojang folders

### ISSUE THREAD

**Issue by Ultr4Anubis** [bridge-core/editor#181]
**Summary**
At the moment, the only way to import an already existing addon is through uploading it to Bridge.V1 and exporting it as a Bridge. project format which you import into Bridge.V2. However, this can be extremely time-consuming if you have got the original Bridge version installed especially if you are working on a time limit.

This would simply be a new button on the file tab that says something along these lines: `Import addon` which takes you straight to the development folders, allowing you to select your addon. It would also accept `.mcaddon` files and `.mcpack` files.

**Alternatives/Considerations**
If this is 100% off the table, then maybe an online tool that will convert any addon to a bridge project file ready for importing into Bridge.V2

**Comment by solvedDev** [comment]
v2.3 will also allow users to load projects from the com.mojang folder: a5ae29ddd2b160dc00d545916fec469b453be885
