### ISSUE TITLE
Dedicated UI to show compiler errors

### ISSUE THREAD

**Issue by solvedDev** [bridge-core/editor#182]

**Comment by jasonjgardner** [comment]
A UI for any kind of compiler output would be useful. I think a terminal-like component would be a good fit for logging or displaying compiler information.

**Comment by solvedDev** [comment]
Yeah, I'd imagine this would be part of the general "compiler" window. I think it's possible to design something neat around it that's close to a terminal/browser console. Generally, this is a very much needed change because it's weird that an average user has to open the browser console

**Comment by solvedDev** [comment]
Initial implementation is available now. Things left to do:
- [ ] Create console instances for each separate project
- [ ] Clear console button
- [ ] Indicator inside of sidebar when an error occurred
- [ ] Make CompilerWindow part of App.windows to keep the window and its state alive
