### ISSUE TITLE
BlockRotationV2 plugin prevents successful compile

### ISSUE THREAD

**Issue by Chikorita-Lover** [bridge-core/editor#204]
**Summary**
When BlockRotationV2's `bridge:rotate_on_place` component is used (untested with other components) in a block behavior file, bridge. fails to compile with the following error:
```
Error: Failed to access "BP/blocks/399c4e8a-54e2-4e4e-92ac-bfb11ac7a3c1": Directory does not exist (at window.onunhandledrejection (https://editor.bridge-core.app/assets/main.48555c7a.js:1:29240))
```

**To Reproduce**
1. Download BlockRotationV2 plugin
2. Open a block behavior file
3. Add `bridge:rotate_on_place`
4. Save and close
5. Compile project
6. Observe results

**Platform:**
 - OS: Windows 10, Microsoft Edge
 - App Version: 2.1.5

**Comment by solvedDev** [comment]
I believe this issue should be fixed with our new compiler. Please feel free to reopen it if you find that to not be the case!
