### ISSUE TITLE
Various auto-completions do not support custom items/blocks

### ISSUE THREAD

**Issue by Chikorita-Lover** [bridge-core/editor#211]
When editing various files in bridge., including recipes or loot tables, auto-completions do not show identifiers for custom items or blocks for applicable values, such as `item` in recipes. Additionally, forcing said identifier will prevent auto-completions from working at all within the file.

**Comment by Joelant05** [comment]
https://github.com/bridge-core/editor-packages/commit/fe02db48116978a6e06d15de89aa5341ac8281ef
