### ISSUE TITLE
.bbmodel import not importing geometry correctly

### ISSUE THREAD

**Issue by RealJoshMC** [bridge-core/editor#225]
**Summary**

i open my bbmodel on bridge v2 and after i get all files (model and texture) the model turn to 1px cube.

My model -
![eye](https://user-images.githubusercontent.com/87614711/140963590-e550434d-dd65-4031-ad09-0ae1e4c9bf34.png)

**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

![Screenshot_20211110_000743](https://user-images.githubusercontent.com/87614711/140961690-646a8973-0078-4aa2-b9b8-346585a9ef84.png)

**Platform (please complete the following information):**
 - OS: Android 7
 - App Version: bridge v2.1.5

**Additional context**

**Comment by solvedDev** [comment]
@RealJoshMC Could you share your .bbmodel file so we can take a look at the issue?

**Comment by solvedDev** [comment]
@RealJoshMC Feel free to reopen once you have shared a way for us to reproduce the issue
