### ISSUE TITLE
Potential security issue in DataLoader

### ISSUE THREAD

**Issue by jasonjgardner** [bridge-core/editor#228]
#### Summary
[DataLoader.loadData method fetches `packages.zip` from a variable base URL](https://github.com/bridge-core/editor/blob/5aeeb1217dc1fb3d58f251dbc1c4ccb30c24f208/src/components/Data/DataLoader.ts#L24) and [decompresses the download without restrictions](https://github.com/bridge-core/editor/blob/5aeeb1217dc1fb3d58f251dbc1c4ccb30c24f208/src/components/Data/DataLoader.ts#L53).

A maximum number of files and/or maximum file size should be used in the unzipping process to avoid decompressing malicious archives (zip bombs). A zip bomb could be inserted through a malicious commit, hosted on a bad actor's bridge. redistribution, through DNS tampering, or who-knows-what.

#### To Reproduce
Replace `public/packages.zip` with a [zip bomb](https://github.com/damianrusinek/zip-bomb) to crash bridge.

#### Possible Solution
Add some kind of limitations to unzipping process. For example, limiting the number of files that can be unzipped:
![DataLoader rewrite screenshot](https://user-images.githubusercontent.com/1903667/141166406-048ffcee-1c13-4f95-bf02-60f9c540c64f.png)

**Comment by solvedDev** [comment]
I think we‘ll end up automatically committing the exact package size & the amount of files to this repository so we can check for that. Thank‘s for the report!
