### ISSUE TITLE
Generate short names for auto-completions

### ISSUE THREAD

**Issue by Joelant05** [bridge-core/editor#229]
https://discord.com/channels/602097536404160523/717701089805205504/908102651907014696

- [x] Animation (controller)
- Suggest short names from end of animation ids
- [x] Entity texture
- Suggest short names based on file names in "RP/textures/entity"

**Comment by solvedDev** [comment]
Should probably do the same for render controllers (and entity textures?)

**Comment by Joelant05** [comment]
The animation (controller) short names aren't working yet though because `getCacheDataFor()` seems to be broken.
@solvedDev is this just something that broke with the dynamic pack paths that hasn't been fixed yet?

**Comment by solvedDev** [comment]
The cache stuff should be working correctly already. Can you open a new issue to track the `getCacheDataFor` problem

**Comment by Joelant05** [comment]
https://github.com/bridge-core/editor/issues/230
