### ISSUE TITLE
Schema scripts: getCacheDataFor not working

### ISSUE THREAD

**Issue by Joelant05** [bridge-core/editor#230]
See https://github.com/bridge-core/editor-packages/blob/main/packages/minecraftBedrock/schemaScript/animationController/shortName.json and no properties show here https://github.com/bridge-core/editor-packages/blob/ca72f7fab3c1f09c9c8ed90d3408184b9b176937/packages/minecraftBedrock/schema/clientEntity/v1.10.0/main.json#L105

**Comment by solvedDev** [comment]
The issue was actually caused by referencing `animation`/`animationController` instead of `clientAnimation`/`clientAnimationController` :)
