### ISSUE TITLE
Extensions: Update "contributeFiles" to support pack paths

### ISSUE THREAD

**Issue by solvedDev** [bridge-core/editor#239]
Towards #50 

A syntax like this could probably work:
```json
{
  "contributeFiles": {
    "components/item/myComponent.js": {
      "pack": "behaviorPack",
      "path": "components/item/myComponent.js"
    }
  }
}
```

**Comment by Joelant05** [comment]
We will need to update all extensions that use "contributeFiles"/"install" to use the new format so I am leaving the issue open so we remember to do this once v2.2.0 is releases.

**Comment by Joelant05** [comment]
https://github.com/bridge-core/plugins/pull/92
