### ISSUE TITLE
Apply for the OpenAI  Codex API to integrate for extensions

### ISSUE THREAD

**Issue by DerrtyWizard** [bridge-core/editor#240]
adding the codex API would allow beginner coders to learn more about what they're doing and help them produce code with fewer bugs and errors. JS is supported by the codex api

**Comment by solvedDev** [comment]
I like the idea (it would certainly be worth exploring) but the waitlist for OpenAI Codex is currently closed.

**Comment by DerrtyWizard** [comment]
I believe OpenAI allowed access to the gpt-3 system yesterday?

**Comment by solvedDev** [comment]
I've just checked out whether we can join the waitlist and this is currently not the case :/

**Comment by solvedDev** [comment]
Closing the issue for now. Thanks for the suggestion 👏
