### ISSUE TITLE
Missing Auto-Completions for minecraft:biome_filter in Feature Rules

### ISSUE THREAD

**Issue by BeeTeeKay64** [bridge-core/editor#242]
**Summary**
I've just started getting into bridge. v2 again and while I was creating a Feature Rule in the Tree Editor, there were no auto-completions for the biome_pass component.

**To Reproduce**
1. Create a blank Feature Rule
2. Under "conditions", click on "minecraft:biome_filter"
3. Observe results.

**Observed behavior**
No auto-completions were showing in the "add object" or "add value" bar.
**Expected behavior**
Auto-completions were showing in the "add object" or "add value" bar.
**Screenshots / File Attachments**
![no_biome_filter_auto_completion](https://user-images.githubusercontent.com/76896809/142787908-b5961a5e-e145-4b19-bad4-21e6aa17cb69.PNG)

**Platform:**
 - OS: Windows 10
 - App Version: v2.1.5

**Comment by solvedDev** [comment]
Thanks for the report; we’ll take a look at the issue :)
