### ISSUE TITLE
Infinite 'Indexing packs' waiting time.

### ISSUE THREAD

**Issue by FrederoxGit** [bridge-core/editor#245]
**Summary**
When I launch bridge, and allow it access to my files, it gets stuck 'indexing packs' and nothing loads in the sidebar. There is also an error which i have attached below

This happens continuously even after restarting the program.

**To Reproduce**
1. Load bridge
2. Observe results

**Observed behavior**
Bridge gets stuck on indexing pack
**Expected behavior**
Bridge should not get stuck on indexing packs

**Screenshots / File Attachments**
[stuck-indexing-packs-error.txt](https://github.com/bridge-core/editor/files/7597231/stuck-indexing-packs.txt)

**Platform (please complete the following information):**
 - OS: Windows 10
 - App Version: v2.1.5

**Additional context**
n/a

**Comment by FrederoxGit** [comment]
I have been able to fix this issue by deleting a few files from the .bridge folder as well as the data folder

**Comment by solvedDev** [comment]
Is the attached error message the complete one or did you maybe see more inside of the console. On a first look this appears to be connected to one of our app settings
