### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by IDontWantToSignUp69** [bridge-core/editor#25]
Can not click off Join Discord

1. Go to Bridge v2
2. Click on the discord icon

**Observed behavior**
Clicking on the X or the LATER buton wont close the window

**Expected behavior**
close the window

**Platform (please complete the following information):**
 - OS: Windows 10
 - App Version: alpha 18

**Comment by solvedDev** [comment]
Thanks for the report! We'll have a fix for the issue out in the next alpha
