### ISSUE TITLE
Invalid syntax when defining face textures

### ISSUE THREAD

**Issue by Ultr4Anubis** [bridge-core/editor#252]
**Summary**
When using the `"minecraft:material_instances"` block component to set each face uv texture, it throws an invalid value warning. Image provided. The syntax is correct, however Bridge. V2 seems to be missing this schema.
![image](https://user-images.githubusercontent.com/79581868/144341672-3c5c3347-1751-451b-b48c-6109fbc5940e.png)

Here is the warning message Bridge throws
![bridge v2 - Builders Blocks - bridge  v2 02_12_2021 01_38_24](https://user-images.githubusercontent.com/79581868/144341837-3b7459d9-c5a9-4b3f-bf31-b111767be50a.png)

**Comment by Joelant05** [comment]
https://github.com/bridge-core/editor-packages/commit/06bf03d3a103cf0701138e353333366313cd6574
