### ISSUE TITLE
New folder option

### ISSUE THREAD

**Issue by Ultr4Anubis** [bridge-core/editor#255]
**Summary**
An option when right clicking to add a new folder similar to the new file one. There is currently no way to make a new folder without going into the project folder

**Comment by solvedDev** [comment]
We already have the option to create a new folder :)

![Bildschirmfoto 2021-12-04 um 13 03 51](https://user-images.githubusercontent.com/33347616/144708716-440f91c7-4bb4-4fb2-a385-a258e28bc90b.png)

**Comment by Ultr4Anubis** [comment]
> 

This only works when right clicking on an already existing folder, which then creates the folder inside the existing folder. If you have no folders, you can only add a folder by adding one in the project folder in file explorer
