### ISSUE TITLE
Option to give more space to tab system

### ISSUE THREAD

**Issue by RhettAtlas** [bridge-core/editor#260]
**Summary**

Sometimes it's pretty hard to read large/long functions in the editor, this messes with my own workflow, causing me to use alternative text editors.

**Alternatives/Considerations**

One idea is to make it so the user can make the tree folder layout on the left side of the screen smaller, by dragging the bounding box that is touching the text area.

The second idea is to make it so the user can make the text area its own window.

**Additional context/Motivation**

![image](https://user-images.githubusercontent.com/95271090/144928587-2f520b5a-fac9-44e4-8b2a-6175dff2cd07.png)

**Comment by solvedDev** [comment]
Hey 👋 
Did you notice that we have a setting to change the sidebar size? You can also enable text wrapping and configure when bridge. should start wrapping lines.

**Comment by solvedDev** [comment]
@RhettAtlas Ping because we need a reply to correctly categorize the issue :)

**Comment by RhettAtlas** [comment]
@solvedDev 
Sorry solved, I actually didn't notice this setting, but now that I know about it, i'm using it haha.
I would say this solved my issue.

**Comment by solvedDev** [comment]
Thanks for the info! :)
