### ISSUE TITLE
[Feature] Colour Preview

### ISSUE THREAD

**Issue by Ultr4Anubis** [bridge-core/editor#267]
**Summary**
It would be cool if there was a colour preview for HEX values similar to the one found on the Blockception VSCode plugin. It would be extremely useful to help minimize time but allowing quick edits rather than having to load up a new website.

**Comment by Joelant05** [comment]
This is certainly something we want to add.
I'll close this issue in favor of https://github.com/bridge-core/editor/issues/114 where you can track progress on the feature.
