### ISSUE TITLE
Geometry not found?

### ISSUE THREAD

**Issue by DatDopeBro** [bridge-core/editor#278]
**Summary**
Bedrock models would not show up in game, despite resource and behaviors set up perfectly.

**To Reproduce**
1. Import addon to Minecraft Bedrock and apply it in a new world.

**Observed behavior**
Content log informs that the geometry is not found, custom entity appear without model nor texture.
**Expected behavior**
Geometry to be found, model to be seen.
![Screenshot 2022-01-01 123701](https://user-images.githubusercontent.com/12470479/147850087-9b73f6d5-0c35-428a-936b-832402ca6d50.jpg)

**Screenshots / File Attachments**
[CriminalsAddon.zip](https://github.com/bridge-core/editor/files/7797633/CriminalsAddon.zip)

**Platform (please complete the following information):**
 - Windows 10, version 21H2
 - App Version: v2.1.5

**Comment by solvedDev** [comment]
This doesn't appear to be a bridge. bug
