### ISSUE TITLE
bridge wont output anything when compiling

### ISSUE THREAD

**Issue by cole00cole00** [bridge-core/editor#279]
**Summary**
When I click compile recently - it shows compiling icon but no files are output. If I restart he dev server - it will then output in the compiling combined with that action, but still compile button wont work again after. This was not always the case

**To Reproduce**
1. Open a project
2. Clear any previous compiled files
3. click compile button and then default
4. check output directory

**Observed behavior**
Bridge appears to compile but out put no files.
**Expected behavior**
Files all compiled and output just as they do when running the dev sever resart function.

**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

**Platform (please complete the following information):**
 - OS: windows 7
 - App Version: bridge v2

**Additional context**
The compile used to work just fine then stopped. I had i manually created the com.mojang directory on my computer as minecraft isnt installed on it, i use ftp to move the files to the appropriate directory on my phone which i test and play on. Restarting the dev server each time sucessfully compiles files which then work as expected.

**Comment by solvedDev** [comment]
We believe that we've already fixed this issue with our new compiler that will release with v2.2.0. I am therefore closing this issue but please reopen it if you find that your issue is not resolved with the next update

**Comment by cole00cole00** [comment]
this bug has started up again - the compile when restarting dev server works but otherwise nothing is output.

**Comment by cole00cole00** [comment]
sorry i dont know how to reopen it
