### ISSUE TITLE
Some "Add object" in the component of any items,block, etc. dosen't show up [BUG]

### ISSUE THREAD

**Issue by jackselhpdepr50** [bridge-core/editor#282]
**Summary**
Some of the "add object" in the items, blocks and other thing dosen't work, some opcion don't show up.

**To Reproduce**
1. Go to items
2. Click on the items you chose
3. Click on the component
4. Try to and an object to that component

**Observed behavior**
Its only show some of the components, not all of them.
**Expected behavior**
I expected that the show all the component, for example I try to create a Sword/battle axe but when I try to look for minecraft:weapon it doesn't show up 

**Screenshots / File Attachments**
![image](https://user-images.githubusercontent.com/97059323/147974039-8d9d2442-696a-428c-afc4-f7d6c4d6e278.png)

**Platform (please complete the following information):**
 - OS: Windows 10
 - App Version: v2.1.5

**Additional context**
I try everything but I just not get any answer.

**Comment by Joelant05** [comment]
This is because that component, along with many others require a format version of 1.16.100+ and "holidayCreatorFeatures" enabled in your project config
