### ISSUE TITLE
child 'events' not valid here

### ISSUE THREAD

**Issue by jackselhpdepr50** [bridge-core/editor#285]
**Summary**
Minecraft in the creator log told me this : [item][error]- events | child 'events' not valid here 
**To Reproduce**
1. Go to 'minecraft:item'
2. Click on 'events' in the add object
3. Add a event.
4. Then try to use in Minecraft

**Observed behavior**
The event doesn't ejecute like supposed to.
**Expected behavior**
The event ejecute when the user/player use the sword

**Screenshots / File Attachments**
![IMG_20220104_002546](https://user-images.githubusercontent.com/97059323/148018103-7bd7f428-3679-4d51-b1fd-2d689916c731.jpg)
![IMG_20220104_002630](https://user-images.githubusercontent.com/97059323/148018194-7299cabe-f5c8-4d5c-8c23-57711fc997a2.jpg)

**Platform (please complete the following information):**
 - OS: Window 10
 - App Version: 2.1.5

**Additional context**
In the early version i can create the events but i don't know if I can anymore

**Comment by solvedDev** [comment]
This is not a bridge. bug. Make sure that your item is using the correct format version (1.16.100+) and activate experimental gameplay inside of your world.
