### ISSUE TITLE
animation controllers not allowed

### ISSUE THREAD

**Issue by AshBrd** [bridge-core/editor#286]
**Summary**
You cannot use "animation_controllers" period. It says that it is not allowed in the editor, and it causes an error with the entity which causes it to be invisible alongside it's spawn egg.

**To Reproduce**
Simply have any mob have any animation controllers. Nothing is allowed to have animations.

**Observed behavior**
I got an error every time I had animation controllers in my entity's json file.
**Expected behavior**
I would expect to be allowed to input my animations for my entity.

**Platform (please complete the following information):**
 - OS: [e.g. Windows 10]

**Comment by solvedDev** [comment]
I assume you're talking about client entity files? This is not a bridge. bug; you're most likely not using the correct format version for the syntax you're using. If you want to use the "animation_controllers" object, you need to use v1.8.0. For v1.10.0, you register animation controllers inside of the "animations" object
