### ISSUE TITLE
Fuzzy Search in Open File

### ISSUE THREAD

**Issue by DjakaTechnology** [bridge-core/editor#288]
**Summary**
Currently, the search function in CTRL + P is very simple, it only matches string.

It works fine on simple case:
![image](https://user-images.githubusercontent.com/19620593/148394325-0d1de72e-2fb8-4f87-b4f1-8bf56f63085d.png)

But if you had a long file name or other weird cases, usually IDE uses fuzzy search to handle it. This will enable us to search `player.json` as `plr` and it will show on top. Currently on bridge we don't do that so it show like this:
![image](https://user-images.githubusercontent.com/19620593/148394502-fe320d5c-08d4-4c88-a96e-3dfbe4195ead.png)

Compared to VSCode:
![image](https://user-images.githubusercontent.com/19620593/148394588-f728081b-a831-4482-bee0-8a3c2b419252.png)

**Alternatives/Considerations**
none

**Additional context/Motivation**
This will help us when working on bigger project so we can do filtering based on directory or other fuzzy stuff:
![image](https://user-images.githubusercontent.com/19620593/148394914-7499776f-8560-49f7-a40d-0002b42cae9b.png)

![image](https://user-images.githubusercontent.com/19620593/148394985-d6b4f3af-25a7-4055-af93-b6050956c1ef.png)

IDE that had this behaviour (but not limited to):
- Visual Studio Code
- Visual Studio
- All Intellij IDE

Reference: https://github.com/microsoft/vscode/blob/main/src/vs/base/common/fuzzyScorer.ts

**Comment by solvedDev** [comment]
Feature is scheduled for v2.2.4
