### ISSUE TITLE
Support for /damage command

### ISSUE THREAD

**Issue by solvedDev** [bridge-core/editor#291]
https://feedback.minecraft.net/hc/en-us/articles/4418784338829-Minecraft-Beta-1-18-10-26-Xbox-Windows-Android-#:~:text=Added%20a%20new%20%27/damage%27%20command%20to%20allow%20players%20to%20deal%20damage%20to%20entities

**Comment by Joelant05** [comment]
I'll move this to v2.2.0 milestone as I'll be able to add it tomorrow
