### ISSUE TITLE
Project contents being deleted

### ISSUE THREAD

**Issue by Joelant05** [bridge-core/editor#292]
https://discord.com/channels/602097536404160523/639751619352854530/929386507419152384

Just encountered a bug on the dev build where all files in a project's BP, RP, WT, SP folders are completely deleted, just leaving empty folders inside.
I seem to be able to reproduce this on other projects too with these steps:

1) Remove the project config from the project (this step happened to me automatically because of <https://github.com/bridge-core/editor/issues/207> but it seems to work by manually removing the config as well).

2) Launch bridge (dev build, but probably also happens on nightly) and make sure the project selected is the one with the removed config.

3) Add the config back to where it should be.

4) Refresh bridge (ctrl + r), allow file access and the files inside of the project are gone.

**Comment by Tschipp** [comment]
Can confirm this, happened to me as well while I was developing
