### ISSUE TITLE
Profile Compatibility

### ISSUE THREAD

**Issue by Eko-byte** [bridge-core/editor#296]
**Summary**
The ability for users to put in folders other than com.mojang as the folder bridge should send its files to per project.

**Alternatives/Considerations**
Users could define the name of the folder inside bridge project settings

**Additional context/Motivation**
This feature would be especially useful for users who use profile switchers who have their data stored in folders that are not named com.mojang, this would allow them to organize their creations and also use these apps. Particularly it works with FoxyNoTails Version Switcher but to an extent because it can only use a folder named com.mojang which limits the profiles feature entirely, another version switcher has been known to use packageData which bridge could not send its files to.

**Comment by solvedDev** [comment]
Connected to #350

**Comment by solvedDev** [comment]
The preview of v2.3 on our [nightly build](https://nightly.bridge-core.app/) now supports setting folders with arbitrary names as output folders
