### ISSUE TITLE
Make errors disappear with new compilation

### ISSUE THREAD

**Issue by Tschipp** [bridge-core/editor#298]
**Summary**
I'd like errors from older compilation runs to disappear when a new run is started. 

**Alternatives/Considerations**
As an alternative, a keybind to clear notifications would also be nice. 
Maybe Shift-Clicking notifications could also directly remove them without opening the dialog, as an idea.

**Additional context/Motivation**
My main gripe is just error notifications building up and having to be clicked away one at a time.

**Comment by solvedDev** [comment]
I am closing this in favor of #182, this issue tracks moving the current error notifications into a dedicated window
