### ISSUE TITLE
"The world you are trying to enter required your device support scripting"

### ISSUE THREAD

**Issue by jackselhpdepr50** [bridge-core/editor#299]
**Summary**
When i export my .mcaddon / mod to my phone or other devices, told me that I can't connect cuz my device doesn't support scripting. And i try everything and nothing work, i thought it was Minecraft but i downloaded other mod and work perfectly.

**To Reproduce**
1. Go to Minecraft and import the mod
2. Click on Add BP and add the BP same with the RP
3. Open the world
4. Observe result

**Observed behavior**
Can't open the world and a text come out "The world you are trying to enter required your device support scripting."
**Expected behavior**
The world open and run the mod as supposed to do

**Screenshots / File Attachments**
![Screenshot_20220110-151247_5c8300b655012b1930f2e0a7b81bf6a9](https://user-images.githubusercontent.com/97059323/148840369-6415d1f8-a58d-4650-9864-955e0a3a2fb1.jpg)
![Screenshot_20220110-151250_5c8300b655012b1930f2e0a7b81bf6a9](https://user-images.githubusercontent.com/97059323/148840392-db03a120-da61-4c1e-aa39-c1636684bc53.jpg)
![Screenshot_20220110-151338_5c8300b655012b1930f2e0a7b81bf6a9](https://user-images.githubusercontent.com/97059323/148840401-b65658bf-4abe-42bd-bbdc-fac8799c829a.jpg)

**Platform (please complete the following information):**
 - OS: Android 11 OnePlus Nord N10 5G
 - App Version: v2.1.5

**Additional context**
And even i tested on Minecraft Beta but that doesn't work too. Also i put the experimental on my world

**Comment by solvedDev** [comment]
This is because you have enabled scripting upon creating the project and thus works as expected.
