### ISSUE TITLE
for some reason i can only see the simple files in the preset thing i dont know if this is a bug or not if it is please fix it

### ISSUE THREAD

**Issue by Darklegend4800** [bridge-core/editor#303]
**Summary**
some of the preset are missing only simple files remain

**To Reproduce**
dont know how it happend

**Observed behavior**
A clear and concise description of what happened
it is just not there

**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

**Platform (please complete the following information):**
 - OS: [Windows 10]
 - App Version: [2.1.5]

**Additional context**

**Comment by solvedDev** [comment]
Most presets require a resource pack and a behavior pack. Since your project only contains a BP, you can only create files and presets which only require this single pack to work
