### ISSUE TITLE
Import file guessing broken

### ISSUE THREAD

**Issue by Joelant05** [bridge-core/editor#312]
When dragging a file over bridge to import and saving it to the project, the file guesser just guesses the "volumes" folder every time, no matter the file imported

**Comment by solvedDev** [comment]
Well... 🙃 

![Bildschirmfoto 2022-01-16 um 21 05 42](https://user-images.githubusercontent.com/33347616/149676096-43af5292-d293-4de5-968f-e7bce92de1e8.png)
