### ISSUE TITLE
Possibility to install an extension locally and globally

### ISSUE THREAD

**Issue by Tschipp** [bridge-core/editor#315]
**Summary**
Sometimes it is useful to be able to additionally install an extension locally, even if it is already globally installed. This is so that the whole team that's working on a project has the same extensions.

**Alternatives/Considerations**
Only alternative right now is uninstalling the global extension and reinstalling it locally.

**Comment by solvedDev** [comment]
Turns out this is a duplicate of #56

**Comment by Tschipp** [comment]
Oh wow 🤦 Even made by me lol
