### ISSUE TITLE
Movable files

### ISSUE THREAD

**Issue by RealJoshMC** [bridge-core/editor#319]
Able to select files in project and move it to other folders

**Comment by solvedDev** [comment]
This is already possible with bridge. on desktop computers (via drag and drop). We've purposefully disabled this feature because drag & drop obviously doesn't work very well on touch devices. We will have to look into a mobile control alternative

**Comment by solvedDev** [comment]
With bridge. v2.3, it's now possible to copy & paste files and folders on mobile
