### ISSUE TITLE
Blank file

### ISSUE THREAD

**Issue by Ultr4Anubis** [bridge-core/editor#321]
**Summary**
Currently, the only way to add a new file to your project is by creating one through a pre-set. However, this means in order to create a file, such as `blocks.json` when you didn't select the file before starting, you have to make a file from a pre-set, then rename the file and then delete its content and start editing.

This is a long way just to add a blank file.

**Comment by solvedDev** [comment]
This already works by right clicking folders. I am keeping this issue open regardless to track creating global files

**Comment by Ultr4Anubis** [comment]
> 

Yes, but this puts the file inside the folder you right clicked on.
