### ISSUE TITLE
Custom Font

### ISSUE THREAD

**Issue by Ultr4Anubis** [bridge-core/editor#326]
Introduce the ability to add custom fonts. At the moment, there is only a select few you can choose from and it would be cooler for people to add that personal touch if they could choose any font they want

**Comment by solvedDev** [comment]
This is technically not possible at the moment, keeping the issue open to track the request regardless

**Comment by Ultr4Anubis** [comment]
Would not be possible to implement a feature like how BlockBench allows users to customise the font?

**Comment by solvedDev** [comment]
Blockbench is an Electron app (not sure whether their web app also supports it). There are ways for us to implement arbitrary font changing as well but it wouldn't be a seamless experience.
This API would enable the experience we're looking for but it's not ready just yet: https://bugs.chromium.org/p/chromium/issues/detail?id=535764

**Comment by Ultr4Anubis** [comment]
Their webapp allows custom fonts aswell.

It relies on the user having the font they want to use installed

**Comment by solvedDev** [comment]
The local font access API just shipped in chromium browsers so we are taking a look at implementing a better font selection control
