### ISSUE TITLE
Failing to recognize when to add a value with bridge. predictions

### ISSUE THREAD

**Issue by Chikorita-Lover** [bridge-core/editor#327]
**Summary**
When typing a value to add to the selected object/array with bridge. predictions, the value will be added as an object unless the value is selected from the auto-completions dropdown. Manually typing the wanted value and pressing enter will add an object instead, even if the value is present as such in auto-completions. Manually typing the wanted value then pressing "force value" adds it as an object as well.

**To Reproduce**

1. Select an object or array to add a value to
2. Type the value in the "add" field
3. Press enter (if value is in auto-completions) or "force value"
4. Observe result

**Observed behavior**
The value is added as an object rather than as a value.
**Expected behavior**
The value should be added as a value, even if enter is pressed (while value is present in auto-completions) or if "force value" is selected.

**Platform (please complete the following information):**

-   OS: Chrome OS
-   App Version: 2.2.1

**Additional context**
This issue occurs to other users, as seen throughout the bridge. Discord server.

**Comment by solvedDev** [comment]
It appears that this has been fixed for v2.2.2 already (at least it's not reproducible for me with this version). Please feel free to reopen the issue if it's not fixed for you once the update is available
