### ISSUE TITLE
[BUG] Downloading New Data Takes a Really Long Time

### ISSUE THREAD

**Issue by kyleplo** [bridge-core/editor#33]
**Summary**
I was really looking forward to this new generation of bridge, but it spent about 10 minutes on the "Downloading new data..." screen. My internet connection is fairly reasonable, I was able to download the package file directly from Github in about two seconds.

**To Reproduce**
1. Open bridge
2. Go through the configuration steps, giving permission for everything
3. Wait about 10 minutes

**Observed behavior**
It spends a long time on the "Downloading new data..." screen.
**Expected behavior**
The editor loads fairly quickly.

**Screenshots / File Attachments**
<img width="543" alt="Downloading new data..." src="https://user-images.githubusercontent.com/31634240/122105688-13e75800-cde7-11eb-9fb3-a8b76b99d424.png">

**Platform (please complete the following information):**
 - OS: MacOS Big Sur
 - Browser: Chrome 91
 - App Version: v2.0.0-rc.1

**Comment by solvedDev** [comment]
We are going to improve the data loading time after v2 officially releases. The speed is pretty slow because of how Windows implements the Native FileSystem API, it's lightning fast on MacOS.

**Comment by kyleplo** [comment]
I am on MacOS

**Comment by solvedDev** [comment]
That's interesting. Do you mind sharing your OS version & how long it takes for you?

**Comment by kyleplo** [comment]
I'm on MacOS Big Sur 11.2.3, Chrome 91.0.4472.106. It took about 10 minutes when I did it, I will run it again when I get home and time it.

**Comment by solvedDev** [comment]
Thanks!

**Comment by yichifauzi** [comment]
I have Same Issue too the Download new data takes so long

**Comment by yichifauzi** [comment]
Im on Windows 21H2 (os build 22000.71) Chrome 
92.0.4515.107

**Comment by solvedDev** [comment]
Closed by 624c08e3706c52f7dbfbc8203efdcad3287c1fa6; scheduled for the next update
