### ISSUE TITLE
entity invisible

### ISSUE THREAD

**Issue by Darkside3321** [bridge-core/editor#331]
hi i wanted to tell you that i have run into a very big problem,when it creates a custom blank entity up to the minute of the physical 
walking it is okay, then when i put the behavior like attack,scale,follow range, snap, the entity becomes invisible this makes me angry please answer me as soon  possible thanks very much

**Comment by solvedDev** [comment]
This is not a bridge. bug; you’ve likely made a mistake setting up/editing the entity. Feel free to use one of the entity related #addon-help channels on our Discord to discuss the issue further.

**Comment by Darkside3321** [comment]
i have checked more than once and i see that the entity has been  programmed well i am not sure it is a programm error but i double check it

**Comment by solvedDev** [comment]
It is **not** a bug in our app. It is a common beginner mistake: https://wiki.bedrock.dev/entities/troubleshooting-entities.html

**Comment by Darkside3321** [comment]
thanks very much

**Comment by solvedDev** [comment]
np
