### ISSUE TITLE
entity dieds when spawned

### ISSUE THREAD

**Issue by Darkside3321** [bridge-core/editor#334]
hello sorry if I disturb you but i don't know how report  this thing and i'm not so able to use bridge.
I wanted tell you although i don't know if it's a bug or i was wrong ,that when the entity spawn  it with the movement, behavior stroll, physics it goes well but then if i add scale, transformation,follow range,melee attack breathable ecc,  the entity is generated but dies
immediately can someone explain to me why? (i cannot use discord for family reason)

sorry for the ignorance

**Comment by solvedDev** [comment]
GitHub issues are not the right place for add-on help. If you cannot use Discord, you can check out the [community wiki](https://wiki.bedrock.dev/) or the [official Minecraft docs](https://docs.microsoft.com/en-us/minecraft/creator/).

**Comment by Darkside3321** [comment]
ok i didn't know it is the first time i sue
