### ISSUE TITLE
Further compatibility between bridge. predictions and auto-completions

### ISSUE THREAD

**Issue by Chikorita-Lover** [bridge-core/editor#335]
**Summary**
Further compatibility between bridge. predictions and auto-completions focuses on manually entering values instead of selecting "force value" or the auto-completion.

When a value is entered in the "add" field that is present in auto-completions as only a value, or when a value is added to an object that can only contain values (as defined in auto-completions), the value should be added as a value rather than as an object when pressing enter.

**Note**: "value" in this feature refers to strings, values, and booleans.

**Further considerations**
If this is added, a "force object" button may be considered for those who are trying to add an object present as a value in auto-completions.

**Additional context/Motivation**
The main motivation for this feature is the presence of bridge. predictions in the bridge. Discord server. bridge. predictions typically causes many issues for people, due to how values are entered.

**Comment by solvedDev** [comment]
This is supposed to work; I am therefore assigning the `bug` label

**Comment by solvedDev** [comment]
I cannot reproduce this; automatically adding values behaves as expected for me. Feel free to add more detail & to then reopen the issue
