### ISSUE TITLE
Bridge gets stuck compiling

### ISSUE THREAD

**Issue by BITroot-9000** [bridge-core/editor#338]
**Summary**
Bridge gets stuck compiling

**To Reproduce**

1. open bridge
2. open the project

**Observed behavior**
Bridge becomes stuck compiling, deleting the RP and some folders from their respective com.mojang folders, after a few seconds a seconds a console error appears. This makes it impossible to save files
**Expected behavior**
The project compiles after a while and i can resume working on things.

**Screenshots / File Attachments**
![image](https://user-images.githubusercontent.com/79287031/151281005-a6c698f6-2487-49f8-838e-dbe07ebdc0a6.png)
**Platform (please complete the following information):**

Windows 10

**Additional context**
I think this only happens with projects without a bridge folder  inside their BP, so i tried creating a new problem but a bridge file didnt generate and the compiler gets stuck.
this is the console error:
Service.f678946d.js:321 
DOMException: A requested file or directory could not be found at the time an operation was processed.

EDIT: I tried creating a bridge folder inside the BP of the project and now it supposedly compiles, and the console shows a message accordingly, but i cant find the files anywhere on com.mojang. This only happens when i manually click the compile button, the problem of the never ending compiling still happens when opening the app

**Comment by solvedDev** [comment]
You may need to "Restart the Dev Server" once to get bridge. to compiler your problems properly again (after an error)

**Comment by solvedDev** [comment]
Could you please provide a screenshot of all errors you're experiencing?

**Comment by solvedDev** [comment]
Closing because of missing information
