### ISSUE TITLE
Import project doesnt work

### ISSUE THREAD

**Issue by Ultr4Anubis** [bridge-core/editor#341]
When trying to import an `.mcaddon` as a project, It says that in unpacking a .zip and then when it finishes, the pack never gets added.

**Comment by Chikorita-Lover** [comment]
Have you refreshed (Ctrl + R / F5) bridge. since importing the project? I imported a MCADDON file yesterday and the project only appeared after refreshing. This is definitely a bug, don't get me wrong.

**Comment by Ultr4Anubis** [comment]
Doesnt work on the nightly build

**Comment by solvedDev** [comment]
We've fixed some issues with project imports as part of #412 and I cannot reproduce issues with `.mcaddon` imports. If you still have issues, please consider creating a minimal reproduction `.mcaddon` file and sharing that one with us :)
