### ISSUE TITLE
Feature Presets Broken

### ISSUE THREAD

**Issue by Zellturok** [bridge-core/editor#342]
**Summary**
There is an is a "Problem loading reference" after creating a feature file.

**To Reproduce**
Create a feature preset, hover over first brace bracket.

1. Go to 'New File'
2. Scroll down to and open 'Simple Files'
3. Create a file with any template
4. Go to the file and hover over the first brace bracket 
5. Observe result

**Observed behavior**
There is an error
**Expected behavior**
There should not be an error

**Screenshots / File Attachments**
![image](https://user-images.githubusercontent.com/62476099/151535653-9b463a36-f4f8-4a32-b717-a547ddab66b1.png)

**Platform (please complete the following information):**

- Edge AND Chrome
- V2.2.3

**Comment by solvedDev** [comment]
Thanks for the report. We'll take a look at it :)
