### ISSUE TITLE
An easier way to switch between tree editor and text 

### ISSUE THREAD

**Issue by KekeCreations** [bridge-core/editor#354]
**Summary**
If your making an add-on and like to copy and paste from stuff like snowstorm switching between tree editor and text editor is easy but can get quite annoying after a while. So this feature would make it easier to switch between the both 

**Alternatives/Considerations**
This could be done with a keyblind?
This could also be done with a button?

**Comment by outercloudstudio** [comment]
Alternatively a feature could be implemented where you can paste copied json into the tree editor

**Comment by KekeCreations** [comment]
yeah that would be nice

**Comment by solvedDev** [comment]
v2.3 comes with new file context menu actions: "Open With Tree Editor" and "Open With Text Editor" allowing you to open specific files with a different editor type than the one you've set within settings
