### ISSUE TITLE
v2.2.0

### ISSUE THREAD

**Issue by batlantern18** [bridge-core/editor#356]
When is v2.0.0, coming out?

**Comment by solvedDev** [comment]
GitHub issues are not the best place to ask questions but both v2.2.0 and v2.0.0 are already available. You can find the app here:
https://editor.bridge-core.app/

**Comment by batlantern18** [comment]
Oh... It was just that the [Website](https://bridge-core.app) said that it was v2.1.5.

**Comment by solvedDev** [comment]
Ah, we currently have an issue with the build script for the web page so it's been a couple of days since it updated ^^
