### ISSUE TITLE
Menu Bug

### ISSUE THREAD

**Issue by Nonplussedx101** [bridge-core/editor#360]
Hello, When im making a new file for Bridge the only option it shows is "Simple Files". But in the past there were may more options. Could you fix this please?

**Comment by Joelant05** [comment]
Are you able to share your project config? This seems like it should be happening and that you've just got them disabled in some way

**Comment by Nonplussedx101** [comment]
![image](https://user-images.githubusercontent.com/99291522/153674791-f9d69253-e4be-4789-a4b4-dcd7e75bf96d.png)
Here's the picture of my project config is there anything wrong?

**Comment by Joelant05** [comment]
Yeah, every preset out of simple files need a resource pack in the project
