### ISSUE TITLE
terrain_texture.json throws warnings for custom texture paths

### ISSUE THREAD

**Issue by Ultr4Anubis** [bridge-core/editor#363]
**Summary**
When defining a new texture in the `terrian_texture.json`, Bridge throws a warning if the texture path does not start with `textures/blocks/`.

**To Reproduce**

1. Open/create a new `terrain_texture.json`
2. Define a new texture and use a path that does not start with `textures/blocks`

**Observed behavior**
Bridge throws a warning saying the `Value is not accepted`
**Expected behavior**
There would be no warning

**Screenshots / File Attachments**
![image](https://user-images.githubusercontent.com/79581868/154167720-43c33ad6-447c-49f7-bfda-9ebcdd369763.png)
![image](https://user-images.githubusercontent.com/79581868/154167880-23fb1b3c-b379-4c93-9af7-80007684b4c9.png)

**Platform (please complete the following information):**
- Regular Bridge V2
- Nightly Build

**Comment by Joelant05** [comment]
https://github.com/bridge-core/editor-packages/commit/584074070f1b2e450ed8eddb17c7284b6c4d6f4c
