### ISSUE TITLE
sword effect bug

### ISSUE THREAD

**Issue by Elliottgamer432** [bridge-core/editor#368]
a weird bug but when you click on the sword effect it a a gramma error [shown by red arrow]
![Screenshot (21)](https://user-images.githubusercontent.com/88251887/154851761-2f7ede3e-1eb6-4381-8fc9-e5d7d304c933.png)
r

**Comment by solvedDev** [comment]
This looks like a preset added by an extension, can you confirm @Joelant05?

**Comment by Joelant05** [comment]
yep, looks like an extension preset
