### ISSUE TITLE
Support for non-JSON files in Custom Compiler Plugins

### ISSUE THREAD

**Issue by outercloudstudio** [bridge-core/editor#370]
**Summary**
This would allow for custom compiler plugins to tap into files that are not just JSON files.

**Alternatives/Considerations**
This might affect existing compiler plugins although it would be best to build in such a way that none are affected.

**Additional context/Motivation**
This would allow for more powerful custom compiler plugins.

**Comment by solvedDev** [comment]
We already support transforming all files (see e.g. custom .molang files)

**Comment by outercloudstudio** [comment]
Okay I will do more test, however I was not able to get them to be transformed. Do I need to include them?

**Comment by outercloudstudio** [comment]
I can't seem to get files that are non-json to be transformed. I looked at the molang builtin plugin but it uses `options.include` which is not documented so I have no idea how to use this.

**Comment by outercloudstudio** [comment]
Also, the normal include function does not seem to affect it even when it returns the correct files in an array.

**Comment by solvedDev** [comment]
By default, Dash fetches all files from your packs and calls the `transform` and `read` hook for every file.
**Important:** You must return something from the `read` hook ("read" the file), otherwise dash will skip further work and just copy the file over.

**Comment by outercloudstudio** [comment]
Ahhh thanks you. That’s what I was missing.
