### ISSUE TITLE
why dont make this to be a app? user electron?

### ISSUE THREAD

**Issue by H0nGzA1** [bridge-core/editor#372]
I think it would be better to make it a desktop application, using a web technology called Electron to build a cross-platform desktop application, rather than a website with your user system, like Postman? Users can log in to use more features。

**Comment by Chikorita-Lover** [comment]
I can't speak for the developers, but this was how bridge. v1 worked and was scrapped (if I recall) to work natively on users' already-installed browsers and have support for mobile.

**Comment by Gekocaretaker** [comment]
@H0nGzA1 As Chikorita-Lover had said, v1 worked like this. It was a mess. Wanted a new feature? Everything else breaks. Electron made bridge. be it's own browser practically, and it took a lot of space. As a PWA, it can be used online or offline, takes up a lot less space, and is much more easily updatable.
As for Postman, that would be practically useless, as Postman is a API site. bridge. is a lightweight IDE. And there is no need for there to be an account system, as that would mean that servers need to be added for the accounts to be hosted, and there would be no need for accounts. Making it where you need to log in to access features would not be good.
As this feature request is to make v2 run on Electron as v1, I recommend you use v1 then. I also am going to close this issue.

**Comment by H0nGzA1** [comment]
thx
