### ISSUE TITLE
Custom Smithing Table Recipe

### ISSUE THREAD

**Issue by githubgamer14** [bridge-core/editor#374]
**Please add the Smithing Table Recipe for bridge v1 and v2. It is working now because I saw this on mcpedl:** https://mcpedl.com/deathnerite-addon-1/

![deathnerite-smithing-table-update_3 (1)](https://user-images.githubusercontent.com/89930001/156477081-bae984e2-38dd-4483-beee-0e31d2162453.png)

**Comment by Joelant05** [comment]
bridge. v2 already supports smithing table recipes and I don't think it is worth a whole bridge. v1 update to support, as it is just a "smithing_table" tag on a shapeless recipe
