### ISSUE TITLE
ChromeOS Mojang Folder

### ISSUE THREAD

**Issue by awehage001** [bridge-core/editor#380]
**Summary**
Can't drag and drop com.mojang folder on chromebook
**To Reproduce**

**Platform (please complete the following information):**

-   ChromeOS

**Comment by solvedDev** [comment]
If this is not possible due to Chrome OS not allowing you to drag and drop the folder, there's nothing we can do on our end to fix it.
The drag and drop action is required because it's the only way we can get access to "restricted" folders.
