### ISSUE TITLE
Elytra Item Preset

### ISSUE THREAD

**Issue by xXDarkChaosXx** [bridge-core/editor#381]
**Summary**
An item preset, such as the blank item, but it is an elytra

**Alternatives/Considerations**
I don’t really thinks there would be many items that are similar to the elytra

**Additional context/Motivation**
I believe that this item would be good to base things off of such as changing animations, playing audio etc.

**Comment by Chikorita-Lover** [comment]
Elytra are not replicable with add-ons, so this is highly unlikely for the time being.

**Comment by solvedDev** [comment]
This is correct, we cannot create a preset for something Minecraft doesn't support yet.
