### ISSUE TITLE
The item_textures.json file was completely overwritten when creating custom armor

### ISSUE THREAD

**Issue by Mcjiprock** [bridge-core/editor#388]
**Summary**
The item_textures.json file was completely overwritten when creating a custom armor set using the new file menu in bridge v2.2.5.

**To Reproduce**

Make sure to have a item_textures.json with at least one item in it (I had 44 items)
1. Go to 'The "new file" tab'
2. Click on 'Armor'
3. Now here I am sure I disabled everything except for the helmet, but all armor pieces appeared in the item_textures.json. In the behaviorpack however only the helmet appeared as expected. In the texturepack only the default texture for the helmet appeared.
4. I have all compile options on default (automatic).
5. Then i noticed in game all textures on my items where gone and checked the file for the problem.

**Observed behavior**
The item_textures.json was completely overwritten. And was only showing the 4 armor pieces (helmet, chestplate, leggings, boots)
**Expected behavior**
All items are still in the item_textures.json file and only the helmet-armor-piece was added.

**Screenshots / File Attachments**
-

**Platform**

-   OS:  Windows 10
-   App Version: 2.2.5

**Additional context**
-

**Comment by solvedDev** [comment]
Maybe the file previously contained invalid JSON and bridge. therefore failed to load the old file contents. We should look into providing information to the user in such cases

**Comment by Mcjiprock** [comment]
For as far as I know the file has never been edited outside of bridge. And it was working completely fine beforehand. I created this project in bridge v2. The only "unusual thing ive done to it quite often is adding things like the model, and textures via the project file instead of the bridge editor.

**Comment by Mcjiprock** [comment]
> I can not reproduce the issue where the entire file is being overwritten, does this happen consistently for you on both the [main](https://editor.bridge-core.app/) build and [nightly](https://nightly.bridge-core.app/)?
> 
> > Now here I am sure I disabled everything except for the helmet, but all armor pieces appeared in the item_textures.json. In the behaviorpack however only the helmet appeared as expected. In the texturepack only the default texture for the helmet appeared.
> 
> I can confirm this is an issue and I'll get this fixed.

It has never happened before i have added 2 armor pieces in pretty much the same way before in that pack. I did however exit bridge pretty much right after adding the armor piece to go to sleep and found out about the problem the next day so maybe its related to exiting the program.
