### ISSUE TITLE
offline editor

### ISSUE THREAD

**Issue by ahmad12331233** [bridge-core/editor#393]
**Summary**
a way to use this powerfull editor offline

**Alternatives/Considerations**
modding on a web browser SUCKS and working for a loooong time on a web app with internet connection is expensive
AND no i cant use bridge v1 its outdated

**Additional context/Motivation**
just offline version (or just tell me that this is on the plans to do)

**Comment by Joelant05** [comment]
once you have installed the app it is useable offline, check out our [getting started guide](https://bridge-core.app/editor-docs/getting-started/#setting-up-bridge), it starts with how to install

**Comment by ahmad12331233** [comment]
> once you have installed the app it is useable offline, check out our [getting started guide](https://bridge-core.app/editor-docs/getting-started/#setting-up-bridge), it starts with how to install

well i use edge browser and everything is fine but after closing and reopening the app more than 5 times (offline) it just says a compiler error with some libraries missing so what to do??????

**Comment by ahmad12331233** [comment]
> once you have installed the app it is useable offline, check out our [getting started guide](https://bridge-core.app/editor-docs/getting-started/#setting-up-bridge), it starts with how to install
![Screenshot 2022-03-19 220718](https://user-images.githubusercontent.com/79656085/159136858-23362991-023c-42e6-aa5c-5f7cc041353c.png)
thanks it works fine but why all the textures are squares?? its just wierd is it a bug or its a browser imitation?

**Comment by ahmad12331233** [comment]
> once you have installed the app it is useable offline, check out our [getting started guide](https://bridge-core.app/editor-docs/getting-started/#setting-up-bridge), it starts with how to install
thanks it works fine but why all the textures are squares?? its just wierd is it a bug or its a browser imitation?.....
......a..aa..AAA......it just bugs me

![Screenshot 2022-03-19 220718](https://user-images.githubusercontent.com/79656085/159136858-23362991-023c-42e6-aa5c-5f7cc041353c.png)
