### ISSUE TITLE
Custom MoLang doesn't work

### ISSUE THREAD

**Issue by Tschipp** [bridge-core/editor#397]
**Summary**
Molang files' schema is bugged, and the parser for it also doesn't work

**To Reproduce**
Molang file:
```js
function("createList", {
    t.list.length = 0;
    return t.list;
});

function("listLength", "list", {
    return arg.list.length;
})

function("addFirst", "list", "element", {
    arg.list.length = arg.list.length + 1;
    t.newfirst.element = arg.element;
    t.newfirst.next = arg.list.first;
    arg.list.first = t.newfirst;
    return;
});

function("addLast", "list", "element", {
    t.curr = arg.list.first;
    loop(arg.list.length - 1, {
        t.curr = t.curr.next;
    });
    t.newele.element = arg.element;
    t.curr = t.newele;
    (!arg.list.first) ? arg.list.first = t.curr;
    return;
});

function("getElement", "list", "index", {
    t.curr = arg.list.first;
    t.ele = t.curr.element;
    loop(arg.index, {
        t.curr = t.curr.next;
        t.ele = t.curr.element;
    });
    return t.ele;
});
```

Animation Controller that uses it:
```json
{
	"format_version": "1.10.0",
	"animation_controllers": {
		"controller.animation.molang_test": {
			"initial_state": "default",
			"states": {
				"default": {
					"on_entry": [
						"v.list = f.createList();",
						"f.addLast(v.list, 1);",
						"f.addLast(v.list, 2);",
						"f.addLast(v.list, 3);",
						"f.addLast(v.list, 4);",
						"f.addLast(v.list, 5);",
						"v.idx = (v.idx ?? -1) + 1;",
						"v.switch = f.getElement(v.list, v.idx);"
					],
					"transitions": [
						{
							"5": "v.switch == 5"
						},
						{
							"1": "v.switch == 1"
						},
						{
							"2": "v.switch == 2"
						},
						{
							"3": "v.switch == 3"
						},
						{
							"4": "v.switch == 4"
						}
					]
				},
				"5": {
					"on_entry": [
						"/say 5"
					],
					"transitions": [
						{
							"default": "5"
						}
					]
				},
				"1": {
					"on_entry": [
						"/say 1"
					],
					"transitions": [
						{
							"default": "1"
						}
					]
				},
				"2": {
					"on_entry": [
						"/say 2"
					],
					"transitions": [
						{
							"default": "1"
						}
					]
				},
				"3": {
					"on_entry": [
						"/say 3"
					],
					"transitions": [
						{
							"default": "1"
						}
					]
				},
				"4": {
					"on_entry": [
						"/say 4"
					],
					"transitions": [
						{
							"default": "1"
						}
					]
				}
			}
		}
	}
}
```

**Observed behavior**
The syntax is marked as an error in bridge:
![image](https://user-images.githubusercontent.com/11649893/160881537-c8b6c2b4-d7bc-41c0-8ff2-6078374f94ad.png)

The parser can't parse the file, these errors are thrown:
![image](https://user-images.githubusercontent.com/11649893/160881734-208d7edd-8377-4f4d-b1ec-563e4b14b1bc.png)

In the output AC, the functions are also not replaced by the real code.

**Expected behavior**
None of these errors

**Screenshots / File Attachments**
As above

**Platform (please complete the following information):**

-   OS: [e.g. Windows 10]
-   App Version: [e.g. 2.2.5 (nightly)]

**Comment by solvedDev** [comment]
The problem appears to be that .molang file don't support using `""` for strings (matching inline MoLang statements). I am going to change that for the custom MoLang file parser

**Comment by Tschipp** [comment]
When replacing `"` with `'`, the file compiles and there are no errors in the console. However, the molang is still not replaced in the AC I listed above. For reference, this is my config.json:
```json
"compiler": {
        "plugins": [
	        "typeScript",
	        "entityIdentifierAlias",
	        "templater",
	        "preprocessor",
	        "customEntityComponents",
	        "customItemComponents",
	        "customBlockComponents",
	        "customEntitySyntax",
	        "customCommands",
	        "moLang",
	        [
		        "simpleRewrite",
		        {
			        "packName": "NatureConservancy"
		        }
	        ]
        ]
}
```

**Comment by Tschipp** [comment]
Update: I think part of the problem is that bridge's Molang processor converts all uppercase to lowercase. Since my functions were named with uppercase, they then were actually lowercase in the generated output. When I changed the function names to snake_case, this was (part of) the output for the animation controller:
```json
"default": {
	"on_entry": [
		"v.list=({t.__scvar0=0;t.__scvar1=t.__scvar2;}+t.__scvar1);",
		"f.add_last(v.list,1);",
		"f.add_last(v.list,2);",
		"f.add_last(v.list,3);",
		"f.add_last(v.list,4);",
		"f.add_last(v.list,5);",
		"v.idx=(v.idx??-1)+1;",
		"v.switch=f.get_element(v.list,v.idx);"
	],
	"transitions": [
		{
			"5": "v.switch==5"
		},
		{
			"1": "v.switch==1"
		},
		{
			"2": "v.switch==2"
		},
		{
			"3": "v.switch==3"
		},
		{
			"4": "v.switch==4"
		}
	]
}
```

**Comment by solvedDev** [comment]
You're missing a semicolon behind the `list_length` function. This stopped parsing the other functions within the custom molang file

**Comment by solvedDev** [comment]
Related commit: https://github.com/bridge-core/MoLang/commit/86d6f9146bbbc576442a9aa1b28fd16f01e3a13e

**Comment by Tschipp** [comment]
After I corrected the file:
<img width="277" alt="image" src="https://user-images.githubusercontent.com/11649893/161265109-74fe435f-d63b-4c2d-a5f8-d7a1092d123a.png">
🤔

**Comment by solvedDev** [comment]
Oh, yeah... Forgot to mention: Empty returns (`return;`) are not valid within MoLang. Maybe it makes sense to return the added element instead?

**Comment by solvedDev** [comment]
The next MoLang update will also enable you to just omit the return statement (implicitly returning 0)
