### ISSUE TITLE
[BUG] bridge. gets stuck loading after saving twice

### ISSUE THREAD

**Issue by dombomb64** [bridge-core/editor#40]
**Summary**
When I save the first time, I can still use the program. However, when I save a second time, whether that be on the same file or a different one, the loading box never goes away.

**To Reproduce**
1. Set up and open bridge.
2. Give bridge. the necessary permissions
3. Choose an addon to edit
4. Choose a file or files to edit
5. Save twice

**Observed behavior**
The program immediately locks up.
**Expected behavior**
The program closes the loading dialog once it finishes saving.

**Screenshots / File Attachments**
![Miscellaneous Features - bridge  v2 7_19_2021 2_45_47 PM](https://user-images.githubusercontent.com/49823019/126211188-b0bb2162-b984-4f3c-b994-0b95a2916c16.png)

**Platform:**
 - OS: Windows 10
 - App Version: v2.0.0

**Additional context**
I can't remember, but when I went to get the screenshot, I think it might have locked up on the first save. I had it open before, but I can't remember if I had saved before.

**Comment by solvedDev** [comment]
Does that happen consistently for you when you quickly save two times in a row? I am unable to reproduce the issue so far

**Comment by dombomb64** [comment]
I’ve found that it happened only on the project that I was struggling with in [Issue #39](https://github.com/bridge-core/editor/issues/39), but that’s since been fixed. Sorry that I thought it was a bug.
