### ISSUE TITLE
Suggesting Unobtainable Blocks In Recipes

### ISSUE THREAD

**Issue by outercloudstudio** [bridge-core/editor#402]
**Summary**
Bridge auto completions suggests unobtainable blocks in recipes.

**To Reproduce**
1. Create a recipe
2. For one of the ingredients begin typing cocoa

**Observed behavior**
Bridge suggests the block `minecraft:cocoa` which is unobtainable.
**Expected behavior**
Bridge should not suggest blocks or items for recipes that are completely unobtainable.

**Screenshots / File Attachments**
[Discord Message](https://discord.com/channels/602097536404160523/728393873260412979/959855147146686564)

![image](https://user-images.githubusercontent.com/60296487/161393539-178d04fa-7fd1-469c-bc77-f4fd03504a62.png)

**Platform (please complete the following information):**
-   OS: N \ A
-   App Version: 2.2.5

**Comment by Joelant05** [comment]
I don't think we need to change this, all identifiers are taken from the docs by a script and so if we manually remove identifiers, they will be added back every time an update is released with a new identifier. I also think it is good to have every identifier included for cases where they might be used by the user.
For the specific case you've screenshot, `minecraft:cocoa_beans` is also proposed so it shouldn't be a problem.

LMK if there is anything I've not thought about, thanks.
