### ISSUE TITLE
Toggle experimental features in project switcher

### ISSUE THREAD

**Issue by Chikorita-Lover** [bridge-core/editor#404]
**Summary**
Add the ability to toggle on/off experimental features of projects in the project switcher. This could either be done in the same window, or have a button open a new window for toggling experimental features.

**Motivation**
This would simplify toggling experimental features that were not enabled during project creation, and provide easier accessibility for users unfamiliar with the editor.

**Comment by solvedDev** [comment]
Thanks @pascal541! 🎉
