### ISSUE TITLE
Improved "save to project" window

### ISSUE THREAD

**Issue by Chikorita-Lover** [bridge-core/editor#406]
**Summary**
Currently when multiple files are opened and selected to save to the project, there are many windows piled on top of each other, and it is impossible to know which file you're selecting the file path for. Also, there are three to four windows involved in the process: selecting to save the project, setting the file path, setting the file name, and if you wish to overwrite. Showing all selected files in the same window and combining the file path and name processes would simplify the experience.

**Comment by solvedDev** [comment]
![Bildschirmfoto 2022-04-23 um 13 29 05](https://user-images.githubusercontent.com/33347616/164892570-d6c7e185-d312-4f7a-b467-412c58135fca.png)

This is what I am going to push out for now. I agree that mass importing of files could further be improved in the future though

**Comment by Chikorita-Lover** [comment]
Thank you, I'm glad you got around to merging the file path and name!
