### ISSUE TITLE
No block/item auto-completions when HCF is disabled in tree editor

### ISSUE THREAD

**Issue by KaboomBEAN** [bridge-core/editor#408]
**Summary**

**To Reproduce**

4. Observe result

**Observed behavior**
A clear and concise description of what happened
**Expected behavior**

**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

**Platform (please complete the following information):**

-   OS: [e.g. Windows 10]
-   App Version: [e.g. 0.13.3]
<img width="302" alt="Screenshot 2022-04-06 204759" src="https://user-images.githubusercontent.com/103158520/162103953-a0045268-6533-4c18-bdf6-fef3fb1a3d02.png">

**Additional context**

**Comment by ihategravel2** [comment]
All you did was leave the prefilled description and included a picture.  I'm pretty sure you just forgot to make the format version 1.16.100 or did not turn on holiday creator features upon project creation.

**Comment by Joelant05** [comment]
https://github.com/bridge-core/editor/commit/19c46bd506ef3bdbe8060e21920746d823687dab
