### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Glacerad** [bridge-core/editor#41]
**Summary**
my function files didn't carry any information whenever bringing them from bridge v1 to bridge v2

**To Reproduce**
1. upload files from v1 to v2

**Observed behavior**
A clear and concise description of what happened
**Expected behavior**

**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

**Platform (please complete the following information):**
 - OS: [e.g. Windows 10]
 - App Version: [e.g. 0.13.3]

**Additional context**

**Comment by Joelant05** [comment]
This will be fixed with bridge v1.8.1
