### ISSUE TITLE
Can we create java datapacks with this tool?

### ISSUE THREAD

**Issue by A-childs-encyclopedia** [bridge-core/editor#414]
If not, please suggest alternatives for java

**Comment by outercloudstudio** [comment]
At the moment bridge. does not support Java. The only tool I can recommend is using vscode.

**Comment by solvedDev** [comment]
We have started work on support for Java a while ago but the demand doesn't really justify us putting more work into it. Feel free to pick up our work by contributing this feature; that's the beauty of open-source tools! :)

**Comment by A-childs-encyclopedia** [comment]
ok
