### ISSUE TITLE
How to disable/remove script.

### ISSUE THREAD

**Issue by Fuufff** [bridge-core/editor#416]
**Summary**

**To Reproduce**

4. Observe result

**Observed behavior**
A clear and concise description of what happened
**Expected behavior**

**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

**Platform (please complete the following information):**

-   OS: [e.g. Windows 10]
-   App Version: [e.g. 0.13.3]

**Additional context**
Why there is a script because my phone can't do scripts

**Comment by Joelant05** [comment]
Could you fill in the bug report so we know what exactly you are reporting
