### ISSUE TITLE
Add browse com.mojang folder

### ISSUE THREAD

**Issue by mirkokral** [bridge-core/editor#419]
**Summary**
I have a problem on Chrome OS that I can't drag a folder to bridge v2, it will do nothing!
**Alternatives/Considerations**
Or fix the bug on Chrome OS where you can't drag a folder onto bridge v2

**Additional context/Motivation**
A browse button like that one on the bridge v2 folder

**Comment by solvedDev** [comment]
There's now (bridge. Nightly build/scheduled to release with v2.3) an "Open Folder" action within the app toolbar. After selecting a folder, you're prompted with multiple options: One of them allows you to set the folder as an output destination.
