### ISSUE TITLE
Unsupported Web Browser

### ISSUE THREAD

**Issue by Kobra299** [bridge-core/editor#421]
**Summary**

Basically as this does not support Firefox I can not use the newest version if possible could you compile it so that you can get a offline version to use as well

**Comment by solvedDev** [comment]
Firefox can run bridge. v2 just fine. The experience won't be as good as on Chrome or Edge but it works (™️). If you're on Windows, you might want to consider installing bridge. v2 using Edge as that comes pre-installed anyways.
