### ISSUE TITLE
Sometimes "\n" gets deleted when migrating addons

### ISSUE THREAD

**Issue by Laiffo** [bridge-core/editor#423]
**Summary**
\n gets removed together with the text behind it

**To Reproduce**

1. Make an new Project
2. Put all Addon files in there and make sure many items with \n are in it
3. Check them in the json. file

**Observed behavior**
When I migrated all my addons to Bridge v2 everything seemed fine, expect that a lot of item files that used \n worked too, yet the \n and the text behind it just got deleted.
**Expected behavior**
The \n text should still be there

**Platform (please complete the following information):**

-   OS: Windows 10
-   App Version: [e.g. 2.2.8]

**Comment by solvedDev** [comment]
Where did you put the newline characters? Inside of strings in JSON files? Lang files? Strings in mcfunction files?

**Comment by Laiffo** [comment]
I put it in Item.json files in "minecraft:display_name"

**Comment by solvedDev** [comment]
This might have been fixed by 92751f30fdc067bb87c427d2801bd7ae55e41161. Feel free to reopen if that‘s not the case
