### ISSUE TITLE
Incompatibility with Opera GX after a new update

### ISSUE THREAD

**Issue by whatwillweget** [bridge-core/editor#426]
**Summary**
Opera GX no longer works with bridge after updating to v.2.2.8

**To Reproduce**

1. Go to [bridge](https://editor.bridge-core.app) Version 2.2.7 using Opera GX Browser
2. Click the Update button

**Observed behavior**
When I was using bridge Version 2.2.7 everything seems fine, expect that the update was still usable, yet it was no longer usable.
**Expected behavior**
Bridge should still be usable after an update.

**Platform (please complete the following information):**

-   OS: Windows 10
-   Browser: Opera GX
-   App Version: 2.2.7 (w/o Issues) 2.2.8 (w/ Issues)

**Comment by Joelant05** [comment]
In what way does it "not work"? Does it not load?

**Comment by whatwillweget** [comment]
![image](https://user-images.githubusercontent.com/104620568/165985945-6ea6f2ae-afc6-43a9-96e5-7f357b7cacd9.png)
It does no longer work with directory support.

**Comment by Joelant05** [comment]
Ah, in 2.2.8 we enabled our file system API polyfill for every browser that isn't Edge or Chrome as no other browser supports the API fully. It does seem that Opera now supports this feature fully so we can enable it for Opera in the next update
