### ISSUE TITLE
crswap file copy

### ISSUE THREAD

**Issue by Laiffo** [bridge-core/editor#428]
**Summary**
Randomly created a .

json.crswap file

**To Reproduce**
(I am not sure if this always does it) But when I made a new file in the Recipe folder

**Observed behavior**
Creates a copy of a file of ".json.crswap"
**Expected behavior**
Only create the JSON file

**Platform (please complete the following information):**

-   OS: [e.g. Windows 10]
-   App Version: [e.g. 2.2.8]

![Screenshot (3661)](https://user-images.githubusercontent.com/87951487/166146031-f0d65769-a074-4984-ac25-4bef48ad0b53.png)

**Comment by solvedDev** [comment]
As far as we can tell at the moment, this is an issue that happens when you close the app while still saving some files. There's nothing we can do to fix the issue rn
