### ISSUE TITLE
My game keeps saying the version of my /header/min_engine_version is too high

### ISSUE THREAD

**Issue by IDKIGSU** [bridge-core/editor#430]
how do you set the header from 1.19.0 to 1.18.30

**Comment by Joelant05** [comment]
You can change the "min_engine_version" field in your manifest, and I recommend you change the "targetVersion" in your project config as well. To stop this in future projects, make sure you set your target version correctly on project creation.

**Comment by Vasonch** [comment]
@Joelant05 How can this be changed? I have a file but I do not know how to edit it 
![photo_5287685219547212049_y](https://github.com/user-attachments/assets/59ae2054-72ef-496b-8d29-3f499c17b2ad)
[Vasonch's Pack [MConverter.eu].zip](https://github.com/user-attachments/files/16459546/Vasonch.s.Pack.MConverter.eu.zip)
(converted mcpack to zip)
