### ISSUE TITLE
I can not make a block

### ISSUE THREAD

**Issue by cjibo** [bridge-core/editor#44]
I am trying to make a block with the bridge v2 and it will not work

**Comment by FrederoxGit** [comment]
Could you provide some more details? Is this block not being created inside of bridge? Or does it not work in game?

**Comment by cjibo2** [comment]
hi other account is bugged so yah not being created inside of bridge

**Comment by cjibo2** [comment]
this is my other account because my main is glitchy.

**Comment by cjibo2** [comment]
> Could you provide some more details? Is this block not being created inside of bridge? Or does it not work in game?


not being created inside of bridge

**Comment by cjibo2** [comment]
hello?

**Comment by solvedDev** [comment]
duplicate of #45
