### ISSUE TITLE
ignore_game_mode missing from decrement stack.

### ISSUE THREAD

**Issue by ihategravel2** [bridge-core/editor#440]
**Summary**

the decrement_stack event response is missing the "ignore_game_mode" object. 

**To Reproduce**
Steps to reproduce the behaviors

1. Create a 1.16.100+ block/item
2. Create a event
3. Add decrement stack

**Observed behavior**
A clear and concise description of what happened

There is no "ignore_game_mode" 

**Expected behavior**

There is a "ignore_game_mode" object.

`"decrement_stack": {
	"ignore_game_mode": true
}`

"ignore_game_mode" can be set to true/false.

This is not in the docs for some reason but it is included on the bedrock.dev wiki.
https://wiki.bedrock.dev/items/items-16.html#decrement-stack

**Comment by solvedDev** [comment]
`ignore_game_mode` has been added in v1.16.200 and therefore is locked behind this format version within bridge.
