### ISSUE TITLE
Bridge v2. Desktop App

### ISSUE THREAD

**Issue by wendellmeset** [bridge-core/editor#443]
**Summary**
I would like you to change bridge v2 into a desktop app as well. I know you can install it as app from your browser, however I feel safer knowing that I have a hard copy of the app even if the website goes down!

**Alternatives/Considerations**
Other than using the old bridge, none!

**Additional context/Motivation**
There aren't many screenshots to show, but may you please somehow convert this web app into a desktop application.

**Comment by jasonjgardner** [comment]
You're safe! bridge v2 works offline. Your browser will save everything it needs to reopen bridge. upon visiting the editor page.

**Comment by wendellmeset** [comment]
Thank you! But what if the website goes down @jasonjgardner ?

**Comment by solvedDev** [comment]
We didn’t have any downtime since we launched bridge. v2 and even if we would stop working on the project, someone else could pick it up as it’s open-source
