### ISSUE TITLE
not loading any broject or mcaddon files

### ISSUE THREAD

**Issue by jason7141** [bridge-core/editor#445]
**Summary**
When I load brojects or mcaddon they don't fully load and I can open anything behavior pack or resources pack
**To Reproduce**

4. Observe result

**Observed behavior**
A clear and concise description of what happened
**Expected behavior**

**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

**Platform (please complete the following information):**

-   OS: [e.g. Windows 10]
-   App Version: [e.g. 0.13.3]

**Additional context**

**Comment by jason7141** [comment]
![Screenshot_20220515-152405_Chrome](https://user-images.githubusercontent.com/105606159/168490373-ad60a7eb-d0a9-464e-a05b-7547326cb126.jpg)

**Comment by solvedDev** [comment]
Closing because of missing details
