### ISSUE TITLE
ERROR: Maximum call stack size...

### ISSUE THREAD

**Issue by hardlovedev** [bridge-core/editor#447]
The error "ERROR: Maximum call stack size..." happens when I have a server entity json file.
The error happens when my entity is too complex.. so far my entity has 100 component groups, 100 events and 100 interactions with the player.
This error does not have a step by step for sure but I will attach the file that happened to me.
This makes all autocomplete no longer work. this is bad because it makes me go to the wiki every new component or molang.

![Captura de tela 2022-05-20 005253](https://user-images.githubusercontent.com/76071951/169449052-9ffbd7ca-0d6d-4f6d-8888-aa839b573cb2.png)
[fire_dragon_male.zip](https://github.com/bridge-core/editor/files/8735890/fire_dragon_male.zip)

-   OS: [e.g. Windows 11]
-   BridgeV2 nightly
-   App Version: [e.g. 2.2.9]

**Comment by solvedDev** [comment]
Cannot reproduce the issue with your file

**Comment by Mardz38** [comment]
Having the same problem, sometimes this doesn't occur though.

**Comment by solvedDev** [comment]
I was just able to reproduce the issue

**Comment by solvedDev** [comment]
This is a Monaco editor we cannot fix at the moment. I've instead made the same error notification only appear once
