### ISSUE TITLE
Support new execute command

### ISSUE THREAD

**Issue by Joelant05** [bridge-core/editor#450]
Available as of 1.19.10.20

**Comment by Joelant05** [comment]
In order to support this, we need some way of supporting recursive command arguments, e.g. chain of as, at, unless and run in `execute as @a at @s unless block ~ ~1 ~ air 0 run say there is a block above my head`
Is this something you could look into when you get the time @solvedDev? I'll let you know if I think of a nice way of supporting this

**Comment by solvedDev** [comment]
I've been thinking about how to implement the new `/execute` as well. Maybe we can add the subcommands as normal commands and then have a new "requiredCommandPrefix" property?

**Comment by Joelant05** [comment]
How exactly would this work? I understand we could introduce `as`, `at` etc as individual commands with `"requiredCommandPrefix": "execute"` but what about when it comes to nesting these. We won't know what the prefix will be as it could be a selector for example, so how could we use "requiredCommandPrefix" then? Unless I have understood this wrong

**Comment by solvedDev** [comment]
“requireCommandPrefix” would look at the last command that was started, not the last argument the user typed.
Maybe something like this would work better:

```
{
  “requires”: {
    “commandBefore”: “execute”
  }
}
```

**Comment by Joelant05** [comment]
oh I see, but how would this let us choose when to begin the chain within the command?
e.g. `execute positioned as @p ...` how would it know when to propose the chain after this

**Comment by solvedDev** [comment]
An alternative would be to add a dedicate system for subcommands...

```json
{
  "commands": [
    {
      "commandName": "execute",
      "arguments": [
	{
	  "type": "subcommand",
          "allowMultiple": true
	}, 
        {
          "additionalData": {
	    "values": ["run"]
	  }
        },
        {
          "argumentName": "command",
          "type": "command"
        }
      ]
    }
  ],
  "subcommands": [
    {
      "commandName": "execute",
      "commands": [{...}]
    }
  ]
}
```

**Comment by solvedDev** [comment]
> oh I see, but how would this let us choose when to begin the chain within the command? e.g. `execute positioned as @p ...` how would it know when to propose the chain after `@p` specifically

I think this won't be a big problem but I believe my latest proposal probably still makes more sense

**Comment by Joelant05** [comment]
> An alternative would be to add a dedicate system for subcommands...
I like this format 👍

**Comment by Joelant05** [comment]
https://github.com/bridge-core/editor-packages/commit/1728c36ff2aa78845e12ee4efced5d8fa1f12747

**Comment by solvedDev** [comment]
6e372b0f04e8c3c7b0bb49970d82580c42b9f952
