### ISSUE TITLE
Make posible open files inside the com.mojang carpet as a toggleable option

### ISSUE THREAD

**Issue by Axelpvz2030** [bridge-core/editor#454]
Bridge V2 has many advantages over bridge v1, but bridge v1 is quicker to edit certain things. This wouldn't be a problem if both versions could be used together, but as Bridge v2 is unable to open files inside the com.mojang carpet, that is were bridge v1 saves all the chages, people have to choose between one of them, and most addon makers choose v1 because it is quicker for most things. I understand the reasons behind this limitation, but the user should be able to decide if block the option to open files inside com.mojang or not. Being able to do so would make easier to use both versions on the same addon for people that prefer v1 over v2

**Comment by solvedDev** [comment]
v2.3 will allow users to load projects from the com.mojang folder: a5ae29ddd2b160dc00d545916fec469b453be885
