### ISSUE TITLE
Block event auto-completion not showing

### ISSUE THREAD

**Issue by NguyenDuck** [bridge-core/editor#457]
**Summary**
Code suggestion don't available except first block event

**To Reproduce**

1. Edit my file below
2. Inside ```events``` block, add an events to next after last event
3. After write complete *event name*
4. Click *Ctrl + Space*

**Observed behavior**
Show suggestion be like first event typing
**Expected behavior**
No suggestion

**File:**
[https://pastebin.com/Z4Qu52WZ](url)

**Platform:**

-   OS: [Windows 10]
-   App Version: [2.2.11]

**Comment by Joelant05** [comment]
Are you talking about the event responses inside of the event not showing?
![image](https://user-images.githubusercontent.com/64587014/171380528-d40f1871-5a6b-42e1-b6eb-0dfb858bada3.png)

Or the actual event name?
![image](https://user-images.githubusercontent.com/64587014/171380634-4c6fcf48-8af8-4dd3-9d1e-d02dbb26a5b9.png)

Both are working as expected for me

**Comment by NguyenDuck** [comment]
@Joelant05 you can try again with my file!
