### ISSUE TITLE
open file project on website android device error

### ISSUE THREAD

**Issue by FPGTV** [bridge-core/editor#459]
![chrome_screenshot_1654426536998](https://user-images.githubusercontent.com/86946978/172047611-5b6c65c3-ab19-48cf-a506-6b72473bc294.png)

**Summary**

**To Reproduce**

4. Observe result

**Observed behavior**
A clear and concise description of what happened
**Expected behavior**

**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

**Platform (please complete the following information):**

-   OS: [e.g. Windows 10]
-   App Version: [e.g. 0.13.3]

**Additional context**

**Comment by solvedDev** [comment]
What does the error say?

**Comment by FPGTV** [comment]
> What does the error say?

Error: Trying to access project before it is defined. Make sure to await app.projectManager.projectReady.fired (at window.onunhandledrejection (https://editor.bridge-core.app/assets/main.9f011dae.js:2:68 5))

**Comment by FPGTV** [comment]
Error: Trying to access project before it is defined. Make sure to await
app.projectManager.projectReady.fired (at window.onunhandledrejection (
https://editor.bridge-core.app/assets/main.9f011dae.js:2:68 5))

ในวันที่ อา. 12 มิ.ย. 2022 22:24 น. solvedDev ***@***.***>
เขียนว่า:
