### ISSUE TITLE
Change where bridge syncs files

### ISSUE THREAD

**Issue by SineVector241** [bridge-core/editor#460]
**Summary**
Make it so you can toggle a switch or button which will move the packs to the non development packs automatically. Bridge will still be able to edit the pack but it will be updated in the non dev packs unless the user decides to toggle it back to to the development packs. Currently is a bit of a pain to move the packs to the non dev packs.

**Alternatives/Considerations**
I have no alternative considerations. This is open for discussion

**Additional context/Motivation**
No additional context.

**Comment by solvedDev** [comment]
Closing in favor of #355
