### ISSUE TITLE
ambient_sound_interval > event_names not supported

### ISSUE THREAD

**Issue by solvedDev** [bridge-core/editor#462]
![Bildschirmfoto 2022-06-10 um 10 47 41](https://user-images.githubusercontent.com/33347616/173028357-bef49cb0-8398-4a80-abd5-17a8d6754fce.png)

**Comment by Joelant05** [comment]
It should be supported in format versions 1.19.0+

**Comment by solvedDev** [comment]
👍 I just saw the error within the vanilla warden file 🙃

**Comment by Joelant05** [comment]
yeah, I wish they didn't use 1.16.0 as the version for new entities
