### ISSUE TITLE
Wrong slash is automatically added when editing dialogue texts with Tree Editor

### ISSUE THREAD

**Issue by a86296007** [bridge-core/editor#465]
**Summary**
A slash is automatically added when use "\n" to create a new line (or other similar stuff) in dialogue scene texts, which prevent stuff function correctly. 

**To Reproduce**

1. Set the editor to Tree Editor mode
2. Create a dialogue file in behavior pack
3. Make a valid scene which contains scene_tag, npc_name and texts
4. Use rawtext -> text in texts editing, and try create a new line with "\n"
5. Save and close the file, then switch the exitor to Raw Text mode
6. Open the same dialogue file, and check scene texts

**Observed behavior**
A extra slash was added before "\n", preventing the new line from creating. 
**Expected behavior**
This slash should not exist. 

**Screenshots / File Attachments**
![image](https://user-images.githubusercontent.com/91132489/173634352-abfbaecc-d7ec-4f6c-a7ca-c7c9d5d2f0b9.png)
![image](https://user-images.githubusercontent.com/91132489/173634538-6ef32bbe-fd06-4543-9f26-2522e4af5cad.png)
![image](https://user-images.githubusercontent.com/91132489/173634919-69d37810-c326-46b1-b49e-f404854f6425.png)
![image](https://user-images.githubusercontent.com/91132489/173635341-ca1975dc-1450-4d1a-bf2a-60ffb01c451f.png)

**Platform (please complete the following information):**
-   OS: Windows 11
-   App Version: 2.2.12

**Comment by solvedDev** [comment]
Thanks for the report, I'll take a look at fixing it for the next update 👍
