### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Swkiee** [bridge-core/editor#470]
basically when i make a blank entity it looks like every thing is working fine until i go into game with it and the texture isnt there i cant see it but i can still hit it. this is vary confusing. i just need to know the problem so i can fix my mistake

![Minecraft 6_20_2022 5_28_21 PM](https://user-images.githubusercontent.com/90010096/174679997-e2ab5e52-5b7e-4b7b-90ea-c2fd8a6274d9.png)

**Comment by Joelant05** [comment]
Please use a help channel in our discord for Add-on questions. Issues are for feature requests and bug reports for bridge.
