### ISSUE TITLE
compiler is stuck when move file fast

### ISSUE THREAD

**Issue by NguyenDuck** [bridge-core/editor#474]
**Summary**
compiler is stuck when move file fast
compiling icon at left will never hide or remove when error is thrown
after that, if save all files if be infinite loading screen

**Screenshots / File Attachments**

![Screenshot (5)](https://user-images.githubusercontent.com/83252725/175473501-b12e67df-64cc-4c64-9d14-fbb73d5c8929.png)

![Screenshot (6)](https://user-images.githubusercontent.com/83252725/175474860-7977ab5f-8fe2-49dd-81ad-a80d600eec04.png)

**Platform:**

-   OS: Windows 10
-   App Version: 2.2.13

**Comment by solvedDev** [comment]
The issue should be fixed on the latest nightly build
