### ISSUE TITLE
"Add Object" fails to add object

### ISSUE THREAD

**Issue by ihategravel2** [bridge-core/editor#483]
https://discord.com/channels/602097536404160523/602097536840237087/990605899158679642

**Comment by solvedDev** [comment]
Fixed an issue with the "force value" input not reacting to clicks correctly but I cannot reproduce the other issue you've reported on the nightly build anymore. I am therefore closing the issue as "cannot reproduce"

**Comment by ihategravel2** [comment]
I will try it out on nightly.
