### ISSUE TITLE
Scroll Lag

### ISSUE THREAD

**Issue by Xterionix** [bridge-core/editor#487]
**Summary**
Scrolling through large files is noticeably slow

**To Reproduce**

1. Open large file
2. Scroll all the way down

**Observed behavior**
Freezes for a few seconds in between
**Expected behavior**
Scroll to the bottom without any freezing

**Screenshots / File Attachments**
[Already sent in the Discord](https://discord.com/channels/602097536404160523/602097536840237087/990803055064805457)

**Platform (please complete the following information):**

-   OS: Windows 10
-   App Version: 2.2.13

**Comment by solvedDev** [comment]
I believe this should be fixed on the latest nightly build
