### ISSUE TITLE
Changing BP & RP Labels

### ISSUE THREAD

**Issue by Xterionix** [bridge-core/editor#488]
**Summary**
Allow a global config in the settings similar to the default author on how pack should be named. Like "Name BP" to "Name [BP]"

**Alternatives/Considerations**
You could always manually rename it but that gets tedious when there are a lot of packs

**Additional context/Motivation**
Just a QOL thing, to match with my other pack formats

**Comment by solvedDev** [comment]
https://github.com/bridge-core/dash-compiler/commit/70f36561498b87fe6f7d127f6ca8b00aa4910d16
