### ISSUE TITLE
Block Code-Autocomplete

### ISSUE THREAD

**Issue by NguyenDuck** [bridge-core/editor#490]
**Summary**
Code Auto-complete doesn't suggest in event trigger "run_command" affected "/playsound" command

**Screenshots / File Attachments**
![image](https://user-images.githubusercontent.com/83252725/177251003-8665d508-b526-43cd-92dd-0164944faf16.png)

**Platform:**

-   OS: Windows 10
-   App Version: 2.2.13

**Comment by Joelant05** [comment]
https://github.com/bridge-core/editor-packages/commit/9ecb32eb1aa70ac6382cc8b8ecfc2dd6dc0d371a
