### ISSUE TITLE
Pack paths in config.json not respected

### ISSUE THREAD

**Issue by Joeyrsp** [bridge-core/editor#50]
**Summary**
When I change the pack paths in the project config.json, the packs are not correctly located. After perusing the source it looks like the pack paths from the config.json are read into the config object and then never actually used by loadPacks, PackTypes, etc.

**To Reproduce**
1. Create new project
2. Close bridge
3. Rename or move packs (e.g. 'BP' => 'Behaviour_Pack')
4. Update config.json with new pack paths (e.g. './BP' => './Behaviour_Pack')
5. Open bridge

**Observed behavior**
Bridge cannot find the packs
**Expected behavior**
Bridge finds the packs in their new location

**Platform:**
 - OS: Windows 10
 - Browser: Chrome 92.0.4515.131
 - Bridge: 2.0.3
 - Also checked on dev branch: bdfe4fbbb9ef496afc4064f5921cf544e5b710b5

**Additional context**
I came across this while trying to transition a project in a git repo into a project folder. After trying to change the paths, I've worked around with a couple of sym links so bridge sees the BP and RP folders and the git repo preserves its history.

**Comment by solvedDev** [comment]
We don't support the full specification defined [here](https://github.com/bridge-core/project-config-standard) just yet but we're want to eventually. Especially the pack path configuration is a bit tricky because everything is currently hardcoded to the default folders

**Comment by Joeyrsp** [comment]
Ahh looks like I must have got mixed up with bridge v1 documentation. Thanks for the prompt clarification. If I get time I'll see if I can implement it.

**Comment by solvedDev** [comment]
Nope, this is totally on us, you didn't mix anything up :)
I would have expected this to work too if I wouldn't work on the app 🙃

**Comment by solvedDev** [comment]
We will update pack spider with support for this feature later. Apart from that, the nightly build should fully support user-defined pack paths now! :)
