### ISSUE TITLE
Custom recipies including custom item dont work

### ISSUE THREAD

**Issue by YesItsRedPanda** [bridge-core/editor#503]
**Summary**
I am making a mod which i have many custom item that i used for crafting. When put in everything it doesnt work

**To Reproduce**

1. create blank item
2. create second blank item
3. add crafting recipie that require the first item to make the other

**Observed behavior**
when the game loaded i couldnt craft the sword i wanted with the item
**Expected behavior**
To get a sword by using a custom material

**Platform (please complete the following information):**
Windows 10

**Comment by solvedDev** [comment]
This is not a bridge. bug, it's most likely an user error. You can get add-on help on our Discord server
