### ISSUE TITLE
Auto import creates incorrect path

### ISSUE THREAD

**Issue by Joelant05** [bridge-core/editor#504]
![image](https://user-images.githubusercontent.com/64587014/178484963-addfb0dd-d173-4b9e-ba00-55190de60dbe.png)

Path should instead be "scripts/test.js"

**Comment by Joelant05** [comment]
Yeah, it is called "BridgeTest"

**Comment by solvedDev** [comment]
Looked into this today and didn't found a way to fix the issue on our end
