### ISSUE TITLE
Allow compatibility for the Minecraft Bedrock Launcher

### ISSUE THREAD

**Issue by KaidenSkywalker** [bridge-core/editor#506]
**Summary**
The Minecraft Bedrock Launcher (https://bedrocklauncher.github.io) does not have a com.mojang folder and therefore cannot be used along side of bridge. v2.

**Alternatives/Considerations**
A solution could to just allow the selection on the packageData folder or even just allow the selection of any folder that has a child folder of "packageData" or something else.

**Additional context/Motivation**
None

**Comment by solvedDev** [comment]
With bridge. v2.3, any folder can be registered as an output folder. There's a preview of this functionality already available on our [nightly build](https://nightly.bridge-core.app/) but we still have a significant rewrite of the output folder system pending

**Comment by KaidenSkywalker** [comment]
how can I select the output in the nightly version of bridge?
