### ISSUE TITLE
[BUG] Tree editor cannot create recipes

### ISSUE THREAD

**Issue by BloodShotYT** [bridge-core/editor#51]
**Summary**

with the tree editor you cant make recipe and some stuff is broken pls fix it i cant make any mods with this bug's
and maby i just go to v1 of bridge bks its good there

**Comment by outercloudstudio** [comment]
Try using the text editor as it is a lot more complete and will help you understand the actual json and not a tree representation of it better.

**Comment by solvedDev** [comment]
(We will also look into improving the tree editor further for v2.1 though)

**Comment by solvedDev** [comment]
It looks like this will be closed by the changes made in v2.1. If this is not the case, feel free to reopen the issue with more details on your problem.
