### ISSUE TITLE
Renaming files does not compile correctly

### ISSUE THREAD

**Issue by Chikorita-Lover** [bridge-core/editor#521]
**Note**: This is a bridge. Nightly issue

**Summary**
When renaming a file (either through the rename or duplicate action), the compiled file of the original name is not deleted and remains in the compiler output (not in the bridge. project). Additionally, the new file is not compiled, and needs to be refreshed/saved to be compiled.

Moving a file has the same effect: the old file is kept in the compiler output, and the new file is not compiled.

**To Reproduce**

1. Open the pack explorer
2. Right-click on a file
3. Rename the file
4. Open the compiler output in File Explorer
5. Observe result

**Observed behavior**
The original file is left in the compiler output, and the new file is not compiled
**Expected behavior**
The original file should be deleted, and the new file should be compiled.

**Platform (please complete the following information):**

-   OS: Windows 10
-   App Version: 2.3.0

**Comment by solvedDev** [comment]
Yep, this hasn't been added back yet. It's one of the last things of the old directory viewer that I still need to port over
