### ISSUE TITLE
Bridges broken

### ISSUE THREAD

**Issue by ace06260** [bridge-core/editor#532]
Having issues with bridge.
I'm trying to make a DUI dialogue and it keeps on putting massive gaps in between the lines.
It did not do this at first when I started working on my project today but since three something July 21st
I have been having nothing but issues.
Here are some pics
![Screenshot_20220721-170951](https://user-images.githubusercontent.com/97758903/180327341-8bf4745f-e2b2-4f41-ba17-992da2b7d53f.png)
![Screenshot_20220721-173115](https://user-images.githubusercontent.com/97758903/180327360-08100b0f-962d-4d10-9ab4-a38425c6090f.png)

Not sure what's going on but I hope you can fix it.
These are the extensions I'm using and I'm using a Motorola Stylo g
![Screenshot_20220721-173528](https://user-images.githubusercontent.com/97758903/180327490-04ca0ee6-1344-41d4-999d-9a44a21a33db.png)

**Comment by Joelant05** [comment]
This appears to be a user error; the compact prettier extension seems to have been misconfigured. In the sidebar tab for this extension, you should try changing the settings, or disable the extension completely if you cannot get that to work
