### ISSUE TITLE
Function names don't let you add capital letters, but minecraft fully supports it.

### ISSUE THREAD

**Issue by Micah-Suess** [bridge-core/editor#538]
Everything you need to know is in the title.

**Comment by solvedDev** [comment]
We know that this works for most of Minecraft's files. This rule was originally put in place to enforce consistent naming across all files within a project. I also vaguely remember something about one of Minecraft's platforms not correctly supporting uppercase letters within file paths but this information could be outdated by now. 

I am personally in favor of keeping this rule (another advantage is that we avoid one of the major differences between Windows/Unix file systems with this rule).
@Joelant05, what's your position on this?

**Comment by Joelant05** [comment]
I would like to keep the rule to maintain the `snake_case` naming scheme which applies to the majority of addon files (name and content). I think it is better to keep things consistent

**Comment by solvedDev** [comment]
Closing the issue as won't fix. If you have additional reasons for this change, please let us know though!
