### ISSUE TITLE
.bbmodel importer doesn't work correctly

### ISSUE THREAD

**Issue by Tschipp** [bridge-core/editor#539]
**Summary**
The texutres are imported to the wrong location, then it errors and hangs

**To Reproduce**
import a .bbmodel and select "entity"

**Observed behavior**
the texture is imported as a subfolder of the entity folder, but still inside the block folder

**Screenshots / File Attachments**
![image](https://user-images.githubusercontent.com/11649893/181440983-728e4362-eff4-43f8-8048-2ef210ca9aec.png)

**Platform (please complete the following information):**

-   OS: Win10
-   App Version: Latest Nightly

**Comment by solvedDev** [comment]
https://github.com/bridge-core/editor/commit/f40b98244d6621208aa94bdcfb003a25b4e8a19c
