### ISSUE TITLE
Asset preview window freezing

### ISSUE THREAD

**Issue by Joelant05** [bridge-core/editor#540]
![image](https://user-images.githubusercontent.com/64587014/181482888-bfbdb313-083b-4b93-8d76-c44bf0ad6931.png)

Getting this error consistently when opening any entity in the asset preview window. The preview in the window is working, but the window controls freeze, so can't do things like close the window

**Comment by solvedDev** [comment]
We are unable to fix the issue rn. I am not sure what is causing this internal Vue bug but my hope is that it gets resolved by #502
