### ISSUE TITLE
Keyboard shortcuts are unreliable

### ISSUE THREAD

**Issue by Chikorita-Lover** [bridge-core/editor#549]
**Note:** This is a bridge. Nightly issue

**Summary**
With unknown reasoning, keyboard shortcuts in bridge. (e.g. Ctrl + N to create a new file) may sometimes execute outside of bridge. Instead of creating a new file, Ctrl + N may instead open a new Chrome tab if installed with Chrome. Ctrl + O to open a new file, for example, may do nothing some of the time.

**Observed behavior**
The keyboard shortcut is not executed within bridge., but within the browser
**Expected behavior**
All keyboard shortcuts should execute in bridge. when the window is active

**Platform (please complete the following information):**

-   OS: Windows 10
-   App Version: 2.3.0

**Comment by solvedDev** [comment]
Cannot reproduce reliably atm, delaying further investigations

**Comment by solvedDev** [comment]
Is this still an issue?
Make sure that you're testing this with a version of bridge. that's installed to your device
