### ISSUE TITLE
Opening certain items fails before project is first opened

### ISSUE THREAD

**Issue by Chikorita-Lover** [bridge-core/editor#550]
**Note:** This is a bridge. Nightly issue

**Summary**
Before any project is first opened in a bridge. session, certain items cannot be opened in bridge. From testing, these include files and the extension store. Such files may be from the Vanilla Pack Viewer extension or from opening them (i.e. Ctrl + O on Windows). When these are attempted to be opened, no error or pop-up is provided.

**To Reproduce**

1. Open bridge.
2. Attempt to open an external file or the extension store
3. Observe result

**Observed behavior**
Certain items, including files and the extension store, will not open
**Expected behavior**
All items should be able to be open before a project is opened.

**Platform:**

-   OS: Windows 10
-   App Version: 2.3.0

**Comment by solvedDev** [comment]
Both the extension store and all files open fine without a project for me. Are you sure that this issue is not caused by an extension?
