### ISSUE TITLE
The Wood Preset is not working/Downloading

### ISSUE THREAD

**Issue by Laiffo** [bridge-core/editor#553]
**Summary**
I had this for like 2-3 Days.
When Trying to Download the new Wood preset, it gave off an error, and the Wood preset loading repeatedly (Not the Error, the Loading circle that was in the box of the Extension), and when then closing the extension menu and trying to use the Preset, it gave off another error

**To Reproduce**

1. Download the new Wood Preset
2. Use it

**Observed behavior**
It gives off 2 Errors:
One when downloading the preset
And the Second when using it
**Expected behavior**
The Wood Preset working

**Screenshots / File Attachments**

While downloading the Preset:
![Screenshot (3985)](https://user-images.githubusercontent.com/87951487/183297205-271bff5e-8ab5-443f-a1d5-193fb3618fbb.png)

While trying to use the Preset
![Screenshot (3986)](https://user-images.githubusercontent.com/87951487/183297216-d875adb8-71fd-43c7-8368-e27e27ee7663.png)

**Platform (please complete the following information):**

-   Windows 10
-   Bridge Nightly V. 2.3.0

**Additional context**
I have heard that this issue only really happens to me, therefore it might not be able to reproduce

**Comment by solvedDev** [comment]
@Gekocaretaker I've fixed this first installation issue but the preset creation issue gets caused by you using the built-in "presetScripts/blockImages.js" preset script incorrectly. You probably need to write your own preset script based on ours to make all of your file inputs work

**Comment by solvedDev** [comment]
Cleared the milestone because this is a plugin issue
