### ISSUE TITLE
Dragging a `com.mojang` folder to Bridge. results in nothing on Chromebook

### ISSUE THREAD

**Issue by VenomousSteam81** [bridge-core/editor#554]
**Summary**
Dragging Minecraft's `com.mojang` folder results in nothing happening on a Chromebook

**To Reproduce**
1. Open Bridge.
2. Try to drag Minecraft's `com.mojang` folder to Bridge.

**Observed behavior**
Nothing happens
**Expected behavior**
Bridge. to accept and show that I dragged the folder.

**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

**Platform (please complete the following information):**

-   OS: ChromeOS
-   App Version: Latest Website

**Additional context**
None

**Comment by solvedDev** [comment]
This is a chrome OS platform issue. We've already added a dedicated "Open Folder" action (similar to "Open File") that'll enable this functionality for v2.3 though.

**Comment by solvedDev** [comment]
You can beta test v2.3 via our nightly builds: https://nightly.bridge-core.app/

**Comment by VenomousSteam81** [comment]
Got it. Thank you!
