### ISSUE TITLE
Ability to install extensions both locally and globally

### ISSUE THREAD

**Issue by Tschipp** [bridge-core/editor#56]
**Summary**
Ability to install extensions both locally and globally

**Alternatives/Considerations**
Apart from uninstalling a global extension and reinstalling it locally, there's no way to get get a local extension when it is already global.

**Additional context/Motivation**
This is useful when working with multiple people on a shared project.

**Comment by outercloudstudio** [comment]
Maybe a bridge project could store which extensions it uses then if those extensions are not installed, install them.

**Comment by solvedDev** [comment]
![Bildschirmfoto 2022-07-29 um 15 00 15](https://user-images.githubusercontent.com/33347616/181765815-29f61df1-4953-40fb-8457-8fadd9a1a6a6.png)
