### ISSUE TITLE
Add screenshots to PWA manifest

### ISSUE THREAD

**Issue by solvedDev** [bridge-core/editor#560]
Screenshots are now used within the install UI on desktop and mobile Chrome

https://twitter.com/alexey_rodionov/status/1559056724232785921?s=21&t=oWhf0ETi2YluusOCU0mKQQ

**Comment by Joelant05** [comment]
Relevant commits
https://github.com/bridge-core/editor/commit/37de5eb5edf32f62e4e48cbbe292f018321a9846
https://github.com/bridge-core/editor/commit/ad2baad698db8ebaa314268468eab3d94c7e664b
https://github.com/bridge-core/editor/commit/d9feac9d6ec693ca71667eb7affeb93153db7030
