### ISSUE TITLE
Xbox problem

### ISSUE THREAD

**Issue by itsscristian** [bridge-core/editor#561]
Hi I have a problem. I do not have a pc and my phone broke and I use my xbox and the website detects as if it were a computer but it is not and asks me to select a folder to save files but on xbox it is not possible if they solve that would be incredible they could make it be saved in google drive

**Comment by jasonjgardner** [comment]
Although Edge on Xbox poses as a full-featured Chromium version, it **can't** support certain APIs required by bridge. The write permissions on Xbox are very strict. (Probably to avoid modding workarounds.)

Unfortunately, even if this feature was in bridge., the Xbox will not let you save anything to its file system from Edge. Maybe with the exception of images or plain-text documents, but certainly not .mcpack or .mcaddon files.

**Comment by solvedDev** [comment]
I think we might be able to enable the file system polyfill for Edge on Xbox but a problem I see is actually reliably detecting that Edge runs on an Xbox

**Comment by Joelant05** [comment]
I think Edge on xbox recently blocked any file downloads at all, so even the fs polyfill wouldn't be an option as you wouldn't be able to download the project

**Comment by ihategravel2** [comment]
Yah they did. I don't think Xbox Support would be worth it at this point due to the extremely restricted file system.

**Comment by solvedDev** [comment]
Closing because of the reasons mentioned above.
