### ISSUE TITLE
[Feature] Overwriting existing files

### ISSUE THREAD

**Issue by Tschipp** [bridge-core/editor#57]
**Summary**
When dragging/dropping a file onto bridge which already has the same name (and type), allow us to overwrite the file or just manually set a path for the new file.

**Alternatives/Considerations**
Alternatives so far consist of either copying file contents, or copying the file's destination path

**Additional context/Motivation**
Would save time

**Comment by solvedDev** [comment]
Has this been resolved with the new file type guessing that's part of v2.1?

**Comment by Tschipp** [comment]
yes
