### ISSUE TITLE
Still with the new update you cannot load previous projects

### ISSUE THREAD

**Issue by jason7141** [bridge-core/editor#570]
**Summary**
When you load a previous project it says it's been removed.

**To Reproduce**

1. Go to file import project
2. Click on import project
3. Scroll down to whatever project you made previous to the update
4. Observe result project removed

**Observed behavior**
When you upload an old file it shows on home screen for a split second and then is removed
**Expected behavior**
M
I dunno maybe actually download the project I selected it's been an issue since the last update

**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

**Platform (please complete the following information):**

-   OS: [e.g. Windows 10]
-   App Version: [e.g. 0.13.3]

**Additional context**

**Comment by jason7141** [comment]
The direction the app for my tablet is going in the right direction this is the only issue I have and I love the app. Keep up the good work

**Comment by solvedDev** [comment]
Can reproduce the issue but closing in favor of #600
