### ISSUE TITLE
Tree Editor: randomize and sequence event responses don't work correctly in the tree editor

### ISSUE THREAD

**Issue by carpoolxx** [bridge-core/editor#572]
When You create an event for a item and choose the randomize or Sequence event thing it doesn't allow you to input the other option.

As shown here it only gives you these two options 
![Screenshot (142)](https://user-images.githubusercontent.com/111540605/185505361-bf585c8f-5e50-4dd2-a1a8-c61242461df4.png)

And if you click them and try to continue by putting in the input it lists it just closes the tab your in 
![Screenshot (140)](https://user-images.githubusercontent.com/111540605/185505765-8d0ffdf7-0b07-41c1-9d85-379c7af30700.png)

**Comment by Joelant05** [comment]
This also effects entity and block event responses. Seems to be because the tree editor doesn't correctly support how I've set up the event response schemas.

**Comment by solvedDev** [comment]
Fix will be available shortly on our nightly build: https://nightly.bridge-core.app/
