### ISSUE TITLE
DirectoryViewer not showing icons

### ISSUE THREAD

**Issue by FrederoxDev** [bridge-core/editor#576]
https://discord.com/channels/602097536404160523/810611353588465674/1010262680227037196

Extension with the issue: [MarkdownDocs.zip](https://github.com/bridge-core/editor/files/9384774/MarkdownDocs.zip)

**Comment by solvedDev** [comment]
This is not a bug, you need to define the `startPath` to make file types work:

```vue
<DirectoryViewer 
  :renderTopLevelDirectory="true" 
  :directoryHandle="sidebarContent.directoryHandle" 
  :options="{
    isReadOnly: false, 
    startPath: sidebarContent.docsPath
  }"
/>
```
