### ISSUE TITLE
Show schema errors in tree editor

### ISSUE THREAD

**Issue by Chikorita-Lover** [bridge-core/editor#579]
**Summary**
At the moment, schema errors (yellow underlines) only show in the raw text, and not the tree editor. Adding these to the tree editor with a yellow underline or warning sign (similar to the legacy version of bridge.) would help a lot for tree editor users.

**Additional context/Motivation**
![Screenshot (358)](https://user-images.githubusercontent.com/68617589/185798173-081a8743-1278-4c98-9fd9-f01510b2ab03.png)

**Comment by Joelant05** [comment]
Closing in favor of https://github.com/bridge-core/editor/issues/101
