### ISSUE TITLE
View model pane throwing a script error

### ISSUE THREAD

**Issue by sitefinitysteve** [bridge-core/editor#58]
**Summary**
The "View Model" feature shows nothing, devtools shows an error that it can't find textures?

**To Reproduce**
1. Add Entity
2. Open resource
3. Click View Model

**Screenshots / File Attachments**
![Screenshot 2021-09-02 122028](https://user-images.githubusercontent.com/1542376/131883312-58d8e56c-2e4b-4426-ab41-0a4b55fd963d.png)
![Screenshot 2021-09-02 122054](https://user-images.githubusercontent.com/1542376/131883318-9106d084-516a-4cf7-aac7-53fe19150bc3.png)

**Platform (please complete the following information):**
Windows 10
2.0.3

**Additional context**
- Bridge project files are stored in OneDrive
- Error only trips after clicking the View Model button
- Made sure uBlock wasn't running (no other extensions)

**Comment by solvedDev** [comment]
Thanks for your report!
This issue has already been fixed for v2.1. You can check out our nightly build until this update is available:

https://nightly.bridge-core.app/

**Comment by sitefinitysteve** [comment]
Oh Apologies, I'm new, didn't even know this was a thing!

**Comment by solvedDev** [comment]
No worries, this issue wasn't tracked on GitHub yet so I don't mind your report :)
