### ISSUE TITLE
Generator Scripts don't automatically change file format to .mcfunction for function files

### ISSUE THREAD

**Issue by AdamodeOne** [bridge-core/editor#581]
**Summary**
Generator Scripts are supposed to automatically change the file format from `.js` to `.mcfunction` when a generator file is in the `functions` folder. However, the file remains a `.js` file after compilation

**To Reproduce**

1. Create a generator file in the functions folder of a project
2. Compile the project
3. Observe the file remain as `.js` in the output folder

**Observed behavior**
The output file has the file type `.js`
**Expected behavior**
The output file should have the file type `.mcfunction`

**Platform (please complete the following information):**

-   OS: Windows 10
-   App Version: v2.3.1

**Comment by solvedDev** [comment]
Fix will be available with bridge. v2.3.2 and Dash v0.9.28 later today
