### ISSUE TITLE
Loot Table auto-completions either don't work or are broken half the time

### ISSUE THREAD

**Issue by BeeTeeKay64** [bridge-core/editor#582]
**Summary**
While working with loot tables I have noticed that some auto-completions went missing or changed after v2.3.0 (currently using v2.3.1). This is using the tree editor.

**To Reproduce**

1. Make a Loot Table file
2. Remove 'pools' to remove everything in the file
3. Save and reopen the file (clicking on the 'pools' auto-completion doesn't work until you reopen it)
4. Add 'pools' via auto-completion and then add 'entries' via auto-completion

**Observed behavior**
'pools' does not have 'rolls' or 'tiers' as auto-completions; 'entries' does not automatically go inside curly brackets when auto-completed; clicking on 'entries' shows auto-completions meant for 'pools'. When 'entries' does end up in curly brackets manually, it does not allow you to add any entries.
**Expected behavior**
'pools' should also have 'rolls' and 'tiers' as auto-completions; 'entries' should automatically go in curly brackets, and it should also allow you to add more entries.

**Workaround**
As a workaround, obviously you just don't delete 'pools' or 'entries' when you make the file, but you are still unable to add any other entries.

**Screenshots / File Attachments**
![loot_table_bug_2](https://user-images.githubusercontent.com/76896809/186086613-efbedf57-63b1-42db-b15b-95419c7a1306.PNG)
![loot_table_bug_3](https://user-images.githubusercontent.com/76896809/186086618-49e6428c-2c0d-403c-a78a-71089911cffa.PNG)
![loot_table_bug_1](https://user-images.githubusercontent.com/76896809/186086610-6f0c9c61-c590-43d4-8417-d6f75d5bda01.PNG)

**Platform (please complete the following information):**

-   OS: Windows 10
-   App Version: v2.3.1

**Additional notes**
If these technically count as more than one bug then I truly apologize, these all regard loot table auto-completions and I figured they were all because of the same bug, if not under the same category.

**Comment by solvedDev** [comment]
Fix will be available shortly on our nightly build: https://nightly.bridge-core.app/
