### ISSUE TITLE
Schema reference error

### ISSUE THREAD

**Issue by MasterDiegoCreations** [bridge-core/editor#587]
The references of the mob do not load me

when putting something in mob components, I don't get references

In bridge you go to any mob
on any components, groups of components, or events
no examples come out

it shows me an error
is next
Problems loading reference 'file:///data/packages/minecraftBedrock/schema/entity/general/eventDefinition.json': Unable to load schema from '\data\packages\minecraftBedrock\schema\entity\general\eventDefinition.json'. No schema request service available(768)

the platform is Windows 10 and the version of the ap is v2.3.2

**Comment by Joelant05** [comment]
Do you have any extensions installed?

**Comment by MasterDiegoCreations** [comment]
Yes.. I don't even know which ones to install. But if it has happened to me
when I did not have any extension

**Comment by Joelant05** [comment]
Could you just let me know what extensions you have installed anyway?

**Comment by MasterDiegoCreations** [comment]
Yes, I don't know how I can do it to see the ones that I already deleted
but the ones that are active are "Navigator by Tschipp"

**Comment by Joelant05** [comment]
I've pushed a fix to this now, you just need to update the "Navigator" extension
