### ISSUE TITLE
[BUG] bridge crashes Chrome (in macOS)

### ISSUE THREAD

**Issue by carlop3333** [bridge-core/editor#59]
**Summary**
When opening bridge for first time Chrome crashes (even when you open a old project)

**To Reproduce**
1. Open bridge-editor for first time (skip com.mojang)
2. Create a new project.
3. Chrome crashes.

or
1. Open bridge-editor (on a old project)
2. Chrome crashes.

**Screenshots / File Attachments**
none (only the chrome report crash but this is not chromium)

**Platform**
 - OS: macOS 10.14 (with Chrome 93)
 - App Version: 2.0.3

**Comment by FrederoxGit** [comment]
This is a known issue currently. Microsoft Edge will work completely fine
