### ISSUE TITLE
Autocompletions dont show up on chrome

### ISSUE THREAD

**Issue by Omena0** [bridge-core/editor#601]
**Summary**
On chrome autocompletions for functions dont show up. But on edge they did just fine.

**To Reproduce**

1. Open Bridge (chrome)
2. Create a function 
3. Type a command
4. Observe result

**Observed behavior**
Autocompletions for functions dont show up
**Expected behavior**
Autocompletions show up

**Screenshots / File Attachments**
![image](https://user-images.githubusercontent.com/82773737/188319795-c8343122-2c37-4a6a-8914-52c030120ed8.png)

**Platform (please complete the following information):**

-   OS: Windows 10
-   App Version: 2.3.2 (chrome)

**Additional context**
After using bridge for a long time edge suddently stopped working so i started using chrome for bridge.

**Comment by Omena0** [comment]
i literally cannot use bridge without autocompletions

**Comment by Omena0** [comment]
OH! i just realised that on my other project the autocompletions do work, but on my new one it doesent...

**Comment by Omena0** [comment]
Oh i just had to delete the project and create a new one

**Comment by Joelant05** [comment]
Even though you fixed your problem, in future could you send us the project that has issues so we can look into it anyway

**Comment by Omena0** [comment]
True, But i am still having issues with bridge autocompletions. They only show up some times. Also i am still forced to use chrome, but when edge works, bridge also works. Could be caused by the fact that chrome uses 20% of my cpu lmao
