### ISSUE TITLE
Incorrect component listing for  "Light_emission"

### ISSUE THREAD

**Issue by cakeGit** [bridge-core/editor#603]
**Summary**
Incorrect component listing

**To Reproduce**

1. Go to any block file's components
2. Click on add
3. Search for 'light'
4. Observe result

**Observed behavior**
"block_light_emission" appears as a valid component
**Expected behavior**
Most likely supposed to be "light_emission"

**Screenshots / File Attachments**
![image](https://user-images.githubusercontent.com/65340665/188509810-a89b91fe-7b00-4a36-b431-d5360ea8472d.png)

**Platform (please complete the following information):**

-   OS: Windows 11 [Edit: Running off Chrome]
-   App Version: V2.3.2

**Comment by Joelant05** [comment]
@cakeGit Ensure you have set the correct `format_version` in your file, we already have auto-completions for `light_emission` for format versions of 1.19.20 and above
