### ISSUE TITLE
[BUG] Compiler doesn't work?

### ISSUE THREAD

**Issue by Broascaa** [bridge-core/editor#61]
**Summary**
When i click to compile the files nothing happens on minecraft bedrock and when i check com.mojang i don't see any file created into resources and behaivor.

**To Reproduce**
Just compiling the resource using the web or desktop app (both has the same problem) and no files are generated into com.mojang

**Observed behavior**
-

**Expected behavior**
-

**Screenshots / File Attachments**
![Capture](https://user-images.githubusercontent.com/86567732/132952812-f900d8c2-42eb-4c11-aa0d-9e128dd2b525.PNG)
same thing with behaivor file

**Platform (please complete the following information):**
 - OS: Windows 10
 - App Version: v2.0.3

**Additional context**
How can i solve this?

**Comment by Joelant05** [comment]
Have you linked the com.mojang folder by dragging it onto bridge?

**Comment by Broascaa** [comment]
I don't understand..
So do i need to drag projects file into com.mojang?

**Comment by Broascaa** [comment]
Oh, i understand now..
Sorry, i was thinking in another place..
I think i didn't did that.. How can i link it?

**Comment by Joelant05** [comment]
You just find the com.mojang folder in file explorer and drag the folder onto bridge.

**Comment by Broascaa** [comment]
Founded, solved!

**Comment by Broascaa** [comment]
Thanks!

**Comment by Joelant05** [comment]
This then links it and your dev compiler output will end up in the development folders
