### ISSUE TITLE
Tests for editor-packages

### ISSUE THREAD

**Issue by Joelant05** [bridge-core/editor#611]
We should set up checks that run in GitHub actions when a commit is made to the editor-packages repo. Ideally this should:
- Check every JSON file in the commit for syntax errors
- Resolve $refs recursively in the changed files to ensure they all lead somewhere valid

**Comment by solvedDev** [comment]
Do you maybe also want to automatically run this when we make commits to the repo?

**Comment by Joelant05** [comment]
Yeah, I'll see if I can set that up
