### ISSUE TITLE
Subfolders not closing when closing parent folder

### ISSUE THREAD

**Issue by pascal541** [bridge-core/editor#616]
**To Reproduce**
1. Open some folders and subfolders
2. Close the parent folder
3. Refresh the project
4. The parent folder opens (because the subfolders are still opened)

**Expected behavior**
All subfolders should be closed after closing the parent folder

**Screenshots / File Attachments**
![image](https://user-images.githubusercontent.com/7486865/190702706-d46f27c3-c9d9-482d-80bf-b35b9035afff.png)

**Platform (please complete the following information):**

-   OS: Windows 10
-   App Version: 2.3.3

**Additional context**
I hope this gives enough information. If not, let me know and I can send a video or screenshare on Discord.

**Comment by Joelant05** [comment]
This may be intended since double clicking a folder opens/closes all subfolders. I'll wait for @/solvedDev confirm this though before we close the issue

**Comment by solvedDev** [comment]
If I understand this correctly, the bug is that refreshing the project re-opens the parent folder even though it should stay closed

**Comment by pascal541** [comment]
> If I understand this correctly, the bug is that refreshing the project re-opens the parent folder even though it should stay closed

As far as I know, it indeed only happens when refreshing the project
