### ISSUE TITLE
Bridge Compiles To Bridge Folder

### ISSUE THREAD

**Issue by outercloudstudio** [bridge-core/editor#626]
**Summary**
My bridge nightly editor all of a sudden began compiling to my bridge folder instead of com.mojang and I can not get it to go back even after resetting the browser, restarting bridge, resetting output folder, bridge folder, and so on.

**To Reproduce**
I honestly do not know what to do to reproduce this as I myself can not. I assume you try to create a project and compile it to a com.mojang folder.

**Observed behavior**
A developement_behaviours and resource folder apear in the bridge folder.
**Expected behavior**
These folders should apear in designated com.mojang folder.

**Platform (please complete the following information):**

-   OS: Windows 10
-   App Version: 2.3.3

**Comment by solvedDev** [comment]
This bug is actually a consequence of the pack indexer becoming so much faster. There's currently a race condition where we create the dash compiler service (depending on how long the pack indexer takes) before the com.mojang folder was setup
