### ISSUE TITLE
Upgrade a addon to a newer version

### ISSUE THREAD

**Issue by H017269L** [bridge-core/editor#633]
**Summary**
This feature will allow creators to upgrade their addons to newer versions when there has been an update to the code, for example: 1.19 to 1.19.30 when the developers changed the "minecraft:destroy_time" to "minecraft:destructible_by_mining" ect. This will allow developers to easily Update addons to newer versions.

**Alternatives/Considerations**
An Alternative could be allowing the Developer to change the version the addon was created in to quickly allow for reprogramming. 

**Additional context/Motivation**
The motivation behind this is that I have had a addon in the works that I have been developing for a while and every time the code gets changed I then have to go through all of my addon's files to change what has been done.

**Comment by solvedDev** [comment]
Most changes Minecraft makes are versioned behind the "format_version" property meaning that your add-on keeps working as expected. When that is not the case, you can consider writing a small compiler plugin which fixes the issue for you.

We currently have no intention to build this functionality into the core app though.

Read more on compiler plugins: https://bridge-core.app/guide/advanced/dash/index.html
