### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by FALLENKingpin** [bridge-core/editor#67]
![Screenshot_20210926-142453_Chrome](https://user-images.githubusercontent.com/91405698/134796194-8274c960-f277-4d40-84f8-3281152165f7.jpg)
Pressing the file button wont work

**To Reproduce**
1. Go to File
2. Click on 'new file
3. Observe result

**Observed behavior**
Then it lags

**Comment by solvedDev** [comment]
Fixed with v2.1.4
