### ISSUE TITLE
Wrong block autocompletion

### ISSUE THREAD

**Issue by NguyenDuck** [bridge-core/editor#670]
**Summary**
Wrong block autocompletion

**To Reproduce**

1. Import my project below to bridge
2. Create an new block with `format_version` `1.19.30`
3. Go to `components` in `minecraft:block`
4. Ctrl + Space

**Observed behavior**
Wrong block components autocompletion

**Screenshots / File Attachments**
![image](https://user-images.githubusercontent.com/83252725/196151773-5e4ec622-b0d4-4475-9a6b-3d8be36d0252.png)
https://www.mediafire.com/file/2mie8naho4sc3t6/Exnihilo_Bedrock.brproject/file

**Platform:**

-   OS: Windows 11
-   App Version: Bridge 2.3.5 & Bridge Nightly 2.3.5

**Comment by Joelant05** [comment]
Make sure you have enabled the "Holiday Creator Features" exp toggle in your project. You can do so by toggling the options in the project selection window.

**Comment by NguyenDuck** [comment]
> Make sure you have enabled the "Holiday Creator Features" exp toggle in your project. You can do so by toggling the options in the project selection window.

I definitely enabled this feature before
