### ISSUE TITLE
Why can’t I edit dialogue scene files?

### ISSUE THREAD

**Issue by Ch36** [bridge-core/editor#673]
So whenever I try to edit a dialogue scene file in bridge using prettier compactor & tree editor, it doesn’t show the correct options. After selecting an option it won’t let you progress. I have noticed similar behavior with trade tables & animation controllers.

I’m on mobile chrome browser.
Using bridge 2.3.5

Video:
https://user-images.githubusercontent.com/114157891/196200856-6b8846a9-91f8-4b89-a99d-d3f015f64a09.MOV

**Comment by solvedDev** [comment]
Fix will be available shortly on our nightly build: https://nightly.bridge-core.app/
