### ISSUE TITLE
Updating to 2.3.5 broke the "Templater" extension

### ISSUE THREAD

**Issue by Corosauce** [bridge-core/editor#674]
**Summary**
Updating to 2.3.5 broke the "Templater" extension that injects code into files

**To Reproduce**

Install the Templater extension by Tschipp

have a BP setup to test

1. put this file named despawnable.json into folder location entities/templates/ : [https://gist.githubusercontent.com/Corosauce/a278e3bd91000a1f4cda43de6265e686/raw/1261d49f47377ed55089e3745be963ff1b95277a/despawnable.json](https://gist.githubusercontent.com/Corosauce/a278e3bd91000a1f4cda43de6265e686/raw/1261d49f47377ed55089e3745be963ff1b95277a/despawnable.json)
2. put this entity json into entities folder: [https://gist.githubusercontent.com/Corosauce/bd6ec84c6b5b9bddc7cfc88ff36d17a9/raw/e72d8315e8b9bdd21d46851a3ac5309bdce06093/gistfile1.txt](https://gist.githubusercontent.com/Corosauce/bd6ec84c6b5b9bddc7cfc88ff36d17a9/raw/e72d8315e8b9bdd21d46851a3ac5309bdce06093/gistfile1.txt)
3. save the file so the compile runs
4. see observed results below

**Observed behavior**
[https://gist.githubusercontent.com/Corosauce/4c72349148df30ce8917d1544ffffde3/raw/00affe66d2c0fed748e5c15eb1e9a9ce5fcd171c/gistfile1.txt](https://gist.githubusercontent.com/Corosauce/4c72349148df30ce8917d1544ffffde3/raw/00affe66d2c0fed748e5c15eb1e9a9ce5fcd171c/gistfile1.txt)

Missing template injections into component groups and events, see expected behavior to compare
**Expected behavior**
[https://gist.githubusercontent.com/Corosauce/e958b19b6c6b2cc6c5935bd7a7bc942a/raw/d83c591fdf177683186c3b98d1d0cc0d16cee6f1/gistfile1.txt](https://gist.githubusercontent.com/Corosauce/e958b19b6c6b2cc6c5935bd7a7bc942a/raw/d83c591fdf177683186c3b98d1d0cc0d16cee6f1/gistfile1.txt)

Note how it has json code injected into component groups and events, this is missing in observed behavior

**Platform (please complete the following information):**

-   OS: Windows 10
-   App Version: 2.3.5

**Additional context**
Worked fine in 2.3.3

**Comment by solvedDev** [comment]
Thanks a lot for the great bug report! That'll help me a lot fixing the issue :)

**Comment by solvedDev** [comment]
Closed with the release of v2.6.0
