### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kaymanater** [bridge-core/editor#68]
**Summary**

**To Reproduce**
1. Go to 'three dots'
2. Click on 'new file'
4. Observe result

**Observed behavior**
when i clicked new file it did not create new file and it made all buttons go grey and unuseable
**Expected behavior**
i expected it to create a file
**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

**Platform (please complete the following information):**
 - OS:  Windows 10
 - App Version: 2.1.3]

**Additional context**

**Comment by solvedDev** [comment]
Fixed with v2.1.4
