### ISSUE TITLE
Tree Editor Deletes Raw Text Changes

### ISSUE THREAD

**Issue by Ch36** [bridge-core/editor#681]
Whenever I create a file using tree editor for example an item, And I for example add some components & events, Let’s say I need to edit one of my events or components to do multiple things on the same component or event. I would need to use the rawtext editor mode to do that, so I make my changes. Whenever I switch back to the tree editor, it deletes my rawtext changes.

**Comment by outercloudstudio** [comment]
I can not seem to reproduce this. Can you verify that this issue is still happening?

**Comment by outercloudstudio** [comment]
Closing as stale
