### ISSUE TITLE
Entity Presets

### ISSUE THREAD

**Issue by DauntingOcean44** [bridge-core/editor#684]
We need every mob in the entity presets option.

In bridge v1, when you choose to make a new entity, you can choose from any mob in the game (besides new ones like the Warden, because v1 does not get updated anymore).

In bridge v2, you only have a couple of options, like zombie pigmen or a ghast, I guess? Where are essentials like zombies, creepers, and skeletons? Am I missing something?

**Comment by solvedDev** [comment]
Your mixing up bridge. v1's file templates and presets. 
bridge. v2 no longer has native support for file templates as those blew up the app size considerably but you can install & setup the official "Vanilla Pack Viewer" extension which allows you to import any vanilla file into your project with just a few clicks.
