### ISSUE TITLE
'run_command' field has no auto completion in entity events

### ISSUE THREAD

**Issue by xxyz30** [bridge-core/editor#691]
Minecraft support `run_command` field in entity `events` field.
but bridge has no suggestion about this.
eg:
![图片](https://user-images.githubusercontent.com/81208875/198862744-6629c638-f9e2-4392-be10-dc5f7a112383.png)
![图片](https://user-images.githubusercontent.com/81208875/198862809-a61919fd-5e1c-4cd8-8e79-a24541d1e4d6.png)

in game:
![图片](https://user-images.githubusercontent.com/81208875/198862776-7a18bf47-9a10-4235-a9ad-384aee253cee.png)
![图片](https://user-images.githubusercontent.com/81208875/198862783-794f1bcf-d67c-4956-93f0-99fe70d32803.png)

**Comment by Joelant05** [comment]
Your entity's `format_version` must be 1.16.100 or greater for bridge to suggest this field

**Comment by xxyz30** [comment]
> format version is 1.18.0

![图片](https://user-images.githubusercontent.com/81208875/200207272-711741f5-9212-431b-a4c5-ab0239f27dbd.png)
