### ISSUE TITLE
How to add bug fixes to .bridge v2?

### ISSUE THREAD

**Issue by WaffleWWolfer** [bridge-core/editor#706]
I am having a bug issue that has been resolved, but I'm unsure how to apply the fix to .bridge v2. Where do I add the files that I have downloaded? Is it an extension or does it replace existing files? Is there a tutorial?

**Comment by solvedDev** [comment]
Are you talking about a bug within bridge. v2? Updates are applied automatically upon restarting the app. You can check your version number within the top right corner on desktop and by clicking on the bridge. logo inside of the sidebar on mobile.

Additionally, there's also an update icon inside of the sidebar that you can click to restart the app for an update when it's available.
