### ISSUE TITLE
ERROR: Maximum call stack size...

### ISSUE THREAD

**Issue by Mardz38** [bridge-core/editor#734]
**Summary**
Autofill refuses to work and **Maximum call stack size,,,** error is spammed.

**To Reproduce**
Make an extremely large .json file (player for example).
After approximately 4000 lines the bug occurs.

**Observed behavior**
Autofill refuses to work and **Maximum call stack size...** error is spammed.
**Expected behavior**
The editor should work perfectly fine with no issues.

**Screenshots / File Attachments**
![image](https://user-images.githubusercontent.com/108638065/202021022-e885418f-cb0f-4858-874a-b20a1fbd3c5a.png)
![image](https://user-images.githubusercontent.com/108638065/202021086-ca17a3d6-13dc-46fb-863c-4285696ecd2c.png)

**Platform:**

-   OS: Windows 10
-   App Version: v2.4.0 (Main and Nightly)

**Comment by solvedDev** [comment]
I've tried reproducing your issue on both Windows and MacOS with files larger than 100k lines of code and I cannot reproduce your problem. Can you open the dev console and click on the blue link inside of the console next to your error?
Afterwards, click on the "{}" icon at the bottom of the view. This should format the file. Once you've done that, can you send me a screenshot of which lines of code are highlighted in red (where the error happened).

**Comment by solvedDev** [comment]
Closing because of missing reproduction and reporter inactivity

**Comment by Mardz38** [comment]
> I've tried reproducing your issue on both Windows and MacOS with files larger than 100k lines of code and I cannot reproduce your problem. Can you open the dev console and click on the blue link inside of the console next to your error? Afterwards, click on the "{}" icon at the bottom of the view. This should format the file. Once you've done that, can you send me a screenshot of which lines of code are highlighted in red (where the error happened).

I don't know how to open the console. Formatting the file doesn't seem to do anything and there's nothing highlighted in red.
