### ISSUE TITLE
Generator script compiling to wrong location

### ISSUE THREAD

**Issue by pascal541** [bridge-core/editor#735]
**Summary**
I have multiple generator scripts inside different locations. They both add files to a relative location, using a collection: ```collection.add(`./${gear}.mcfunction`, command)```. The problem is that one of the scripts is using the relative location of another script, resulting in the files being compiled to the wrong folder.

**To Reproduce**

1. Create at least two different generator scripts in different folders
2. Use createCollection() and add files to a relative location inside the script
3. Compile the project

**Observed behavior**
Files are being compiled to the wrong folder
**Expected behavior**
Files to compile to their relative folder

**Platform (please complete the following information):**

-   OS: Windows 10
-   App Version: v2.4.0

**Additional context**
Using the standalone compiler (https://github.com/bridge-core/deno-dash-compiler) v0.4.2 and running `dash build`

**Comment by solvedDev** [comment]
Do these files cross-import each other or are they completely independent?

**Comment by pascal541** [comment]
They are independent. One thing to note, they both use the same name for the collection.

**Comment by solvedDev** [comment]
Currently working on fixing #489, I'll try to reproduce & fix your issue right after
