### ISSUE TITLE
Missing auto-completions inside of tree editor

### ISSUE THREAD

**Issue by kaymanater** [bridge-core/editor#76]
**Summary**
when it doesn't show options
**To Reproduce**
1. Go to 'add object or add value'
2. Click on 'arrow to bring up options'
4. Observe result

**Observed behavior**
no options show up 
**Expected behavior**
options to show up

**Screenshots / File Attachments**

**Platform (please complete the following information):**
 - OS: [e.g. Windows 10]
 - App Version: [e.g. 0.13.3]
![Screenshot (2)](https://user-images.githubusercontent.com/91458323/136647485-2541f7c3-2fbb-4f0a-98d2-038f6eb88098.png)

**Additional context**

**Comment by solvedDev** [comment]
I can no longer reproduce the issue. Feel free to reopen if you can still have issues on the latest nightly build.
