### ISSUE TITLE
Move directory zipping/unzipping to Rust

### ISSUE THREAD

**Issue by solvedDev** [bridge-core/editor#764]
https://github.com/zip-rs/zip

**Comment by outercloudstudio** [comment]
This increases speed of unzip by ~20%. The main bottleneck is transferring the data from rust to js after unzipping. Possibly a more integrated solution into the importers could get this faster by preventing the actual file data from being transferred.

**Comment by outercloudstudio** [comment]
resolved in (bd2bff0008216f2c550d4fad6b91ecfa7190ccff) and (965cd7052dcf31d899b4b19a029171ac89d1e1ad)
