### ISSUE TITLE
Tauri: Support real file watching

### ISSUE THREAD

**Issue by solvedDev** [bridge-core/editor#765]
Allow bridge. to listen for changes to a project's file (on tauri builds) so we can automatically recompile externally changed files. Requires a Rust implementation

**Comment by outercloudstudio** [comment]
Was able to get detecting changes in project working and the triggering a refresh, however any changes made in the editor also triggers a refresh, so that needs to be handled.

**Comment by outercloudstudio** [comment]
This works now. I just need to do more testing to make sure that there isn't any conflicts.

**Comment by outercloudstudio** [comment]
Now implemented at #1000. Just need some more testing.

**Comment by outercloudstudio** [comment]
I believe this is mostly stable now.
