### ISSUE TITLE
Validate Commands

### ISSUE THREAD

**Issue by solvedDev** [bridge-core/editor#77]
**TODO**
- [x] extract validating a single line to its own function
- [x] additional values schema
- [x] is optional
- [x] selector
- [x] blockState
- [x] scoreData
- [x] jsonData
- [x] translation keys

Notes on block data:
in the format ["long string" : number | "long string", ... ]

Link to mc function data for ease of access [here](https://github.com/bridge-core/editor-packages/blob/main/packages/minecraftBedrock/language/mcfunction/main.json)

**Comment by Yasserpro312** [comment]
This is a needed features

**Comment by outercloudstudio** [comment]
> This is a needed features

The base of this feature should be available on nightly already, so if you have any feedback, post it here.

**Comment by outercloudstudio** [comment]
I'm going to remove the file action for this as it does not seem polished enough for me. However the validator should work for future integration into validating functions of like funciton files and commands in json files.

**Comment by outercloudstudio** [comment]
I plan on redoing the validator with my updated code knowledge and have it integrated with the editor to show the warnings in the text instead of a separate window

**Comment by solvedDev** [comment]
This would be awesome 👏

**Comment by solvedDev** [comment]
We should look into using our existing command schemas & parser for the feature this time

**Comment by outercloudstudio** [comment]
Definitely. This might tie into supporting the new execute command. Would this have to detect the version and change the execute command parsing or should it stick to only the new execute syntax?

**Comment by solvedDev** [comment]
We actually already have the tech in place to change how a command parses only with JSON files. We also already have functions which can be called to get which values are valid within a certain part of a command so this is all about connecting the already existing data to Monaco's diagnostic system

**Comment by outercloudstudio** [comment]
Alright that should make my life much easier! 👍

**Comment by outercloudstudio** [comment]
Would this be defined in the McFunction.ts file in languages?

**Comment by solvedDev** [comment]
Yes, our MoLang validations are terrible rn because we just highlight the whole file but you can take a look at how to implement the "validate" method there: https://github.com/bridge-core/editor/blob/main/src/components/Languages/MoLang.ts

**Comment by outercloudstudio** [comment]
I think I got a much better idea after looking at the Molang language file. [here](https://github.com/bridge-core/editor/blob/main/src/components/Languages/MoLang.ts)

**Comment by outercloudstudio** [comment]
Lol I posted this right as you posted the message.

**Comment by outercloudstudio** [comment]
Just two more features left! 🥳
