### ISSUE TITLE
| URGENT | Bridge Fails to compile and you can not set com.mojang

### ISSUE THREAD

**Issue by outercloudstudio** [bridge-core/editor#783]
**To Reproduce**
1. Open a project
2. Set the com.mojang

**Observed behavior**
Upon attempting to set the com.mojang folder, an error is thrown.
**Expected behavior**
The com.mojang folder should be set and the project should be compiled.

**Screenshots / File Attachments**
Upon setting com.mojang:
![image](https://user-images.githubusercontent.com/60296487/207205307-0f3934bc-de46-4c89-8ad8-971742320705.png)

**Platform (please complete the following information):**

-   OS: Windows 10
-   App Version: 2.5.1 PWA (Stable) and 2.5.2 PWA (Nightly)

**Comment by solvedDev** [comment]
Gonna close this because I think this is "just" Chrome and Edge blocking access to the com.mojang folder just like we have expected them to do.
