### ISSUE TITLE
Bridge native does not create animation for custom components

### ISSUE THREAD

**Issue by outercloudstudio** [bridge-core/editor#784]
**Summary**
When a custom component attempt to dynamically create an animation, no animation is created, however, the animation data is added to the entity.

**To Reproduce**
1. Create a project
2. Create an entity
3. Create a custom component that creates a animation
4. Assign that custom component to the entity
5. Compile and observer no animation saved

**Platform (please complete the following information):**

-   OS: Windows 10
-   App Version: 2.5.0 (Native)

**Additional context**
Especially important because of this bug #783

**Comment by solvedDev** [comment]
I've just tried to create a minimal reproduction and everything appears to be working as expected. I found out that after adding custom components to the project for the first time, they won't compile until the app is restarted though. I'll fix that for the next bridge. release

**Comment by outercloudstudio** [comment]
This seems to be working perfectly fine for me now. Not sure what the problem was.
