### ISSUE TITLE
drag and drop dosen't works

### ISSUE THREAD

**Issue by Velakut** [bridge-core/editor#793]
**Summary**
The drag and drop function of windows dosen't work for add or move objects or code

**To Reproduce**
Try to move a line of code or add a file from the file manager

**Observed behavior**
When trying to move an object from the editor, a forbidden symbol appears. When I try to add a file from the file explorer it judt dosen't happen.
**Expected behavior**
When i tried to move an object from a place it should take the position that I indicate. When I drag a file to the window, the program should be able to read it.

**Platform:**

-   OS: Windows 10
-   App Version: 2.5.0

**Comment by ExcitedName** [comment]
This is also happening when trying to rearrange open tabs in the editor of the native app.
OS: Windows 10 & 11 (I checked on both of my PCs)
App Version: 2.5.0

**Comment by solvedDev** [comment]
> This is also happening when trying to rearrange open tabs in the editor of the native app. OS: Windows 10 & 11 (I checked on both of my PCs) App Version: 2.5.0

Also fixed by PR #800
