### ISSUE TITLE
com.mojang it doesn't matter in the app 

### ISSUE THREAD

**Issue by hardlovedev** [bridge-core/editor#794]
hi solveddev I have a new machine with bridge v2 web but when trying to synchronize with com.mojang the browser says it cannot import the folder because it contains system files, how can I solve this?

sorry for the translator english. (translator)

**Comment by solvedDev** [comment]
Chrome and Edge sadly broke native com.mojang syncing for our PWA with their latest update. The solution is to use [our native app](https://bridge-core.app/guide/download/) and we have update the com.mojang syncing setup steps accordingly with v2.5.2 which is rolling out right now
