### ISSUE TITLE
the Windows version is slow

### ISSUE THREAD

**Issue by hardlovedev** [bridge-core/editor#797]
today I tested the native Windows version, it looks very promising but I noticed some strange things: 

1 there is no way to drag drop.

2 when saving a file (it's very slow compared to the web extension version).

 the most positive point in my opinion is that there is a way to open the folder of a certain file within the context menu.

-   OS: [e.g. Windows 10]
-   App Version: [e.g. 2.5.2]

**Comment by solvedDev** [comment]
Closing in favor of #799 (this report has a bit more detail). Thanks for reporting the bug!
