### ISSUE TITLE
Large projects cause huge lag upon saving a file from within the native bridge editor (possibly recompiling when saving)

### ISSUE THREAD

**Issue by Mcjiprock** [bridge-core/editor#799]
**Summary**
Whenever I am working on a large project talking about 500+ files/folders Bridge lags for about 10 seconds when saving the file I am working on. This didn't happen with this exact project when I was working on it yesterday using the web version. I seems to recompile the entire project instead of just saving the file. However, I am not sure that is actually the case for the lag.

**To Reproduce**
Load up a huge project ca. 500+ files maybe 1000+ to be sure. with a decent amount of these files being over 200 lines. 

Then edit a file (json in my case didn't check on other files but I do assume the same result for those.) 

Save that file (ctrl+s) 

Observe the lag and the loading animation with 2 gears in the left sidebar.

**Observed behavior**
Extremely bad performance/lag and possible recompiling of the project
**Expected behavior**
Just saving the file without any noticable lag

**Screenshots / File Attachments*
![image](https://user-images.githubusercontent.com/28510997/208266196-15c57b85-2b86-45ca-bb71-9a9baf8b734f.png)

**Platform (please complete the following information):**

-   OS: Windows 10 (i7 8core, 16gb ram)
-   App version: bridge. v2.5.2

I can sadly not send the project along for testing purposes because its not public (yet).

**extra info**

The project has both a behavior and resource pack, it is linked up to git, I had no extensions enabled. There don't seem to be other problems happening due to this bug.

**Comment by Mcjiprock** [comment]
I just noticed this might be a duplicate with the bug report Hardlovedev made a few hour ago however I am leaving this one open anyways because it goes into detail about the problem, compared to just saying the files save somewhat slow.

**Comment by solvedDev** [comment]
Can you open the compiler logs and take a look at how many files dash compiled?

**Comment by Mcjiprock** [comment]
![image](https://user-images.githubusercontent.com/28510997/208266705-ce3627f6-ba05-430a-95da-b818f6d8c2de.png)
One. however It does give an error message. Although this particular one doesn't affect the performance I think.

Don't mind the censoring, gotta do that for the nda.. :P

**Comment by Mcjiprock** [comment]
Yea the error was just a typo I made a min ago.

**Comment by solvedDev** [comment]
Hmm.. I wonder what is taking so long then. 🤔

**Comment by Mcjiprock** [comment]
A few more details: Restarting the watch mode takes about 14 seconds on this project. Saving the file (with no changes made for testing purposes) about 8 seconds so there is a clear difference between those two. In both cases the editor lags. However in the first case that is not unexpected.
