### ISSUE TITLE
Settings in native app not saving

### ISSUE THREAD

**Issue by ExcitedName** [bridge-core/editor#805]
Summary
None of the settings are being saved after closing  and reopening the native app.

1. Go to 'Projects'
2. Click on 'Settings'
3. Change any setting
4. Close the native app
5. Open the native app
6. Review setting change

-   OS: Windows 10
-   App Version: Not sure what version the native app is. Can't find it in the software.

**Comment by ExcitedName** [comment]
I tested this 5 times before reporting. As soon as I report the bug it stopped. Sorry to waste your time.

**Comment by ExcitedName** [comment]
It happened again. I honestly can't explain how to reproduce it. It seems to be completely random. Sorry for the back and forth.

**Comment by solvedDev** [comment]
No worries, some bugs cannot be reliably reproduced.
Can you tell me which specific settings you changed (e.g. settings which require an app reload)?

**Comment by ExcitedName** [comment]
The settings didn't reset when I started bridge. today. I believe these are the settings I changed.
Editor Tab:
-Bracket Pair Colorization
-Keep Tabs Open
-Show Array Indices

General Tab
-Open Links In Default Browser

Projects Tab
_Default Author - added my name
-Add "Generated With" - off

Sidebar
-Shrink Sidebar Elements
-Siderbar Size - small
-Unchecked
--Choose Project

**Comment by outercloudstudio** [comment]
I'm unable to reproduce this at the moment as well. Has this happened again to you recently?

**Comment by ExcitedName** [comment]
No, I have not had it happen recently. Sorry, I should have closed this issue.
