### ISSUE TITLE
Tabs changing location after closing app

### ISSUE THREAD

**Issue by ExcitedName** [bridge-core/editor#806]
Summary:
Tabs invert their order upon closing and launching the app.

To Reproduce:

1. Open multiple files
2. Arrange tabs in desired order
3. Close app with tabs still open
4. Launch app
5. Observe result

Observed behavior:
Tabs invert their order

Expected behavior:
Tabs to maintain order

-   OS: Windows 10
-   App Version: Native app - v2.5.2?

**Comment by ThomasOrs** [comment]
Resolved in `0ff40470d79804e528fda90bf214de0592e7dcea`
