### ISSUE TITLE
Event subcategory: "run_command" may be bugged

### ISSUE THREAD

**Issue by TitaniumAce9379** [bridge-core/editor#808]
**Summary**
The "run_command" event simply doesn't work in game

**To Reproduce**
Steps to reproduce the behavior: Create an item that uses "run_command" in an event

1.  Open Minecraft
2.  Acquire Item
3. Activate event
4. Observe result

It just doesn't work, no errors or anything
I wanted to teleport a player and such but it failed to

-   OS: Android, and Windows 10
-   App Version: 1.19.51

**Comment by solvedDev** [comment]
If you have activated experimental gameplay correctly, and the event response is still not working within Minecraft, this is a Minecraft bug and nothing on our end. 
We don't implement the API, we just provide auto-completions for it

**Comment by solvedDev** [comment]
No problem! :)
