### ISSUE TITLE
Error when opening image tabs

### ISSUE THREAD

**Issue by ExcitedName** [bridge-core/editor#813]
**Summary**
I updated the native app today to 2.5.3. The files are still visible in bridge and are still in the project folder. If I click on an image, say pack.icon, i get the error shown in the attached image.

**To Reproduce**
Update native app to 2.5.3:

1. Go to 'bridge. sidebar'
2. Click on 'pack.icon'
4. Observe result

**Observed behavior**
See attched image.

<img width="372" alt="image" src="https://user-images.githubusercontent.com/17900146/209380530-65e289ba-0ddc-4768-bd63-424972df6064.png">

-   OS: Windows 10
-   App Version: v2.5.3

**Comment by ExcitedName** [comment]
They still show up in the game as well.

**Comment by solvedDev** [comment]
Thanks for the investigation. Guess we need to send over a bit more data for the initial file load :)
