### ISSUE TITLE
Tree Editor: incorrect auto-complete when two tabs are open in split screen

### ISSUE THREAD

**Issue by Joelant05** [bridge-core/editor#826]
When two tree editor tabs are open in split screen, the auto-completions are incorrect and versioned components that should only show up in one tab show up in both.

![image](https://user-images.githubusercontent.com/64587014/209968904-037bc2f9-9841-4305-a6af-33ac976cf266.png)

**Comment by outercloudstudio** [comment]
I am unable to reproduce this. I tested this by opening two different versioned block files and they seem to work properly. Is this still a bug?

**Comment by outercloudstudio** [comment]
This is fixed in 2.8.0
