### ISSUE TITLE
Platforms which do not have a native app suggest to install the native app

### ISSUE THREAD

**Issue by ThomasOrs** [bridge-core/editor#827]
**Summary**
Mobile users are suggested to download the native app when there is not one for Mobile

**To Reproduce**

1. Go to [bridge](https://editor.bridge-core.app/) on a mobile device
2. Look at setup sheets
3. Observe issue

**Observed behavior**
A setup box that suggests com.mojang syncing can be enabled by installing bridge's native app appears.
**Expected behavior**
Platforms that do not have a native app should not tell users to install the native app

**Screenshots / File Attachments**
<img src="https://user-images.githubusercontent.com/84604286/210105726-6690e2b6-a981-46a3-b010-4a1ba6ef5075.png" width="150" >

**Platform (please complete the following information):**

-   OS: `Android 13; Pixel 6 Pro Build/TQ1A.221205.011`
-   Environment: `Chrome 108.0.5359.128`
-   App Version: `2.5.4`

**Additional context**
Issue resolved in an upcoming PR

**Comment by solvedDev** [comment]
Keeping this open until we have addressed https://github.com/bridge-core/editor/pull/828#issuecomment-1368100170

**Comment by ThomasOrs** [comment]
Partially resolved by #828.
Issue still occurs on tablet devices, see comment on #828
