### ISSUE TITLE
Renaming, Copying, Duplicating files of any sort will result in an empty file that only appears upon reloading

### ISSUE THREAD

**Issue by Mcjiprock** [bridge-core/editor#829]
**Summary**
Whenever you rename, copy/paste or duplicate a file the copied or renamed version will save as an empty file, bridge throws various errors about the files not being found or being of unknown data types (however I could only get the error I posted below when making this report, I am pretty sure I got another error as well at some point.) After pressing the refresh project button the file will appear but completely empty.

**To Reproduce**

1. Go to 'Your project'
2. Right click on 'A file for example smth.mcfunction'
3. Click on 'Rename, copy or duplicate'
4. Observe result

**Observed behavior**
The new file doesn't appear until the project is refreshed, the file is empty. The previous file stays unaffected (The last part applies mainly when renaming the file.)

**Expected behavior**
The file got either duplicated correctly with the same name with for example (_copy_1) behind it, The new file got renamed without there being a duplicate version. The new file is not empty.

**Screenshots / File Attachments**

**Timeline of me trying to duplicate an egg texture file:**

![image](https://user-images.githubusercontent.com/28510997/210133580-ed78c1b3-1d5e-4d08-a953-0356aa129f62.png)
![image](https://user-images.githubusercontent.com/28510997/210133646-68a662d1-b347-4ba7-af26-87e03e7e35cc.png)

![image](https://user-images.githubusercontent.com/28510997/210133656-36c2f57f-de35-4841-940e-24037cd5bbe0.png)
![image](https://user-images.githubusercontent.com/28510997/210133618-ced894f5-17b7-44e9-a3d9-88892935fd42.png)

![image](https://user-images.githubusercontent.com/28510997/210133682-dbb259c6-15c2-4129-91ae-03944be60f5f.png)
![image](https://user-images.githubusercontent.com/28510997/210133181-3a7e4411-c6e8-432f-a3e4-5db2a1be0adb.png)

**Platform**

-   OS: Windows 10
-   App Version: [[v2.5.4]] Native

**Additional context**
I selected a custom .Bridge root folder in settings

**Comment by solvedDev** [comment]
Thanks for the report! This has been fixed by #817 already 👍
