### ISSUE TITLE
When creating custom geometry block there is no autofill

### ISSUE THREAD

**Issue by Orbiter12** [bridge-core/editor#830]
When I create a custom geometry block, and e.g. add the "minecraft:creative_category" object, there is no autofill. There should be a "category" and "group" autofill at the bottom where you add objects and values, however there are none. This isn't the only object where that's the case. I've tried to fill it myself but it doesn't show up in my inventory. I've been trying to figure it out for so long now. Please help. I tried it with a normal block and it worked...

**Comment by solvedDev** [comment]
This is a deprecated component, the tree editor should normally not suggest it to you at all. This is a bug that we're currently trying to fix as part of #825

**Comment by solvedDev** [comment]
Closed by https://github.com/bridge-core/editor/pull/825/commits/cf1c30a2887f1bbb061dcc1f5f18c2c261e8a1fd
