### ISSUE TITLE
com.mojang location change option

### ISSUE THREAD

**Issue by hardlovedev** [bridge-core/editor#839]
I recently discovered an unofficial mcbe launcher that changes where addons/maps are installed. I did an installation myself on a non-local HD C:

the game is installed on another disk and the data is also saved on another disk.

bridge currently defaults to com.mojang from ms store/mc launcher.

if this could be changed by the end user it would be easier to use bridge in minecraft bedrock from the unofficial launcher.

I hope you understand because I'm using Google translator. XD

**Comment by solvedDev** [comment]
You can already change the com.mojang location within the compiler window:

https://bridge-core.app/guide/misc/com-mojang-syncing/index.html#setup
