### ISSUE TITLE
CustomEntitySyntax slowing down saving considerably

### ISSUE THREAD

**Issue by solvedDev** [bridge-core/editor#84]

**Comment by solvedDev** [comment]
This problem should hopefully be a bit better with our new compiler Dash because there's now a clear distinction between files we need to load to process changes to a file and files that actually change their content when a file changes.
In this case, this means that if you update an entity file, bridge. will only save the entity file & animation controller to the output directory. We still need to load all entity files though so the best solution is still to generate a single virtual animation controller for every entity

**Comment by Tschipp** [comment]
> In this case, this means that if you update an entity file, bridge. will only save the entity file & animation controller to the output directory. 

Interesting, I thought that's how it always worked

**Comment by solvedDev** [comment]
Yeah, that's how it should have always worked but previously the only difference between hot updates and full builds was with which files we call the build algorithm. (We would do a dependency trace step before the hot update). This was never intended to be a permanent compilation algorithm but the advantage of it was that -in theory- it should have been very reliable because we do more work than necessary instead of missing file update edge cases. This obviously turned out to not be the case because something broke the reliable architecture. I still suspect that the compilation problems are connected with the plugins users are running but I have no evidence to proof that.

**Comment by solvedDev** [comment]
Delaying a rewrite of the plugin to v2.3.0
