### ISSUE TITLE
Error: Error: Failed to access "bridgeFolder/extensions/MinecraftDocumentationImplementation/Docs": Directory does not existError: Error: Failed to access "bridgeFolder/extensions/MinecraftDocumentationImplementation/Docs": Directory does not exist    at window.onunhandledrejection (https://editor.bridge-core.app/assets/main-f9329ff6.js:28:2507)

### ISSUE THREAD

**Issue by sobrahedgehog** [bridge-core/editor#849]
**Summary**

**To Reproduce**

4. Observe result

**Observed behavior**
A clear and concise description of what happened
**Expected behavior**

**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

**Platform (please complete the following information):**

-   OS: [e.g. Windows 10]
-   App Version: [e.g. 0.13.3]

**Additional context**

**Comment by solvedDev** [comment]
Did this error happen upon installing the extension?
