### ISSUE TITLE
Error: NotFoundError: A requested file or directory could not be found at the time an operation was processed.Error: NotFoundError: A requested file or directory could not be found at the time an operation was processed.    at window.onunhandledrejection (https://tauri.localhost/assets/main-5acbd52f.js:28:2506)

### ISSUE THREAD

**Issue by Alexandre1424** [bridge-core/editor#851]
**Summary**
cannot link the com.mojang folder to the bridge
s
**To Reproduce**

1. Go to bridge
2. go to C:\Users\alexn\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games
3. drag the com.mojang folder to the bridge
4. Observe result

**Observed behavior**
when dragging the com.mojang folder to the bridge, an error message appears
**Expected behavior**
link the com.mojang folder to the bridge

**Platform (please complete the following information):**

-   OS: [ Windows 11]
-   App Version: [ 2.6.0]

**Comment by baroquedub** [comment]
Getting the same in v2.6.0_x64 (Win10)

Would be useful to have an option in Settings where you can just paste the file path. Would at least give users an option to add the folder without having to rely on drag and drop

**Comment by solvedDev** [comment]
Closing in favor of #850
