### ISSUE TITLE
Error: NotFoundError: A requested file or directory could not be found at the time an operation was processed.    at window.onunhandledrejection (https://tauri.localhost/assets/main-5acbd52f.js:28:2506)

### ISSUE THREAD

**Issue by Suffix30** [bridge-core/editor#852]
**Summary**
- Ran update 
- Installed vanilla pack viewer 
- Downloaded pack 1.19.40.23 BP/RP from suggested site
- Unzipped both with 7zip
- dragged and dropped BP first = ERROR
- dragged and dropped RP sec = ERROR
- reinstalled ver twice/ then tried a nightly ver, same across the board, ERROR

**To Reproduce**
try adding vanilla BP/RP  to the application 

1. Go to 'Extensions'
2. Click on 'Curated'
3. Scroll down to 'Vanilla Pack Viewer'
4. Observe result after a drag and drop of BP or RP folder

-   OS: [Windows 10]
-   App Version: [2.6.0]

**Additional context**

![Screenshot (3)](https://user-images.githubusercontent.com/49195535/211967956-616f0f4a-a92c-4b52-8cd5-cba696bcdc4f.png)
![Screenshot (4)](https://user-images.githubusercontent.com/49195535/211967995-6291a955-97a7-409b-9c26-77e63c679b60.png)
![Screenshot (5)](https://user-images.githubusercontent.com/49195535/211968022-d3f0f1fd-7bf2-4dda-ba9a-bf0f0c5a2024.png)

**Comment by Suffix30** [comment]
Fixed my issue
The only thing i did differently, I download the app from EDGE ( TOP RIGHT )
 instead of downloading it from https://bridge-core.app/guide/download/ 

even the ACCESS LINKED PACKS showed back up , so idk.  hopefully this might guided you in the other listings. 
attaches are the results . 

![Installed from EDGE](https://user-images.githubusercontent.com/49195535/212137157-10d3e8d1-c0cc-4b11-9962-42ce399b4ef7.png)
![confirm folder BP](https://user-images.githubusercontent.com/49195535/212137247-a73da720-1a16-4c9a-bfd2-d689b0a2a095.png)
![confirm folder RP](https://user-images.githubusercontent.com/49195535/212137281-b3b6d086-9634-426d-9869-dfa5b7966cc1.png)
![vanilla success](https://user-images.githubusercontent.com/49195535/212137325-6efcba7c-6299-495e-a7ce-f06d59885c67.png)

**Comment by solvedDev** [comment]
Reopening because this should work on our native build too

**Comment by outercloudstudio** [comment]
related to #917 Dropping folders appears to be bugged on the tauri build due to a bug in the browser.
