### ISSUE TITLE
Error: TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))Error: TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))    at window.onunhandledrejection (https://tauri.localhost/assets/main-5acbd52f.js:28:2506)

### ISSUE THREAD

**Issue by Arkurum** [bridge-core/editor#853]
**Summary**

**To Reproduce**

4. Observe result

**Observed behavior**
A clear and concise description of what happened
**Expected behavior**

**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

**Platform (please complete the following information):**

-   OS: [e.g. Windows 10]
-   App Version: [e.g. 0.13.3]

**Additional context**

**Comment by solvedDev** [comment]
When did that error occur?
