### ISSUE TITLE
Error: TypeError: Cannot use 'in' operator to search for 'type' in undefinedError: TypeError: Cannot use 'in' operator to search for 'type' in undefined    at window.onunhandledrejection (https://tauri.localhost/assets/main-5acbd52f.js:28:2506)

### ISSUE THREAD

**Issue by DarthDub420** [bridge-core/editor#854]
Trying to create a new type of wood gave me this error and left me on the item creation screen.

**To Reproduce**

1. Go to '+New File'
2. Click on 'Presets, Advanced, Wood Type' (I downloaded the extension previously and holiday creator features are turned on for the project)
3. Fill in all the boxes, 'Identifier', 'Display Name' and gave it 4 new png files for textures which have been tested in the first 4 texture slots and gave it the corresponding oak textures for the last 5 then click '+ Create'.
4. Observe result

**Observed behavior**
I was given this error message and left on the Create Preset window with no new files having been created.
**Expected behavior**
I expected the 'Create Preset' window to go away and a new wood type to be created and placed into my project so that I could inspect it's properties.

**Screenshots / File Attachments**

**Platform (please complete the following information):**

-   OS:  Windows 10
-   App Version: 2.6.0

**Additional context**
I've been unable to get any extensions to work to date.
![Screenshot 1_13_2023 8_55_08 AM](https://user-images.githubusercontent.com/121879832/212338004-75aa6e3e-96e3-4807-8115-928520744aed.png)
![Screenshot 1_13_2023 8_55_21 AM](https://user-images.githubusercontent.com/121879832/212338041-fc24daa2-843b-492c-99fa-38db86e80221.png)
![Screenshot 1_13_2023 8_55_45 AM](https://user-images.githubusercontent.com/121879832/212338073-92ad3dcf-b311-441e-9955-239dcbaeaad2.png)

![Screenshot 1_13_2023 8_55_56 AM](https://user-images.githubusercontent.com/121879832/212338164-2161d5b9-9061-42e4-83c9-22e0416a2d49.png)

**Comment by solvedDev** [comment]
This is an extension so we're not responsible for its behavior. @Gekocaretaker in case you are interested
