### ISSUE TITLE
Renaming a file from testFile to testfile will not automatically update the file name in the development beviorpacks folder

### ISSUE THREAD

**Issue by Mcjiprock** [bridge-core/editor#858]
**Summary**
Renaming a file when only changing capital letter to non capital letters will not automatically update the file name in the development_beviorpacks folder

**To Reproduce**

1. Create a file called "testFile" (.mcfunction)
2. Rename it to "testfile" (.mcfunction)
3. Check the com.mojang folder and the .bridge projects folder
4. Observe result, the file in com.mojang will still be called "testFile" and the file in .bridge will be called "testfile"

**Observed behavior**
The files at both locations had different names
**Expected behavior**
Both files should be named "testfile"

**Platform:**

-   OS: [e.g. Windows 10]
-   App Version: Native 2.6.0

**Comment by solvedDev** [comment]
Thanks for the report!
Windows does not differentiate between files with capital letters and lowercase letters. This is just how the operating system works
