### ISSUE TITLE
functions

### ISSUE THREAD

**Issue by LUNAxTOKITO** [bridge-core/editor#862]
i made 5 functions but when i load in there is only 3. 2 of the main ones don't exist in game but do inside the actual project idk wth is wrong with it

**Comment by ExcitedName** [comment]
Most likey a syntax error or typo within the function file. It happens to me a lot. Whenever there is an error with a .mcfunction file it won't load it at all.

**Comment by LUNAxTOKITO** [comment]
there doesn't seem to be any issue but ill try check it all. thanks so much for taking the time to help me man!

**Comment by LUNAxTOKITO** [comment]
I just checked it and nothing was wrong i loaded it up and 2 of my functions are still missing (btw i meant 2 not 3. 2 lol) here is the lines of code that won't work

1st function (chakra0)
scoreboard players set @a[scores={level=0}, scores={chakra=51..}] chakra 50
scoreboard players set @a[scores={level=0}, scores={chakra=..-1}] chakra 0

second function (bars)
titleraw @a actionbar {{"rawtext":[{"text":"chakra: "},{"score":{"name":"*","objective":"chakra"}},{"text":         "level: "},{"score":{"name":"*","objective":"level"}}

i already have both chakra and level objectives made but it won't work for those 2 here are the other 3

1st one (level_system)
scoreboard objectives add level dummy level
scoreboard players add @a level 0

2nd one (level0)
effect @a[scores={level=0}] speed 10000000 0 true
effect @a[scores={level=0}] jump_boost 100000000 0 true

3rd one (chakra_system)
scoreboard objectives add chakra dummy chakra
scoreboard players add @a chakra 0

thats all of them

**Comment by LUNAxTOKITO** [comment]
btw all the capital A's are auto correct the "A" is "a"

**Comment by LUNAxTOKITO** [comment]
omg thank you so much oi managed to fix it with your advice and it works now like holy sh!1 im so happy you posted on this your the man bro!!!

**Comment by ExcitedName** [comment]
Glad I could help. In the future try commenting out all commands except one at a time and run the file manually. That way you can identify the point of failure. it's a pain, but it tends to be the fastest way to figure out the error.

**Comment by LUNAxTOKITO** [comment]
yeah thanks so much man your an absolute god lol
