### ISSUE TITLE
Custom Components don't get compiled on normal save

### ISSUE THREAD

**Issue by Tschipp** [bridge-core/editor#866]
**Summary**
Whenever a file is saved, its custom components are not compiled. A restart of watch mode is needed.

**To Reproduce**
Make an entity file, add a custom component, save the file. The component will not be compiled.  
Can provide a test project if needed

As far as I can tell, neither the component nor the entity file make a reference to eachother in the .dash.development.json:
```json
    {
        "isVirtual": false,
        "filePath": "projects/Test Project 2/BP/components/entity/bridge/addAnim.js",
        "aliases": [
            "entityComponent#bridge:event_animation"
        ],
        "requiredFiles": [],
        "updateFiles": []
    },
    {
        "isVirtual": false,
        "filePath": "projects/Test Project 2/BP/entities/test.json",
        "aliases": [
            "bridge:test"
        ],
        "requiredFiles": [
            "projects/Test Project 2/BP/commands/**/*.[jt]s",
            "projects/Test Project 2/BP/commands/*.[jt]s",
            "projects/Test Project 2/BP/scripts/molang/**/*.[jt]s",
            "projects/Test Project 2/BP/molang/**/*.molang",
            "projects/Test Project 2/RP/molang/**/*.molang"
        ],
        "updateFiles": [
            "projects/Test Project 2/BP/animations/bridge/1a7ca0336debc1d65377f7bdb1946dceb7ab2e2f.json",
            "projects/Test Project 2/BP/animation_controllers/bridge/1a7ca0336debc1d65377f7bdb1946dceb7ab2e2f.json"
        ]
    }
```

-   OS: Windows 10
-   App Version: 2.6.0 native build

**Comment by ExcitedName** [comment]
@solvedDev This also happens with custom commands. Would you like me to open a seperate issue for it?

**Comment by Corosauce** [comment]
I've confirmed this is definitely still happening, I have to do a full restart of watch mode every time I tweak any file with a custom component.

**Comment by Tschipp** [comment]
This PR should fix the issue: https://github.com/bridge-core/dash-compiler/pull/2

**Comment by DokaebiYe** [comment]
This issue is currently confirmed that it's still exist.
