### ISSUE TITLE
Block Rotation

### ISSUE THREAD

**Issue by Suffix30** [bridge-core/editor#867]
**UPDATE TEXTURE**
Trying to add  rotation to a ( custom block geo ) seems to conflict the rendering.

- bridge:rotate_y_on_place
- bridge:log_rotation_on_place
- bridge:rotate_on_place
- minecraft:rotation
 
All listed above when applied are unable to display the ( .geo w/ texture ) the way its suppose to in game.

**To Reproduce**
- Add any of the listed options above to a custom_block.geo

1. Go to 'BP'
2. Click on / blocks / <custom_block>.json '
3. Scroll down to 'components'
4. Add any rotation option provided
5. Observe result in game

**Observed behavior**
 - UPDATE block displayed
 
**Expected behavior**
 - should be able to place the block facing me from any direction

**Screenshots / File Attachments**
Attached are 2 screenshots of with and without rotation. the end result is the same on every option.
![Rotation ERROR](https://user-images.githubusercontent.com/49195535/215204379-fb30b997-fcaa-4e87-bf69-7127dc8cd688.png)
![No Rotation ERROR](https://user-images.githubusercontent.com/49195535/215204422-fdbed465-5784-4c3b-b424-0e05dacc9f9a.png)

-   OS Name	Microsoft Windows 10 Pro Version	10.0.19045 Build 19045 
-   App Version: [v2.6.0]

**Comment by ThomasOrs** [comment]
The component requires features removed in the format version you are using. Block events don't exist in 1.19.50 block format.

**Comment by outercloudstudio** [comment]
In the future I recommend asking for addon help in the bridge discord.
