### ISSUE TITLE
Error: ReferenceError: createUrl is not definedError: ReferenceError: createUrl is not defined    at window.onunhandledrejection (https://editor.bridge-core.app/assets/main-5a0ecece.js:28:2507)

### ISSUE THREAD

**Issue by fgclue** [bridge-core/editor#868]
**Summary**
It just gives me this error... the only extension I have is MCBE essentials

**To Reproduce**
It just happend randomly. I never used createURL in my code. 

**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

**Platform (please complete the following information):**

-   OS: chromeOS 109.0.5414.94 64-bits
-   App Version: 2.6.0

**Additional context**
It just gave me this error out of nowhere.
![image](https://user-images.githubusercontent.com/87581499/215284433-edeebcb3-8d85-411e-9443-483f846b82cb.png)

**Comment by outercloudstudio** [comment]
You'll need to provide more information of what happened just before this error message appeared. What action's did you do that might have cause this error?

**Comment by ThomasOrs** [comment]
Closing as stale
