### ISSUE TITLE
Drag and Drop breaks app

### ISSUE THREAD

**Issue by ghost** [bridge-core/editor#869]
If you try to rearrange a node, it snaps back to its original position and the app straight up breaks.

1. Go to any file in the tree editor
2. Click and drag a node above or below another one

The node goes back to originally where it was

I exxpected the node to move to another slot

-   OS: Windows 11
-   App Version: v2.6

**Comment by outercloudstudio** [comment]
I am able to reproduce this. Thanks for reporting 👍
