### ISSUE TITLE
Texture or Rendering Issues?

### ISSUE THREAD

**Issue by VvSeanGTvV** [bridge-core/editor#873]
So I don't know if this is a bug to the editor or a bug to blockbench, because I made a custom texture and custom geometry block for bedrock, upon loading it works fine but when I added a new block and texture, the first custom texture got bugged out...
![Screenshot_20230207-102100_Gallery](https://user-images.githubusercontent.com/64627966/217347573-5e658e79-2fbe-4f15-a4bb-243d10032788.jpg)

**To Reproduce**
1. Make first custom geometry, and custom texture
2. Load up minecraft with the custom texture & geometry
3. Go back and make a secondary texture & geometry
4. Load it up again and see if there is an issue.

**Disclaimer**
It may not reproduce the same issue that I am experiencing!

**Expected behavior**
I expected that the texture was gonna look like from the preview but it ended up merging straight from lava texture from Minecraft

-   OS: **Windows 10**
-   App Version: **2.6.0 - "Coral"**

**Additional context**
None...

**Comment by outercloudstudio** [comment]
You should ask for help in the bridge discord server. Generally these issues are for bugs with bridge or feature requests.
