### ISSUE TITLE
 Reinstall Bridge

### ISSUE THREAD

**Issue by Caue569** [bridge-core/editor#874]
**Summary**
Reinstalling bridge is a tool similar to reloading bridge but it deletes all files and leaves the brigde as new, thus also erasing errors generated by the users themselves.

**Alternatives/Considerations**
You will also need a backup button for projects that creates a zip with all projects in brproject (if the user has more than one)
and also warnings (at least two)
to avoid unintentionally restarting (maybe even three because losing all projects is no joke) the backup can also save the extensions in a new type of file (for example: .brextension,
.brext, brplugin and brplg)
this tool will be in the tools tab.

**Additional context/Motivation**
This feature will only be for the native app
and this is also a good alternative in case a user creates an error exclusively in your application making it impossible to solve it (in case he does not know the real cause of the error).

**Comment by ThomasOrs** [comment]
On the native app you can already uninstall and reinstall it as you wish.
