### ISSUE TITLE
Error: TypeError: t.getParent is not a functionError: TypeError: t.getParent is not a function at window.onunhandledrejection (https://tauri.localhost/assets/main-5acbd52f.js:28:2506)

### ISSUE THREAD

**Issue by Caue569** [bridge-core/editor#875]
**Summary**
Everytime i open a file this error happens.

**To Reproduce**

1. Click on file.
2. Click open file.
3. Select the file.
4. Click open file again (but only if in a project).
5. And the error happens.

**Observed behavior**
I can't see the file because it doesn't open or a new tab appears.
**Expected behavior**
Open the file and see it.

**Platform (please complete the following information):**

-   OS: Windows 10
-   App Version: v2.6.0 Native Version

**Additional context**
This error can only be mine that's why I created the page [Reinstall bridge](874)

**Comment by outercloudstudio** [comment]
I am unable to reproduce this

**Comment by outercloudstudio** [comment]
Closing as stale
