### ISSUE TITLE
Error: User aborted selecting fileError: User aborted selecting file    at window.onunhandledrejection (https://editor.bridge-core.app/assets/main-5a0ecece.js:28:2507)

### ISSUE THREAD

**Issue by Beawpng** [bridge-core/editor#877]
**Summary**

**To Reproduce**

4. Observe result

**Observed behavior**
A clear and concise description of what happened
**Expected behavior**

**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

**Platform (please complete the following information):**

-   OS: [e.g. Windows 10]
-   App Version: [e.g. 0.13.3]

**Additional context**

**Comment by Beawpng** [comment]
![Screenshot_20230212_201112](https://user-images.githubusercontent.com/125180018/218952368-da0b5766-6793-43f2-adfe-403d27e85f54.jpg)
When I want to open a document does not leave and comes out that error

**Comment by outercloudstudio** [comment]
You'll need to provide us with more context. Try filling out the information in the description.
