### ISSUE TITLE
Error: invalid zip file@https://editor.bridge-core.app/assets/main-5a0ecece.js:28:2516

### ISSUE THREAD

**Issue by Okakajp25** [bridge-core/editor#878]
**Summary**

**To Reproduce**

4. Observe result

**Observed behavior**
A clear and concise description of what happened
**Expected behavior**

**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

**Platform (please complete the following information):**

-   OS: [e.g. Windows 10]
-   App Version: [e.g. 0.13.3]

**Additional context**

**Comment by outercloudstudio** [comment]
You'll need to provide us with more context. Try filling out the information in the description.
