### ISSUE TITLE
minecraft:music_disc bugged?

### ISSUE THREAD

**Issue by TitaniumAce9379** [bridge-core/editor#881]
Whenever I create an item that uses the "minecraft:music_disc" component it doesn't show up in any creative menus nor does the item show when I use "/give". It's like the item never existed even though it shows in the files of the addon.

1. Create an item in an addon
2. Add the component "minecraft:music_disc"
3. Open minecraft and load addon.
4. Search for said Item in creative menu or using "/give" and observe

The item seems to not exist within any files even though it shows in the addon. I'd expect for the item to exist and function as a music disc would.

-   OS: Windows 11
-   App Version: Browser Editor?

**Comment by outercloudstudio** [comment]
You should ask for addon specific help in the bridge discord server. These github issues are for problems with bridge itself.
