### ISSUE TITLE
many bugs and low perfomance (powerful PC)

### ISSUE THREAD

**Issue by mateus3c** [bridge-core/editor#889]
I use V2 native PC software atm, but im getting a bit disappointed because it lags so much, like, when I click to open a file, it takes a long time to really open and show me the content of it
I know its not a problem with my PC performance because my PC is actually very powerful and can handle everything I use/play
and it gets laggier with the time, at some point I have to close and reopen to make it useable again
one bug I always face is when I open a file when it starts getting laggy and when the file I open loads its content, the content show is from a different file and every other file I open shows the same content of one single file (that can happen with any file, it depends
entities, animations, entity, animation controller, blocks, scripts, functions etc)
also sometimes this happens with the top menu while Im editing files:
![image](https://user-images.githubusercontent.com/122059128/224455796-75481000-abcd-453b-84a6-fcee0360b687.png)
it grays out and I cant really click anything
im forced to close and reopen Bridge

**Comment by outercloudstudio** [comment]
Is your project large, or are you opening a large file?

**Comment by ThomasOrs** [comment]
Closing as stale
