### ISSUE TITLE
V2 Native starts in offset windowed

### ISSUE THREAD

**Issue by ExcitedName** [bridge-core/editor#890]
**Summary**
When I launch the V2 native app, it opens windowed and offset. See images below. 

**To Reproduce**

1. Install the V2 native app
2. Launch the app
3. Observe result

**Observed behavior**
When I launch the V2 native app, it opens windowed and offset. See images below. 
**Expected behavior**
The app to open full screen.

**Screenshots / File Attachments**
![Screenshot 2023-03-10 184016](https://user-images.githubusercontent.com/17900146/224460975-278ade94-f6d9-4512-a86b-f1272b107a13.png)
![Screenshot 2023-03-10 184208](https://user-images.githubusercontent.com/17900146/224460986-b3d502e1-43ba-419a-a630-a75cb3d56f8d.png)

**Platform:**

-   OS: Windows 11
-   App Version: Native App 2.6.0
-   Default Browser: Microsoft Edge

**Comment by NguyenDuck** [comment]
Suggest Feature:
Save the bridge window location and size
Load back saved data on launch
