### ISSUE TITLE
The Extensions don't work?

### ISSUE THREAD

**Issue by domstudios** [bridge-core/editor#891]
So. I just started using Bridge V2 a little bit. I've been following tutorials and such so that I can improve. But whenever I download an extension and attempt to use it in my code. It doesn't seem to work. **Even when its activated**. I've tried deleting the extensions and redownloading them. I've even tried deleting bridge and redownloading it to no avail.

most of the code starts with '**_bridge:(insert extension name here)_**' like this one
![image](https://user-images.githubusercontent.com/127627413/224508847-28feb3f2-2aed-4de7-9fc8-dfe8334c3be0.png)

The extension is **active**, meaning that I should be able to use it in my code
![image](https://user-images.githubusercontent.com/127627413/224508863-cd130fe0-55ee-4cca-b794-4c6c8b4c836c.png)

But whenever I type 'bridge' **_nothing pops up_**
![image](https://user-images.githubusercontent.com/127627413/224508897-dfc3b51b-8c34-4e90-823f-2decd28596ad.png)

I don't know if I'm the only one having this problem. I hope its just me not knowing how the extensions work. But I do hope this either gets fixed soon. Or that I get a response telling me what to do.

**Comment by outercloudstudio** [comment]
This might be an auto completions error. Will attempt to reproduce this later

**Comment by outercloudstudio** [comment]
I am unable to reproduce this in a normal project. This could however be caused, based on the images, from opening the extensions folder?

**Comment by ThomasOrs** [comment]
Closing as stale
