### ISSUE TITLE
Ctrl tab option to make it switch between last used tabs

### ISSUE THREAD

**Issue by Corosauce** [bridge-core/editor#892]
**Summary**
Ctrl tab option to switch from the left to right behavior of tabbing, to make it instead switch between last used tab, exactly to how windows does it, how notepad++ does it, how IDEA does it etc, would go a long way towards working between a few files, making things much faster.

As a bonus, a little popup to see what file to tab to would help a lot when working with multiple files frequently, which is a thing that happens a lot with pack development.

Example pic of that from notepad++ when you are holding down ctrl after hitting tab: 
![image](https://user-images.githubusercontent.com/1238621/225678996-a75cbb0d-d2e7-4de9-9998-9a9150d7e9d6.png)

**Comment by outercloudstudio** [comment]
This has been implemented in #934
