### ISSUE TITLE
Can't export project as .mcaddon on macOS

### ISSUE THREAD

**Issue by nroshak** [bridge-core/editor#893]
**Summary**
I created a new project using bridge in browser (Firefox on MacOS). I can save it locally, but, I can't export it as .mcaddon . It hangs with "Loading..." indefinitely. In the dev console I see this error: "SyntaxError: export declarations may only appear at top level of a module". Next, I installed bridge. v2 for MacOS, recreated the project and still cannot export as .mcaddon . Same thing happens, it hangs on "Loading..." Using native bridge. v2 I can export as .brproject successfully, but it hangs trying to export .mcaddon .

**To Reproduce**

1. Install bridge. v2 for MacOS, OR, use bridge in Firefox on MacOS
2. Create a new local project called "newproject" using Resource and Behaviour packs
3. Try to export as .mcaddon
4. It hangs on "Loading..." indefinitely

**Observed behavior**
It hangs on "Loading..." indefinitely
**Expected behavior**
It should export the project as .mcaddon

**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

**Platform (please complete the following information):**

-   MacOS
-   bridge. 2.6.0

**Additional context**
This computer doesn't have MC installed on it. I couldn't find any requirement for that in the docs.

![Screen Shot 2023-03-17 at 10 02 40 PM](https://user-images.githubusercontent.com/14022050/226077554-30666c70-66c6-4a65-b85f-d293ccbdfc32.png)

**Comment by outercloudstudio** [comment]
Try using a browser other than Firefox. Chrome or edge are the recommended browsers for using bridge. The source of this error seems to be on Firefox's end at the moment due to a problem with their supporting of a certain feature. [Link to issue](https://github.com/vitejs/vite/issues/8621)
