### ISSUE TITLE
[BUG] Long Loading Time

### ISSUE THREAD

**Issue by Nubdevv** [bridge-core/editor#9]
**Summary**
When creating a new project, or making a adding extensions to bridge. it gets stuck on the loading screen, 

**To Reproduce**

1. Click on extensions or new project.

2. Click "create" tab. 

**Platform:**
 - OS: [e.g. Windows 10]
 - App Version: [e.g. 0.13.3]

**Comment by solvedDev** [comment]
Can you send me a screenshot of this issue happening?

**Comment by solvedDev** [comment]
We have just pushed a couple of changes to reduce lag upon first selecting a project/opening bridge. 
We are also working on more changes to reduce the amount of times app components have to wait on long running tasks
