### ISSUE TITLE
Error: SyntaxError: JSON5: invalid character '}' at 76:1Error: SyntaxError: JSON5: invalid character '}' at 76:1    at window.onunhandledrejection (https://tauri.localhost/assets/main-5acbd52f.js:28:2506)

### ISSUE THREAD

**Issue by LeiLeiLeiLeica** [bridge-core/editor#904]
**Summary**
When I tried to create an item from an item preset, I was asked if I could overwrite multiple files. was displayed. When I executed it, I received an error.
 
**To Reproduce**

4. Observe result

**Observed behavior**
A clear and concise description of what happened
**Expected behavior**

**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.
![スクリーンショット 2023-04-13 142838](https://user-images.githubusercontent.com/116566652/231663086-c45b70f5-b2d3-4121-9f1f-d36b3ce07a0a.png)
![スクリーンショット 2023-04-13 143135](https://user-images.githubusercontent.com/116566652/231663108-f103ba2c-823c-4f17-bcc0-1da3416b7e89.png)

**Platform (please complete the following information):**

-   OS: [e.g. Windows 10]
-   App Version: ["bridge": [
				"2.6.0"
			],
			"dash": [
				"0.10.8"
			]]

**Additional context**

**Comment by outercloudstudio** [comment]
Does this happen every time you create an item?

**Comment by outercloudstudio** [comment]
I am unable to reproduce this at the moment

**Comment by ThomasOrs** [comment]
Closing as stale
