### ISSUE TITLE
Error: Cannot read properties of null (reading 'cloneNode')TypeError: Cannot read properties of null (reading 'cloneNode')    at jy (https://tauri.localhost/assets/vendor-73f88319.js:53:52846)    at Nt._onDragStart (https://tauri.localhost/assets/vendor-73f88319.js:53:68380)

### ISSUE THREAD

**Issue by RevanMay** [bridge-core/editor#906]
**Summary**

**To Reproduce**

4. Observe result

**Observed behavior**
A clear and concise description of what happened
**Expected behavior**

**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

**Platform (please complete the following information):**

-   OS: [e.g. Windows 10]
-   App Version: [e.g. 0.13.3]

**Additional context**

**Comment by outercloudstudio** [comment]
You'll need to provide us with more context. Try filling out the information in the description.
