### ISSUE TITLE
Error: NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.Error: NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.    at window.onunhandledrejection (https://editor.bridge-core.app/assets/main-5a0ecece.js:28:2507)

### ISSUE THREAD

**Issue by SlinkierLamb** [bridge-core/editor#908]
**Summary**
I tried to import png into bridge but instead it gave me this error. This happens whenever I try to upload a png (externally) to my project. But it works while creating a file and uploading an image. This also happens with files and project files, it doesn't let me import any file into bridge.

**To Reproduce**

1. Create/Open a project.
2. Click on File (on the top, between 'Project' tab and 'Edit' tab) then click on Open File, select a file to import. OR
Click the '3 dotted menu' on any of the folders of your project, then click 'Import File', then choose any file you want to import.

**Observed behavior**
It returns "Error: NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
Error: NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at window.onunhandledrejection (https://editor.bridge-core.app/assets/main-5a0ecece.js:28:2507)" 

**Expected behavior**
The file or the png file to be imported to the project.

**Platform:**

-   OS: Android 12
-   App Version: v2.6.0

**Additional context**
I tried it on Android 11 device too, but it gives the same error. I suppose this happens with every Android devices. Please try to fix this bug as it ruins the excitement of using the application.

**Comment by outercloudstudio** [comment]
I am unable to reproduce this bug.

**Comment by ThomasOrs** [comment]
Closing as stale
