### ISSUE TITLE
web editor non functional?

### ISSUE THREAD

**Issue by Axolotl9009** [bridge-core/editor#909]
when i open editor.bridge-core.app it loads and appears to be a completely white screen. I have tried waiting for it to load, but it is always the white screen. Is there possibly a solution? I looked it up and apparently no one else has this problem. please help!!!

Pictures attached below:
![Screenshot 2023-04-24 11 13 40](https://user-images.githubusercontent.com/108891145/234081345-a1cec7c6-9a90-45fb-9403-04f91192c045.png)
![Screenshot 2023-04-24 11 13 20](https://user-images.githubusercontent.com/108891145/234081347-897a6900-e912-4990-8121-e0608580dfd0.png)

**Comment by ThomasOrs** [comment]
@Axolotl9009 can you share your these details please
OS:
Browser:
Hit `F12` or open dev tools, and then refresh the page, are there any errors in the console?

**Comment by ThomasOrs** [comment]
CLosed due to CNR and stale
