### ISSUE TITLE
File Importation Failure

### ISSUE THREAD

**Issue by Voonkoon** [bridge-core/editor#910]
**Summary**
I have encountered a bug that makes me completely Unable to import multiple files at once.

(Which mostly concerns files.)

When i tried to import particles i have made into bridge to fix them, Nothing happened, Other then two warning signs, There is one where it was written:
"Error: User aborted selecting fileError: User aborted selecting file    at window."
And another one that said:

"User Aborted Selecting File"

I thought it would just import the files normally, But seriously, As long as its two files its just hell to import them. I always have to import the files one by one.

Platform:

-   OS: Android
- App Version: Funtouch OS 12 Global

**Comment by outercloudstudio** [comment]
I am able to reproduce this. Thank you for reporting 👍
