### ISSUE TITLE
Allow To add custom item description Using components in items and blocks

### ISSUE THREAD

**Issue by anonymous-90** [bridge-core/editor#915]
**Summary**
Allow Creators to add custom item descriptions Onto their items Without the use of scripts

**Alternatives/Considerations**
If unable to add the Feature directly Add a template script So that creators can use It to apply custom Item descriptions to the items

**Additional context/Motivation**
The motivation is to allow New creators To add their own custom item description Without Having to know javascript or type script To do so

**Comment by outercloudstudio** [comment]
This would be an addon feature or a possible extension. Closing this as it will not be added to the editor.
