### ISSUE TITLE
Indexing Packs and Loading Auto-Completion won't finish

### ISSUE THREAD

**Issue by veedy-dev** [bridge-core/editor#916]
**Summary**
Indexing packs and loading auto-completion do not finish after creating a new project.

**To Reproduce**

1. Go to 'Project'
2. Click on 'New Project'
3. Register BP and RP as a dependency 
4. Write any project name, description, author
5. Click on 'Create'
6. the bug starts happen here

**Observed behavior**
A clear and concise description of what happened
**Expected behavior**
Indexing Packs and Loading Auto-Completion should've finished right away after creating a new project

**Screenshots / File Attachments**
![image](https://github.com/bridge-core/editor/assets/38901140/bbc4ef42-005b-4ddd-8ce6-1b3413d5a25b)

**Platform (please complete the following information):**

-   OS: Windows 11 22H2
-   App Version: 2.6.0

**Additional context**
I don't have any plugins installed beside compact prettier

**Comment by outercloudstudio** [comment]
I can confirm this bug exists. It only happens with compact prettier enabled. To fix this just uninstall the compact prettier extension. Later I'll look to see if I can fix the extension.
