### ISSUE TITLE
Error: NotFoundError: A requested file or directory could not be found at the time an operation was processed.Error: NotFoundError: A requested file or directory could not be found at the time an operation was processed.    at window.onunhandledrejection (https://tauri.localhost/assets/main-5acbd52f.js:28:2506)

### ISSUE THREAD

**Issue by czarryano27** [bridge-core/editor#917]
Tried adding a new vanilla pack to bridge native app using drag and drop and it pops up this error.
I also tried adding a Folder , it somewhat links it but it doesnt show.

(Error: NotFoundError: A requested file or directory could not be found at the time an operation was processed.
Error: NotFoundError: A requested file or directory could not be found at the time an operation was processed.
    at window.onunhandledrejection (https://tauri.localhost/assets/main-5acbd52f.js:28:2506))

 Tried doing the same drag and dropping the files in the web app and it works. I just prefer to use the native app.

**Comment by outercloudstudio** [comment]
I can confirm this. Thanks for reporting 👍

**Comment by outercloudstudio** [comment]
This appears to be a browser bug out of bridge's control. I will continue searching for a work around.

**Comment by outercloudstudio** [comment]
I might be able to work around this by listening to a tauri file drop event instead of the browser drop event.

**Comment by outercloudstudio** [comment]
See: https://github.com/tauri-apps/tauri/discussions/4736#discussioncomment-3204540
