### ISSUE TITLE
App Wont open

### ISSUE THREAD

**Issue by Burgers234** [bridge-core/editor#918]
**Summary**
The App (when i double click it on desktop) wont open, and loads and displays the blue circle.
**To Reproduce**

1. Go to the download
2. Click on the app twice after download
3. Observe result

**Observed behavior**
It opens, but doesnt show anything in task manager, nor does GUI show up...
**Expected behavior**
I shouldve been able to use bridge.

**Platform (please complete the following information):**

-   OS: Windows 10

**Comment by outercloudstudio** [comment]
What do you mean by displaying a blue circle? Like a loading wheel on the mouse?
