### ISSUE TITLE
JSON UI binding_name_override gives an incorrect warning

### ISSUE THREAD

**Issue by Fluffyalien1422** [bridge-core/editor#920]
**Summary**
In JSON UI code using the `binding_name_override` property with a non-hardcoded binding makes bridge. show a warning that the value is not accepted. This is not true, any binding name is accepted in `binding_name_override`.

**To Reproduce**

1. Make a JSON UI file
2. Add a binding to an element like this `{ "binding_name": "#hud_title_text_string", "binding_name_override": "#custom_binding" }`

**Observed behavior**
bridge. shows a warning saying the value is not accepted.
**Expected behavior**
There should be no warning.

**Platform (please complete the following information):**

-   OS: Windows 10 22H2
-   App Version: 2.6.0

**Comment by outercloudstudio** [comment]
Could you provide a minimal sample project. I am unfamiliar with JSON UI and it would greatly help me fix it if you could provide this.

**Comment by outercloudstudio** [comment]
Closing as stale.
