### ISSUE TITLE
Error: TypeError: Cannot set properties of undefined (setting '~local/projects/oh my god tki can make a function/BP/functions/addonfirst.mcfunction')Error: TypeError: Cannot set properties of undefined (setting '~local/projects/oh my god tki can make a function/BP/functions/addonfirst.mcfunction')    at window.onunhandledrejection (https://editor.bridge-core.app/assets/main-5a0ecece.js:28:2507)

### ISSUE THREAD

**Issue by TKi993qq** [bridge-core/editor#923]
**Summary**

**To Reproduce**

4. Observe result

**Observed behavior**
A clear and concise description of what happened
**Expected behavior**

**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

**Platform (please complete the following information):**

-   OS: [e.g. Windows 10]
-   App Version: [e.g. 0.13.3]

**Additional context**

**Comment by outercloudstudio** [comment]
I'll need more information to reproduce the bug.
