### ISSUE TITLE
Error: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.@https://editor.bridge-core.app/assets/main-5a0ecece.js:28:2516

### ISSUE THREAD

**Issue by EBmang101** [bridge-core/editor#924]
**Summary**

**To Reproduce**

4. Observe result

**Observed behavior**
A clear and concise description of what happened
**Expected behavior**

**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

**Platform (please complete the following information):**

-   OS: [e.g. Windows 10]
-   App Version: [e.g. 0.13.3]

**Additional context**

**Comment by outercloudstudio** [comment]
I'll need more information to reproduce the bug.
