### ISSUE TITLE
TypeScript compiler compiles `.d.ts` files.

### ISSUE THREAD

**Issue by Fluffyalien1422** [bridge-core/editor#928]
**Summary**
bridge. v2 compiles `.d.ts` script files.

**To Reproduce**

1. Create a `.d.ts` file in the `scripts` folder containing the following content:
```ts
declare const MY_CONST = 1;
export { MY_CONST };
```
2. Save the file in bridge.
3. View the output in `com.mojang`

**Observed behavior**
bridge. compiled the `.d.ts` file.
**Expected behavior**
The file should be ignored.

**Platform (please complete the following information):**

-   Windows 10
-   App Version:  2.6.0

**Comment by outercloudstudio** [comment]
Blocked until I get access to the Dash npm package. This should probably be implemented within the typescript plugin of Dash.

**Comment by ThomasOrs** [comment]
@outercloudstudio does dash just need to ignore `.d.t.s`?

**Comment by outercloudstudio** [comment]
That would make the most sense to me.

**Comment by outercloudstudio** [comment]
I can take a look at implementing this today if you want.

**Comment by outercloudstudio** [comment]
Oops I forgot I don't have access to the npm package 🤦‍♂️

**Comment by outercloudstudio** [comment]
Going to revise my statement here. We have access to updating dash compiler and I am willing to go ahead and update it but this is low priority since and replacement for Dash is being worked on.
