### ISSUE TITLE
Error: NotFoundError: A requested file or directory could not be found at the time an operation was processed.Error: NotFoundError: A requested file or directory could not be found at the time an operation was processed.    at window.onunhandledrejection (https://tauri.localhost/assets/main-5acbd52f.js:28:2506)

### ISSUE THREAD

**Issue by ChaosDogG** [bridge-core/editor#930]
**Summary**
Trying to import the vanilla behavior packs is not working for whatever reason.

**To Reproduce**

1. Follow the instructions in the app
2. Watch as it fails

**Observed behavior**
When I dragged the vanilla files into the app it threw a fit for some reason
**Expected behavior**
To import the behavior packs with no issues

**Screenshots / File Attachments**
N/A

**Platform (please complete the following information):**

-   OS: Win11
-   App Version: 2.6.0

**Additional context**
N/A

**Comment by outercloudstudio** [comment]
Are you trying to use the vanilla file viewer extension?

**Comment by ChaosDogG** [comment]
Yes, yes I am

**Comment by outercloudstudio** [comment]
Okay thank you for reporting I'll see if I can reproduce this later.

**Comment by outercloudstudio** [comment]
Potentially related to #917

**Comment by ChaosDogG** [comment]
wut can i do to fix this issue?

**Comment by outercloudstudio** [comment]
This bug had been fixed on the dev build. You can wait for the next release or build the dev build yourself to use it right now.
