### ISSUE TITLE
Absolute import path in script

### ISSUE THREAD

**Issue by NguyenDuck** [bridge-core/editor#932]
**Summary**
Autocomplete needs to correct the path to be relative to the directory of "main.js" instead

**Example**

main.js
```ts
import ClassName from "./Library/lib";
```

Instead of

main.js
```ts
import ClassName from "../../../../ProjectName/BP/scripts/Library/lib";
```

**Comment by outercloudstudio** [comment]
I don't seem to get any auto completions for imports. Can you send a video of this happening?

**Comment by outercloudstudio** [comment]
I managed to reproduce this. Will look for a solution later.

**Comment by outercloudstudio** [comment]
Did more digging and found an extremely strange bug. This only occurs when BP is included in the monaco file uri. Replacing all instances of `BP` with `bp` strangely fixes the error. This must be a bug with monaco's resolution.
