### ISSUE TITLE
Wrong content shortcut triggered

### ISSUE THREAD

**Issue by NguyenDuck** [bridge-core/editor#933]
## Summary
Maybe something wrong with tabs view and tab content focus

## To Reproduce

1. Open some files to create tabs
2. Click on content of the tab
3. Press Ctrl + Tab
4. Observe result

## Observed behavior
Switched to other tab in "Browser"
## Expected behavior
Switched current tab to next tab

### Platform:

-   OS: Windows 11
-   App Version: 2.6.1 Nightly

**Comment by outercloudstudio** [comment]
As far as I can tell, this can not be fixed, since these shortcuts are handled by the browser. Perhaps it might be worthwhile the hide this action in the browser build?
