### ISSUE TITLE
Tabs can no longer be rearranged. 

### ISSUE THREAD

**Issue by ExcitedName** [bridge-core/editor#935]
**Summary**
Open tabs can no longer be rearranged. 

**To Reproduce**

1. Open two files.
2 .Attempt to rearrange them.
3. Notice the white circle with the red slash.

**Platform**

-   OS: Windows 11
-   App Version: 2.6.1 native app

**Comment by outercloudstudio** [comment]
Fixed but reopens #917 #852 #930 and #869.
