### ISSUE TITLE
Error: invalid zip fileError: invalid zip file    at window.onunhandledrejection (https://tauri.localhost/assets/main-e00d2ba0.js:28:2506)

### ISSUE THREAD

**Issue by Gamesguor** [bridge-core/editor#941]
**Summary**

**To Reproduce**

4. Observe result

**Observed behavior**
A clear and concise description of what happened
**Expected behavior**

**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

**Platform (please complete the following information):**

-   OS: [e.g. Windows 10]
-   App Version: [e.g. 0.13.3]

**Additional context**

**Comment by outercloudstudio** [comment]
Please fill out the requested information.

**Comment by outercloudstudio** [comment]
Closing as stale.
