### ISSUE TITLE
Error: Error: Overlapping ranges are not allowed!Error: Error: Overlapping ranges are not allowed!    at window.onunhandledrejection (https://tauri.localhost/assets/main-e00d2ba0.js:28:2506)

### ISSUE THREAD

**Issue by punkform** [bridge-core/editor#943]

**Comment by punkform** [comment]
Error: Error: Overlapping ranges are not allowed!
Error: Error: Overlapping ranges are not allowed!
    at window.onunhandledrejection (https://tauri.localhost/assets/main-e00d2ba0.js:28:2506)

**Comment by outercloudstudio** [comment]
Please provide additional information to help us reproduce this. What did you do prior to this error happening?

**Comment by outercloudstudio** [comment]
Closing as stale.
