### ISSUE TITLE
Dragging actions don't work anymore on standalone build

### ISSUE THREAD

**Issue by Tschipp** [bridge-core/editor#948]
**Summary**
Drag actions, like dragging a file into a Preset, or dragging a File around in the file explorer to move it, no longer work in the standalone build.

**To Reproduce**
Try to drag a file in the file explorer.

**Platform (please complete the following information):**

-   OS: Windows 11
-   App Version: 2.6.1

**Comment by outercloudstudio** [comment]
Fixed by 1e50fbc0918d48c11574d238a0fd30565042a7cb
