### ISSUE TITLE
Geometry preview not work when thats generated by using custom components

### ISSUE THREAD

**Issue by NguyenDuck** [bridge-core/editor#949]
**Summary**
As the title, its not work if using a custom component generated the 'texture', 'geometry' components
So, the geometry preview get raw file data ( Not compiled ) to get preview render

**Comment by outercloudstudio** [comment]
Entities don't have texture or geometry components. Are you trying to use a custom component in a resource entity file?

**Comment by outercloudstudio** [comment]
Closing this as stale
