### ISSUE TITLE
Mminecraft:block_sensor dosnt work android

### ISSUE THREAD

**Issue by jason7141** [bridge-core/editor#950]
**Summary**
When I break the diamond ore it should kill the item but dosnt
![Screenshot_20230813-193508_Chrome](https://github.com/bridge-core/editor/assets/105606159/0aae9b4d-43cf-459f-9f8a-51d29502af5a)
![Screenshot_20230813-193454_Chrome](https://github.com/bridge-core/editor/assets/105606159/7b2bee7d-25b0-498f-861d-2e12c6e2869d)
 but does nothing

**To Reproduce**

4. Observe result

**Observed behavior**
A clear and concise description of what happened
**Expected behavior**

**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

**Platform (please complete the following information):**

-   OS: [e.g. Windows 10]
-   App Version: [e.g. 0.13.3]

**Additional context**

**Comment by outercloudstudio** [comment]
This github is for issues with the bridge editor. If you need help with working on addons, feel free to ask in the discord.
