### ISSUE TITLE
[Bug] Certain connected files are not opened correctly

### ISSUE THREAD

**Issue by Tschipp** [bridge-core/editor#955]
**Summary**
Virtual files that are only present in the output (but still connected to the initial file) cannot be opened through the menu.

**To Reproduce**
Use a custom component or the customEntitySyntax plugin that creates a new animation controller file for an entity in the output.
Then try to open it through the connected files action.

**Observed behavior**
Error: Failed to access "E:\....\BridgeWorkspace\projects\Animania\BP\animation_controllers\bridge": Directory does not exist
Error: Error: Failed to access "E:\....\BridgeWorkspace\projects\Animania\BP\animation_controllers\bridge": Directory does not exist
    at window.onunhandledrejection (https://tauri.localhost/assets/main-e00d2ba0.js:28:2506)
**Expected behavior**
It should actually try to find the file at "C:\....\com.mojang\development_behavior_packs\Animania BP\animation_controllers\bridge"

**Screenshots / File Attachments**
![image](https://github.com/bridge-core/editor/assets/11649893/f4f80a26-150e-4a3d-bbe5-fb754e3d2263)
The cmds_xyz.json cannot be opened when clicking
**Platform (please complete the following information):**

-   OS: Win 11
-   App Version: 2.6.1 standalone

**Comment by outercloudstudio** [comment]
This seems to be an issue with the dash compiler. I think it is best to not fix this and let Salp fix this, since I am hesitant to make changes to dash when I don't have access to the npm package.

**Comment by outercloudstudio** [comment]
Going to revise my statement here. We have access to updating dash compiler and I am willing to go ahead and update it but this is low priority since and replacement for Dash is being worked on.
