### ISSUE TITLE
Error: path: C:\Users\ksar9\AppData\Local\com.bridge.dev\bridge\projects\custom crafting test 1 \.gitignore: The system cannot find the path specified. (os error 3)Error: path: C:\Users\ksar9\AppData\Local\com.bridge.dev\bridge\projects\custom crafting test 1 \.gitignore: The system cannot find the path specified. (os error 3)    at window.onunhandledrejection (https://tauri.localhost/assets/main-e00d2ba0.js:28:2506)

### ISSUE THREAD

**Issue by TYLAND74** [bridge-core/editor#956]
**Summary**

**To Reproduce**

4. Observe result

**Observed behavior**
A clear and concise description of what happened
**Expected behavior**

**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

**Platform (please complete the following information):**

-   OS: [e.g. Windows 10]
-   App Version: [e.g. 0.13.3]

**Additional context**

**Comment by ThomasOrs** [comment]
Please fill out the details in the issue so we can better solve this issue

**Comment by outercloudstudio** [comment]
Please provide the requested information.

**Comment by outercloudstudio** [comment]
Closing as stale.
