### ISSUE TITLE
"Error: File does not exist" because Bridge deleted it

### ISSUE THREAD

**Issue by Langtanium** [bridge-core/editor#958]
**Summary**
Error: Error: File does not exist: "projects/Project Name/RP/textures/icons/[object Object]"
    at window.onunhandledrejection (https://tauri.localhost/assets/main-e00d2ba0.js:28:2506)
Tried to import multiple files into a folder using the Import File button. The files I wanted to import got erased and replaced by a file named [object Object]

**To Reproduce**
1. Go to Resource Pack section.
2. Right click on a folder in the textures folder and select import file.
3. Select and import multiple files.
4. The error occurs.
5. Go to the folder that contains the files you wanted to import.
6. Find the files missing and a file named [object Object] in their place.

**Observed behavior**
Using the Import File button from a folder result in the imported file not being imported, but being deleted from their original folder and replaced by a file named [object Object].
**Expected behavior**
When using the Import File button from a folder one should expect the imported files to end up in the folder they where being imported into.

**Platform (please complete the following information):**

-   OS: Windows 10
-   App Version: 2.6.1

**Comment by outercloudstudio** [comment]
I am no longer able to reproduce this. Is this still happening for you?

**Comment by outercloudstudio** [comment]
Closing as stale
