### ISSUE TITLE
Error: Maximum call stack size exceededRangeError: Maximum call stack size exceeded 

### ISSUE THREAD

**Issue by anonymous-90** [bridge-core/editor#959]
**Summary**
bug with the villager v2 entity file opening in bridge 
**To Reproduce**
1. Go to 'villager v2 entity '
2. Click on 'click in to the code the code wait a minute '
3.Observe result

**Observed behavior**
A clear and concise description of what happened
error shows up when attempting to edit or view the villager v2 entity 
also disables suggestions within file when attempting to edit
**Expected behavior**
no error to show up when attempting to edit or view the file and not disabling suggestions 

**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.
![error](https://github.com/bridge-core/editor/assets/72356236/a4c7d038-a361-4a10-af20-a53153ba388f)

**Platform (please complete the following information):**

-   OS: [e.g. Windows 10]
- windows 10 
-   App Version: [e.g. 0.13.3]
      2.6.1
**Additional context**

**Comment by outercloudstudio** [comment]
Is this the villager v2 vanilla file? Are you viewing this through vanilla file viewer?

**Comment by anonymous-90** [comment]
No this is just when I open the entity file without the vanilla pack viewer that I already have the entity inside my project

**Comment by outercloudstudio** [comment]
Fixed by f8574f9d3ca2d0428673a434b459e12235ed3cea
