### ISSUE TITLE
Whenever .wav audiofiles are loaded the editor nearly freezes/crashes

### ISSUE THREAD

**Issue by Mcjiprock** [bridge-core/editor#961]
**.wav audiofiles seem to crash the editor whenever loaded by the editor in any way.**

**To Reproduce**

1. add a .wav audio file
2. refresh the project or save a file anytime after those files have been added, its possible that they need to be of reasonable size like a music track.
4. The editor will start to freeze/lag/and possibly crash

**Observed behavior**
lag
**Expected behavior**
not lag

**Screenshots / File Attachments**
happens with any files, I cant share my files but I can provide you with different files if necessary 

**Platform:**

-   OS: [Windows 10]
-   App Version:  [2.6.1]

**Comment by outercloudstudio** [comment]
I can't seem to reproduce this. What is the size of you Wav file?

**Comment by Mcjiprock** [comment]
Hey, the files are about 18MB in .OGG format (8 files total), converted them from the original .WAV format, its background music. the individual files where about 2-3mb a piece

**Comment by Mcjiprock** [comment]
After converting to OGG I did not encounter any issues with the editor.

**Comment by outercloudstudio** [comment]
Okay thanks for letting me know. Bridge seems to lag a lot with certain non text file types. I'm not sure why yet.

**Comment by outercloudstudio** [comment]
I am still not encountering this. All I noticed was log on importing the large file, but that is to be expected. I'm going to mark this as not being able to reproduce.
