### ISSUE TITLE
New update broke bridge

### ISSUE THREAD

**Issue by Zynxos** [bridge-core/editor#963]
**Summary**
The new Minecraft 1.20.30 update ruined my project and nothing is functional anymore.

**To Reproduce**
If my mod is on a world, it won't work. 

**Observed behavior**
The content log says that all of the recipes malfunctioned because the items "Don't exist." The mod worked last update perfectly

**Expected behavior**
To be able to use my mod

**Screenshots / File Attachments**
(https://cdn.discordapp.com/attachments/1149361450142421033/1155902174098898944/image.png)

**Platform (please complete the following information):**

-   OS: Windows 11
-   App Version: Minecraft = 1.20.30, Bridge = v2.6.1

**Additional context**
The mod is completely broken :(

**Comment by outercloudstudio** [comment]
This is an issue with addons not bridge's fault. You can make a post in addon help in our discord to help fix the issue.
