### ISSUE TITLE
Error: Error: Failed to access "./extensions/MinecraftDocumentationImplementation": Directory does not exist: NotFoundError: A requested file or directory could not be found at the time an operation was processed.Error: Error: Failed to access "./extensions/MinecraftDocumentationImplementation": Directory does not exist: NotFoundError: A requested file or directory could not be found at the time an operation was processed.    at window.onunhandledrejection (https://editor.bridge-core.app/assets/main-62e707fc.js:28:2507)

### ISSUE THREAD

**Issue by zakaria11b** [bridge-core/editor#998]
**Summary**

**To Reproduce**

4. Observe result

**Observed behavior**
A clear and concise description of what happened
**Expected behavior**

**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

**Platform (please complete the following information):**

-   OS: [e.g. Windows 10]
-   App Version: [e.g. 0.13.3]

**Additional context**

**Comment by outercloudstudio** [comment]
Please fill out the requested information

**Comment by outercloudstudio** [comment]
Closing as stale.
